Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2019-07, with the labels that each got.

#98 chore: set CI to use ubuntu-18.04
  .travis.yml
Labels: approved, cncf-cla: yes, size/XS

#100 chore: enable sanity test in CI
  .travis.yml
  Makefile
  test/sanity/README.md
  test/sanity/run-tests-all-clouds.sh
Labels: approved, cncf-cla: yes, kind/design, size/M

#101 chore: don't run sanity test on Azure China Cloud
  deploy/example/azure.json
  test/integration/azure.json
  test/sanity/run-tests-all-clouds.sh
Labels: approved, cncf-cla: yes, size/S

#102 chore: run sanity test in user mode
  test/sanity/run-tests-all-clouds.sh
Labels: approved, cncf-cla: yes, kind/design, size/S

#103 test: randomize volume name
  test/integration/run-test.sh
Labels: approved, cncf-cla: yes, kind/failing-test, size/XS

#104 test: Change test config
  .travis.yml
  test/sanity/run-tests-all-clouds.sh
Labels: approved, cncf-cla: yes, kind/failing-test, size/M

#105 feat: export prometheus metrics
  Gopkg.lock
  Gopkg.toml
  pkg/azurediskplugin/main.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#106 docs: change deployment script
  deploy/v0.2.0/crd-csi-driver-registry.yaml
  deploy/v0.2.0/crd-csi-node-info.yaml
  deploy/v0.2.0/csi-azuredisk-controller.yaml
  deploy/v0.2.0/csi-azuredisk-node.yaml
  deploy/v0.2.0/rbac-csi-azuredisk-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-master.md
  docs/install-csi-driver-v0.2.0.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XL

#108 fix: set driver name
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#109 feat: enable prometheus metrics in deployment
  deploy/csi-azuredisk-controller.yaml
  pkg/azurediskplugin/main.go
Labels: approved, cncf-cla: yes, kind/feature, size/S

#110 fix: return the default MaxVolumesPerNode
  pkg/azuredisk/nodeserver.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#111 docs: add driver log example
  deploy/example/logs/0.2.0/csi-azuredisk-controller.log
  deploy/example/logs/0.2.0/csi-azuredisk-node.log
  deploy/example/logs/0.3.0/csi-azuredisk-controller.log
  deploy/example/logs/0.3.0/csi-azuredisk-node.log
Labels: approved, cncf-cla: yes, kind/documentation

#113 chore: update csi-test vendor
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/kubernetes-csi/csi-test/.travis.yml
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/controller.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/node.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/sanity.go
  vendor/github.com/kubernetes-csi/csi-test/release-tools/LICENSE
Labels: approved, cncf-cla: yes, kind/design, lgtm, size/XL

#114 fix: check DiskSizeGB if it is nil or not
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#107 fix: check the diskName
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, kind/failing-test, lgtm, size/L

#116 test: init klog flags
  test/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/XS

#115 fix: check the disk capacity
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, kind/failing-test, lgtm, size/M

#117 chore: get nodeid from env
  test/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, kind/flake, lgtm, size/XS

#118 fix: check snapshot id if it is empty
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, kind/failing-test, lgtm, size/XS

#120 fix: validate snapshot name
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, kind/failing-test, lgtm, size/S

#121 fix: return empty when the specify snapshot id does not exist
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, kind/failing-test, lgtm, size/XS

#119 fix: return appropriate error code when snapshot exists
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, kind/failing-test, lgtm, size/XS

#123 fix: return empty when the specify source volume id does not exist
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, kind/failing-test, lgtm, size/XS

#125 test: add make container test
  .travis.yml
Labels: approved, cncf-cla: yes, kind/failing-test, size/XS

#124 fix: return appropriate values according to StartingToken and MaxEntries
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
Labels: approved, cncf-cla: yes, kind/bug, kind/failing-test, lgtm, size/L

#127 chore: skip one test sanity test failure in CI test
  .travis.yml
  test/sanity/run-test.sh
  test/sanity/run-tests-all-clouds.sh
Labels: approved, cncf-cla: yes, kind/bug, kind/failing-test, kind/flake, lgtm, size/M

#132 test: add e2e test "dynamically_provisioned_delete_pod_test"
  test/e2e/dynamic_provisioning.go
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/M

#131 test: add e2e test "dynamically_provisioned_collocated_pod_test"
  test/e2e/dynamic_provisioning.go
  test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/M

#134 test: add e2e test "pre_provisioned_reclaim_policy_test"
  test/e2e/pre_provisioning.go
  test/e2e/suite_test.go
  test/e2e/testsuites/pre_provisioned_reclaim_policy_tester.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/L

#133 test: add e2e test "dynamically_provisioned_read_only_volume_test"
  test/e2e/dynamic_provisioning.go
  test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/M
