Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2019-12, with the labels that each got.

#207 fix: golangci-lint error
  hack/verify-golint.sh
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/XS

#176 add topology(zone) support
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/example/storageclass-azuredisk-csi-topology.yaml
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/identityserver.go
  pkg/azuredisk/nodeserver.go
Labels: approved, cncf-cla: yes, kind/feature, size/L

#180 Add e2e test for availability zone scenario
  Makefile
  test/e2e/driver/azuredisk_driver.go
  test/e2e/dynamic_provisioning.go
  test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
  test/e2e/testsuites/dynamically_provisioned_volume_cloning.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/L

#209 Keep helm chart in sync with manifests in deploy folder
  deploy/csi-azuredisk-node.yaml
  hack/verify-all.sh
  hack/verify-helm-chart.sh
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/M

#211 Enable VolumeSnapshotDataSource feature gate in API models
  deploy/example/snapshot/README.md
  test/e2e/manifest/in-tree-vmss.json
  test/e2e/manifest/in-tree.json
  test/e2e/manifest/multi-az.json
  test/e2e/manifest/single-az.json
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/XS

#213 test: reduce e2e pod ready timeout to 10min
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/XS

#215 feat: complete resize feature
  Gopkg.lock
  charts/README.md
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/example/resizing/README.md
  deploy/example/resizing/storageclass-azuredisk-csi-resize.yaml
  deploy/rbac-csi-azuredisk-controller.yaml
  hack/verify-helm-chart.sh
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/nodeserver.go
Labels: approved, cncf-cla: yes, kind/documentation, kind/feature, kind/flake, kind/test, lgtm, size/L

#210 Add additional e2e test cases
  Gopkg.lock
  test/e2e/dynamic_provisioning.go
  test/e2e/pre_provisioning.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go
  test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
  test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/XL

#220 test: Run e2e test suite with JUnit reporter
  Gopkg.lock
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#222 Enable spell checking and fix spelling issues
  deploy/example/logs/0.3.0/csi-azuredisk-controller.log
  hack/verify-all.sh
  hack/verify-spelling.sh
  test/utils/credentials/credentials.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#223 Fix clone process in dev setup doc
  docs/csi-dev.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#224 Enable leader election in csi components
  .gitignore
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/rbac-csi-azuredisk-controller.yaml
  test/utils/azuredisk_log.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#226 chore: print out more driver logs
  test/utils/azuredisk_log.sh
Labels: approved, cncf-cla: yes, kind/test, size/S

#225 fix: disk could not be mounted on Standard_DC4s/DC2s instances
  pkg/azuredisk/azure_common_linux.go
Labels: approved, cncf-cla: yes, kind/bug, size/S

#227 ignore case for managedDiskPathRE and diskSnapshotPathRE
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#234 use azure cloud provider master branch
  Gopkg.lock
  Gopkg.toml
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2019-06-01/storage/accounts.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2019-06-01/storage/blobcontainers.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2019-06-01/storage/blobservices.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2019-06-01/storage/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2019-06-01/storage/fileservices.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2019-06-01/storage/fileshares.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2019-06-01/storage/managementpolicies.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2019-06-01/storage/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2019-06-01/storage/operations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2019-06-01/storage/privateendpointconnections.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2019-06-01/storage/privatelinkresources.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2019-06-01/storage/skus.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2019-06-01/storage/usages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2019-06-01/storage/version.go
  vendor/k8s.io/legacy-cloud-providers/azure/auth/azure_auth.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_backoff.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_blobDiskController.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_client.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_common.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_standard.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_vmss.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_fakes.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_ratelimit.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_standard.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_storage.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_storageaccount.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_vmsets.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_vmss.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_vmss_cache.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_wrap.go
  vendor/k8s.io/legacy-cloud-providers/azure/retry/azure_error.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XXL

#235 feat: BYOK(SSE+CMK) support
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, kind/feature, size/L

#237 test: disable golint check since it does not work
  hack/verify-all.sh
Labels: approved, cncf-cla: yes, kind/test, size/XS

#229 docs: watch does not work in pipe
  docs/install-csi-driver-master.md
  docs/install-csi-driver-v0.2.0.md
  docs/install-csi-driver-v0.3.0.md
  docs/install-csi-driver-v0.4.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/S

#240 Rename test suites to pass linting
  hack/verify-all.sh
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/XS

#236 Support for tags parameter
  docs/driver-parameters.md
  pkg/azuredisk/controllerserver.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#242 chore: use base-ubuntu image from mcr
  pkg/azurediskplugin/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#241 fix: CVE-2019-11255 & mcr image migration
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/S
