Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2019-11, with the labels that each got.

#175 Change package name in Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#181 Add logging for Node{Publish/Unpublish}Volume
  pkg/azuredisk/nodeserver.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#184 Add mock functions to support running UTs on mac
  pkg/azuredisk/azure_common_darwin.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/M

#172 fix golint errors
  test/utils/credentials/credentials.go
  test/utils/credentials/credentials_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#187 Fix verify and e2e CI error
  hack/verify-golint.sh
  test/e2e/suite_test.go
Labels: cncf-cla: yes, lgtm, size/XS

#182 Windows support - set 1 - preparation
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/nodeserver.go
  pkg/mounter/safe_mounter_linux.go
  pkg/mounter/safe_mounter_windows.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#190 Add in-tree API models for e2e jobs
  test/e2e/manifest/in-tree-vmss.json
  test/e2e/manifest/in-tree.json
  test/e2e/manifest/multi-az.json
  test/e2e/manifest/single-az.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#188 Add support to run the tests with in-tree drivers
  pkg/mounter/safe_mounter_unix.go
  test/e2e/README.md
  test/e2e/driver/azuredisk_driver.go
  test/e2e/driver/driver.go
  test/e2e/dynamic_provisioning.go
  test/e2e/pre_provisioning.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/test, lgtm, ok-to-test, size/L

#191 Update VM size to Standard_DS2_v2
  test/e2e/manifest/in-tree-vmss.json
  test/e2e/manifest/in-tree.json
  test/e2e/manifest/multi-az.json
  test/e2e/manifest/single-az.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#186 feat: support volume resize
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/nodeserver.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#195 Remove nodeid empty string check
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#200 test: add xfs fsType e2e test case
  test/e2e/dynamic_provisioning.go
Labels: approved, cncf-cla: yes, kind/test, size/S

#204 Add job info tags to Azure resource groups
  Makefile
  test/utils/azure/azure_helpers.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/S

#196 feat: support volume cloning
  Makefile
  charts/README.md
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/example/cloning/README.md
  deploy/example/cloning/nginx-pod-restored-cloning.yaml
  deploy/example/cloning/pvc-azuredisk-cloning.yaml
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/controllerserver.go
  test/e2e/dynamic_provisioning.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_volume_cloning.go
  test/e2e/testsuites/specs.go
  test/utils/azuredisk_log.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L
