Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2019-03, with the labels that each got.

#57 add OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, kind/design, lgtm, size/XS

#60 Adds MaxVolumesPerNode info in NodeGetInfoResponse
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#62 Fail ControllerPublishVolume when volume doesn't exist
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#61 Fail ControllerPublishVolume when no node exists
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#69 fix(klog): fix info values not getting printed with klog
  pkg/azurediskplugin/main.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#70 enhance(version): Add version flag in azuredisk plugin
  Gopkg.lock
  Makefile
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/version.go
  pkg/azurediskplugin/main.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L
