Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2019-10, with the labels that each got.

#165 fix getting instance id failure
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, size/S

#169 Disable UseInstanceMetadata in controller server
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#170 doc: cut off v0.4.0 beta release
  README.md
  charts/v0.4.0/azuredisk-csi-driver/Chart.yaml
  charts/v0.4.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v0.4.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v0.4.0/azuredisk-csi-driver/templates/crd-csi-driver-registry.yaml
  charts/v0.4.0/azuredisk-csi-driver/templates/crd-csi-node-info.yaml
  charts/v0.4.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v0.4.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v0.4.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v0.4.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v0.4.0/azuredisk-csi-driver/values.yaml
  deploy/v0.4.0/crd-csi-driver-registry.yaml
  deploy/v0.4.0/crd-csi-node-info.yaml
  deploy/v0.4.0/csi-azuredisk-controller.yaml
  deploy/v0.4.0/csi-azuredisk-node.yaml
  deploy/v0.4.0/rbac-csi-azuredisk-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v0.4.0.md
Labels: approved, cncf-cla: yes, size/XXL

#166 Refactor test scripts & enable E2E test on kubernetes/test-infra
  .travis.yml
  Gopkg.lock
  Makefile
  charts/README.md
  docs/csi-dev.md
  hack/verify-all.sh
  hack/verify-dep.sh
  hack/verify-gofmt.sh
  hack/verify-golint.sh
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
  pkg/azurediskplugin/main.go
  test/e2e/driver/azuredisk_csi_driver.go
  test/e2e/dynamic_provisioning.go
  test/e2e/pre_provisioning.go
  test/e2e/run-test.sh
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
  test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/pre_provisioned_reclaim_policy_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
  test/integration/azure.json
  test/integration/integration_test.go
  test/integration/run-test.sh
  test/integration/run-tests-all-clouds.sh
  test/sanity/run-test.sh
  test/sanity/run-tests-all-clouds.sh
  test/sanity/sanity_test.go
  test/utils/azure/azure_helpers.go
  test/utils/credentials/credentials.go
  test/utils/credentials/credentials_test.go
  test/utils/testutil/testutil.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/deploymentoperations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/deployments.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/groups.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/operations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/providers.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/resources.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/tags.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/version.go
  vendor/github.com/pelletier/go-toml/LICENSE
  vendor/github.com/pelletier/go-toml/doc.go
  vendor/github.com/pelletier/go-toml/fuzz.go
  vendor/github.com/pelletier/go-toml/keysparsing.go
  vendor/github.com/pelletier/go-toml/lexer.go
  vendor/github.com/pelletier/go-toml/marshal.go
  vendor/github.com/pelletier/go-toml/parser.go
  vendor/github.com/pelletier/go-toml/position.go
  vendor/github.com/pelletier/go-toml/token.go
  vendor/github.com/pelletier/go-toml/toml.go
  vendor/github.com/pelletier/go-toml/tomltree_create.go
  vendor/github.com/pelletier/go-toml/tomltree_write.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#173 doc: add build-push make command
  Makefile
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#174 fix: use secure ubuntu image
  pkg/azurediskplugin/Dockerfile
Labels: approved, cncf-cla: yes, kind/feature, size/XS
