Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2019-08, with the labels that each got.

#135 test: add e2e test "pre_provisioned_read_only_volume_test"
  test/e2e/pre_provisioning.go
  test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/M

#136 test: add e2e test "dynamically_provisioned_reclaim_policy_test"
  test/e2e/dynamic_provisioning.go
  test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/M

#138 doc: cut off v0.3.0 beta release
  README.md
  deploy/v0.3.0/crd-csi-driver-registry.yaml
  deploy/v0.3.0/crd-csi-node-info.yaml
  deploy/v0.3.0/csi-azuredisk-controller.yaml
  deploy/v0.3.0/csi-azuredisk-node.yaml
  deploy/v0.3.0/rbac-csi-azuredisk-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v0.3.0.md
Labels: approved, cncf-cla: yes, size/XL

#142 doc: upgrade master deployment to use v0.4.0
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node.yaml
Labels: cncf-cla: yes, kind/documentation

#150 feat: set priority class to system critical
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node.yaml
  deploy/v0.2.0/csi-azuredisk-controller.yaml
  deploy/v0.2.0/csi-azuredisk-node.yaml
  deploy/v0.3.0/csi-azuredisk-controller.yaml
  deploy/v0.3.0/csi-azuredisk-node.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#151 chore: use latest version tag for master branch
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/XS

#137 feat: add raw block volume support
  deploy/example/rawblock/README.md
  deploy/example/rawblock/nginx-pod-azuredisk.yaml
  deploy/example/rawblock/pvc-azuredisk-csi.yaml
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
  test/e2e/dynamic_provisioning.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#154 feat: support azure disk with partitions in disk mount
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/nodeserver.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#157 chore: use kube-system instead of csi-demo
  charts/README.md
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v0.2.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v0.2.0/azuredisk-csi-driver/values.yaml
  charts/v0.3.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
Labels: approved, cncf-cla: yes, kind/documentation, kind/flake, lgtm, size/M

#158 feat: fix CSI migration issue
  deploy/csi-azuredisk-controller.yaml
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, kind/feature, size/S

#156 docs: add snapshot feature doc
  deploy/example/snapshot/README.md
  deploy/example/snapshot/nginx-pod-restored-snapshot.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M
