Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2020-05, with the labels that each got.

#386 chore: upgrade snapshot controller to v2.1.1
  charts/latest/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/crd-csi-snapshot.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-snapshot-controller.yaml
  hack/verify-yamllint.sh
Labels: approved, cncf-cla: yes, kind/feature, size/L

#388 chore: lower the cpu/memory limits
  Makefile
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/M

#392 test: remove "storageProfile" field in test config
  test/e2e/manifest/in-tree-vmss.json
  test/e2e/manifest/in-tree.json
  test/e2e/manifest/migration.json
Labels: approved, cncf-cla: yes, kind/test, size/XS

#394 test: add snapshot controller image version check
  hack/verify-helm-chart.sh
Labels: cncf-cla: yes, kind/test, size/XS

#396 feat: update base image with debian-base
  Makefile
  pkg/azurediskplugin/Dockerfile
  pkg/azurediskplugin/Windows.Dockerfile
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#397 test: add publish image support
  Makefile
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/test, size/M

#400 feat: use `azure-cred-file` configmap in `kube-system` namespace to specify azure-cred-file path
  README.md
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  pkg/azuredisk/azure.go
  pkg/azuredisk/azure_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#401 fix: empty azure cred file issue
  pkg/azuredisk/azure.go
Labels: approved, cncf-cla: yes, kind/bug, size/S

#410 fix: support snapshot on disk from external resource group
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#405 feat: enable incremental snapshot feature
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#412 Add Unit tests
  pkg/azuredisk/nodeserver_test.go
  pkg/csi-common/controllerserver-default.go
  pkg/csi-common/controllerserver-default_test.go
  pkg/csi-common/driver_test.go
  pkg/csi-common/identityserver-default_test.go
  pkg/csi-common/utils_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/L

#414 test: set timeout as 10min for windows pod
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/test, size/S

#415 test: change Unicode encoding to String
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, size/XS

#416 fix windows docs
  deploy/csi-azuredisk-node-windows.yaml
  deploy/example/windows/README.md
  deploy/example/windows/deployment.yaml
  deploy/example/windows/statefulset.yaml
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/documentation, size/M
