Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2020-02, with the labels that each got.

#272 Add userAssignedID field in API model
  test/e2e/manifest/single-az.json
Labels: cncf-cla: yes

#271 feat: enable hostNetwork to support MSI
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node.yaml
  test/utils/check_driver_pods_restart.sh
Labels: approved, cncf-cla: yes, kind/feature, size/S

#261 Add negative mountOptions test case
  Gopkg.lock
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_invalid_mount_options.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/L

#277 chore: change port num for this driver
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node.yaml
  pkg/azurediskplugin/main.go
  test/utils/check_driver_pods_restart.sh
Labels: approved, cncf-cla: yes, kind/feature, size/M

#279 fix: yaml file format
  charts/latest/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  deploy/crd-csi-node-info.yaml
  deploy/crd-csi-snapshot.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-driver.yaml
  deploy/csi-azuredisk-node.yaml
  deploy/csi-snapshot-controller.yaml
  deploy/rbac-csi-snapshot-controller.yaml
  docs/install-csi-driver-master.md
  hack/verify-all.sh
  hack/verify-yamllint.sh
Labels: approved, cncf-cla: yes, kind/bug, size/L

#281 fix: improve disk detection inside VM
  pkg/azuredisk/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#216 feat: Implement NodeGetVolumestats feature
  Gopkg.lock
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/nodeserver.go
  test/sanity/run-test.sh
  test/utils/azure/azure_helpers.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#282 chore: scripts modification
  deploy/remove-driver.sh
  hack/verify-yamllint.sh
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/nodeserver.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#284 fix: return codes.NotFound instead of codes.Internal in NodeGetVolume…
  pkg/azuredisk/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#285 fix: find lun with timeout issue
  deploy/uninstall-driver.sh
  pkg/azuredisk/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#289 chore: upgrade to latest azure cloud provider
  Gopkg.lock
  vendor/github.com/prometheus/procfs/crypto.go
  vendor/github.com/prometheus/procfs/loadavg.go
  vendor/github.com/prometheus/procfs/net_conntrackstat.go
  vendor/github.com/prometheus/procfs/net_softnet.go
  vendor/github.com/prometheus/procfs/net_udp.go
  vendor/github.com/prometheus/procfs/net_unix.go
  vendor/github.com/prometheus/procfs/proc_status.go
  vendor/github.com/prometheus/procfs/swaps.go
  vendor/golang.org/x/sys/unix/syscall_linux_mips64x.go
  vendor/k8s.io/cloud-provider/cloud.go
  vendor/k8s.io/legacy-cloud-providers/azure/auth/azure_auth.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_common.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_standard.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_vmss.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_fakes.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_vmsets.go
  vendor/k8s.io/legacy-cloud-providers/azure/retry/azure_error.go
  vendor/k8s.io/legacy-cloud-providers/azure/retry/azure_retry.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/feature, size/XXL

#287 fix: use KubeRegistry instead of prometheus default registry
  charts/README.md
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-node.yaml
  pkg/azurediskplugin/main.go
Labels: approved, cncf-cla: yes, kind/bug, kind/flake, lgtm, size/S

#293 fix yaml format
  README.md
  deploy/example/cloning/nginx-pod-restored-cloning.yaml
  deploy/example/cloning/pvc-azuredisk-cloning.yaml
  deploy/example/metrics/README.md
  deploy/example/metrics/csi-azuredisk-controller-svc.yaml
  deploy/example/nginx-pod-azuredisk.yaml
  deploy/example/pv-azuredisk-csi.yaml
  deploy/example/pvc-azuredisk-csi-static.yaml
  deploy/example/pvc-azuredisk-csi.yaml
  deploy/example/rawblock/nginx-pod-azuredisk.yaml
  deploy/example/rawblock/pvc-azuredisk-csi.yaml
  deploy/example/resize/README.md
  deploy/example/resizing/storageclass-azuredisk-csi-resize.yaml
  deploy/example/snapshot/azuredisk-volume-snapshot.yaml
  deploy/example/snapshot/nginx-pod-restored-snapshot.yaml
  deploy/example/snapshot/pvc-azuredisk-snapshot-restored.yaml
  deploy/example/snapshot/storageclass-azuredisk-snapshot.yaml
  deploy/example/storageclass-azuredisk-csi-topology.yaml
  deploy/example/storageclass-azuredisk-csi.yaml
  hack/verify-yamllint.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#291 feat: add azure disk WriteAccelerator support
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  deploy/csi-azuredisk-driver.yaml
  docs/driver-parameters.md
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/nodeserver.go
Labels: approved, cncf-cla: yes, kind/feature, size/M

#295 fix: get max disk count by static table
  pkg/azuredisk/azure_dd_max_disk_count.go
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/L

#296 doc: cut off v0.6.0 release
  CHANGELOG-v0.1.0-alpha.md
  CHANGELOG-v0.2.0-alpha.md
  README.md
  charts/v0.6.0/azuredisk-csi-driver/Chart.yaml
  charts/v0.6.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v0.6.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v0.6.0/azuredisk-csi-driver/templates/crd-csi-node-info.yaml
  charts/v0.6.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v0.6.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v0.6.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v0.6.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v0.6.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v0.6.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v0.6.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v0.6.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v0.6.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v0.6.0/azuredisk-csi-driver/values.yaml
  deploy/v0.6.0/crd-csi-node-info.yaml
  deploy/v0.6.0/crd-csi-snapshot.yaml
  deploy/v0.6.0/csi-azuredisk-controller.yaml
  deploy/v0.6.0/csi-azuredisk-driver.yaml
  deploy/v0.6.0/csi-azuredisk-node.yaml
  deploy/v0.6.0/csi-snapshot-controller.yaml
  deploy/v0.6.0/rbac-csi-azuredisk-controller.yaml
  deploy/v0.6.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v0.6.0.md
  pkg/azuredisk/nodeserver.go
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XXL

#298 test: add in-tree-migration.json
  test/e2e/manifest/migration.json
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/M

#300 chore: update azure cloud to use fake clients
  Gopkg.lock
  vendor/golang.org/x/crypto/chacha20/chacha_arm64.go
  vendor/golang.org/x/crypto/chacha20/chacha_arm64.s
  vendor/golang.org/x/crypto/chacha20/chacha_generic.go
  vendor/golang.org/x/crypto/chacha20/chacha_noasm.go
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.go
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.s
  vendor/golang.org/x/crypto/chacha20/chacha_s390x.go
  vendor/golang.org/x/crypto/chacha20/chacha_s390x.s
  vendor/golang.org/x/crypto/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/poly1305/sum_amd64.go
  vendor/golang.org/x/crypto/poly1305/sum_amd64.s
  vendor/golang.org/x/crypto/poly1305/sum_noasm.go
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.go
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.s
  vendor/golang.org/x/crypto/poly1305/sum_s390x.go
  vendor/golang.org/x/crypto/poly1305/sum_s390x.s
  vendor/golang.org/x/crypto/poly1305/sum_vmsl_s390x.s
  vendor/k8s.io/legacy-cloud-providers/azure/azure_fakes.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_utils.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_vmss.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/L

#301 test: add the unit test for ensureMountPoint func
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/M

#303 doc: update v0.6.0 installation
  docs/install-csi-driver-v0.6.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#247 Introduce CSI proxy calls
  Gopkg.lock
  Gopkg.toml
  pkg/azuredisk/azure_common_darwin.go
  pkg/azuredisk/azure_common_linux.go
  pkg/azuredisk/azure_common_test.go
  pkg/azuredisk/azure_common_windows.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
  pkg/csi-common/server.go
  pkg/mounter/safe_mounter_unix.go
  pkg/mounter/safe_mounter_windows.go
  vendor/github.com/kubernetes-csi/csi-proxy/LICENSE
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/disk/v1alpha1/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v1alpha1/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/volume/v1alpha1/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/apiversion/version.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/disk/v1alpha1/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/filesystem/v1alpha1/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/volume/v1alpha1/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/utils.go
  vendor/github.com/kubernetes-csi/csi-proxy/release-tools/LICENSE
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XXL

#304 fix: correct the behavior of deleting the target direcotory
  pkg/azuredisk/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S
