Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2020-03, with the labels that each got.

#307 feat: add taints to run controller on master node
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-snapshot-controller.yaml
  deploy/example/deployment.yaml
  deploy/example/statefulset.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#308 fix: support corrupted mount
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/nodeserver.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#310 Normalize paths used in calls to CSI proxy
  pkg/mounter/safe_mounter_windows.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#311 test: install driver during migration job
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#313 fix: use /dev instead of /devhost in volume mapping
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  deploy/csi-azuredisk-node.yaml
  pkg/azuredisk/azure_common_linux.go
  pkg/azuredisk/azure_common_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#315 chore: change default type from Standard to StandardSSD
  docs/driver-parameters.md
  pkg/azuredisk/azure_common.go
  pkg/azuredisk/azure_common_test.go
  test/e2e/suite_test.go
  test/utils/azuredisk_log.sh
Labels: approved, cncf-cla: yes, kind/feature, size/S

#316 test: do not run make e2e-teardown when testing in-tree volume plugin
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#319 Fix cleanupmountpoint to make os specific calls
  pkg/azuredisk/azure_common_darwin.go
  pkg/azuredisk/azure_common_linux.go
  pkg/azuredisk/azure_common_windows.go
  pkg/azuredisk/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#318 docs fix: use correct path to check volume contents
  deploy/example/snapshot/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#321 Windows CSI deployment instructions and yaml
  deploy/csi-azuredisk-node-windows.yaml
  docs/install-csi-driver-master.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#323 feat: shared disk support
  Gopkg.lock
  pkg/azuredisk/controllerserver.go
  test/e2e/pre_provisioning_test.go
  vendor/github.com/Azure/azure-sdk-for-go/version/version.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/syscall_illumos.go
  vendor/golang.org/x/sys/unix/zsyscall_illumos_amd64.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_common.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_fakes.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_vmss.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/diskclient/interface.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/vmssclient/azure_vmssclient.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/vmssclient/interface.go
  vendor/k8s.io/utils/net/net.go
Labels: approved, cncf-cla: yes, kind/feature, size/L

#324 doc: add windows feature doc
  deploy/example/windows/README.md
  deploy/example/windows/aspnetapp.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#320 Add e2e test support for Windows clusters
  Makefile
  test/e2e/README.md
  test/e2e/driver/azuredisk_driver.go
  test/e2e/driver/driver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/manifest/in-tree-vmss.json
  test/e2e/manifest/in-tree.json
  test/e2e/manifest/migration.json
  test/e2e/manifest/multi-az.json
  test/e2e/manifest/single-az.json
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#325 doc: polish windows feature doc
  README.md
  deploy/example/windows/README.md
  deploy/example/windows/aspnetapp.yaml
  deploy/example/windows/deployment.yaml
  deploy/example/windows/statefulset.yaml
  deploy/install-driver-standalone.sh
  deploy/uninstall-driver-standalone.sh
  docs/install-csi-driver-master.md
  hack/verify-yamllint.sh
Labels: approved, cncf-cla: yes, size/L

#326 feat: enable RWX for shared disk
  Makefile
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, kind/feature, size/M

#329 Fix typo
  deploy/example/windows/README.md
Labels: cncf-cla: yes, kind/documentation, size/XS

#327 doc: shared disk doc
  README.md
  deploy/example/rawblock/README.md
  deploy/example/rawblock/nginx-pod-azuredisk.yaml
  deploy/example/sharedisk/README.md
  deploy/example/sharedisk/deployment.yaml
  hack/verify-yamllint.sh
Labels: approved, cncf-cla: yes, size/L

#330 beta.kubernetes.io/arch is already deprecated since v1.14, are targeted for removal in v1.18 or v1.19
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v0.6.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v0.6.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  deploy/csi-snapshot-controller.yaml
  deploy/example/cloning/nginx-pod-restored-cloning.yaml
  deploy/example/nginx-pod-azuredisk.yaml
  deploy/example/rawblock/README.md
  deploy/example/rawblock/nginx-pod-azuredisk.yaml
  deploy/example/snapshot/nginx-pod-restored-snapshot.yaml
  deploy/example/windows/deployment.yaml
  deploy/example/windows/statefulset.yaml
  deploy/v0.6.0/csi-azuredisk-controller.yaml
  deploy/v0.6.0/csi-azuredisk-node.yaml
  deploy/v0.6.0/csi-snapshot-controller.yaml
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#336 fix: change imagePullPolicy to IfNotPresent
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  charts/v0.2.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v0.2.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v0.2.0/azuredisk-csi-driver/values.yaml
  charts/v0.3.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v0.3.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v0.3.0/azuredisk-csi-driver/values.yaml
  charts/v0.4.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v0.4.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v0.4.0/azuredisk-csi-driver/values.yaml
  charts/v0.5.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v0.5.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v0.5.0/azuredisk-csi-driver/values.yaml
  charts/v0.6.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v0.6.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v0.6.0/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  deploy/csi-snapshot-controller.yaml
  deploy/v0.2.0/csi-azuredisk-controller.yaml
  deploy/v0.2.0/csi-azuredisk-node.yaml
  deploy/v0.3.0/csi-azuredisk-controller.yaml
  deploy/v0.3.0/csi-azuredisk-node.yaml
  deploy/v0.4.0/csi-azuredisk-controller.yaml
  deploy/v0.4.0/csi-azuredisk-node.yaml
  deploy/v0.5.0/csi-azuredisk-controller.yaml
  deploy/v0.5.0/csi-azuredisk-node.yaml
  deploy/v0.6.0/csi-azuredisk-controller.yaml
  deploy/v0.6.0/csi-azuredisk-node.yaml
  deploy/v0.6.0/csi-snapshot-controller.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#337 doc: change windows related doc, script
  README.md
  deploy/csi-azuredisk-node-windows.yaml
  deploy/example/snapshot/README.md
  deploy/example/windows/README.md
  deploy/install-driver-standalone.sh
  deploy/uninstall-driver-standalone.sh
  docs/install-csi-driver-master.md
  pkg/azurediskplugin/README.md
Labels: approved, cncf-cla: yes, kind/documentation, size/L

#341 doc: remove useless scripts
  deploy/install-driver.sh
  deploy/uninstall-driver.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#343 test: add install/uninstall deployment script test
  deploy/example/windows/README.md
  deploy/install-driver.sh
  deploy/uninstall-driver.sh
  docs/install-csi-driver-master.md
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/M
