Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2020-01, with the labels that each got.

#243 chore: switch to mcr repo
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
Labels: approved, cncf-cla: yes, size/XS

#245 Doc for version v0.5.0
  README.md
  deploy/example/topology/README.md
  test/utils/azuredisk_log.sh
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#248 doc: cut off v0.5.0 beta release
  README.md
  charts/v0.5.0/azuredisk-csi-driver/Chart.yaml
  charts/v0.5.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v0.5.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v0.5.0/azuredisk-csi-driver/templates/crd-csi-driver-registry.yaml
  charts/v0.5.0/azuredisk-csi-driver/templates/crd-csi-node-info.yaml
  charts/v0.5.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v0.5.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v0.5.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v0.5.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v0.5.0/azuredisk-csi-driver/values.yaml
  deploy/v0.5.0/crd-csi-driver-registry.yaml
  deploy/v0.5.0/crd-csi-node-info.yaml
  deploy/v0.5.0/csi-azuredisk-controller.yaml
  deploy/v0.5.0/csi-azuredisk-node.yaml
  deploy/v0.5.0/rbac-csi-azuredisk-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v0.5.0.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XXL

#244 Setting cpu/memory requests/limits for csi driver containers
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#252 chore: change CSIDriver from alpha to beta
  charts/latest/azuredisk-csi-driver/templates/crd-csi-driver-registry.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  deploy/crd-csi-driver-registry.yaml
  deploy/csi-azuredisk-driver.yaml
  deploy/install-driver.sh
  docs/install-csi-driver-master.md
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/M

#250 chore: remove nodeid restriction
  docs/csi-dev.md
  pkg/azurediskplugin/main.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#258 chore: clean up the redundant code
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#263 chore: add driver pods check
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
  test/utils/check_driver_pods_restart.sh
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/L

#264 chore: fix broken coverage
  .travis.yml
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/S

#265 chore: set replica of controller as 2
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node.yaml
  deploy/rbac-csi-azuredisk-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#266 Enable MSI option for VMAS cluster
  test/e2e/manifest/multi-az.json
  test/e2e/manifest/single-az.json
Labels: approved, cncf-cla: yes, lgtm, size/XS
