Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2020-12, with the labels that each got.

#607 fix: skip raw block node volume expansion
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#609 fix: windows image build error
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#611 test: optimize buildkit setting
  Makefile
Labels: approved, cncf-cla: yes, kind/test, size/XS

#612 chore: Remove unnecessary permissions from external-snapshotter role.
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  deploy/rbac-csi-azuredisk-controller.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/M

#619 test: remove buildkit workaround
  Makefile
Labels: approved, cncf-cla: yes, kind/test, size/XS

#624 chore: remove useless code
  pkg/csi-common/utils.go
Labels: approved, cncf-cla: yes, kind/cleanup, size/S

#627 chore: upgrade cloud-provider-azure
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/diskclient/mockdiskclient/interface.go
Labels: approved, cncf-cla: yes, kind/test, size/S

#629 chore: use go 1.15
  go.mod
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/test, size/M

#631 fix: Fix default Docker Hub prefix generation.
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#634 test: fix windows output encoding for statefulset and deployment e2e test cases
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
  test/utils/check_driver_pods_restart.sh
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/XS

#636 fix: windows support for Azure Stack
  Makefile
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node-windows.yaml
  test/e2e/testsuites/testsuites.go
  test/integration/run-tests-all-clouds.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#618 feat: Implement ListVolumes
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/fake_azuredisk.go
  test/integration/run-test.sh
  test/sanity/run-test.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#640 fix: Set right errorCode for NodeExpandVolume failure
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#642 fix: List only snapshots that match the volumeId
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#643 fix: make node stage and publish idempotent
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/bug, size/M

#620 test: upgrade sanity-test to v4.0.2
  test/sanity/run-test.sh
  test/sanity/run-tests-all-clouds.sh
Labels: approved, cncf-cla: yes, kind/test, size/XS

#644 test: disable statefulset test on CSI Windows
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/test, size/XS

#647 Clean up hack/verify-dep.sh
  hack/verify-dep.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#649 feat: add pv name tag on disk creation
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_tag_tester.go
Labels: approved, cncf-cla: yes, kind/feature, size/S

#650 feat: support Azure disk batch attach/detach
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_mock_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets.go
Labels: approved, cncf-cla: yes, kind/feature, size/XL

#651 test: add UltraSSD e2e test
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/test, size/S
