Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2020-09, with the labels that each got.

#515 fix: use CMD command to avoid the encoding issue
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#517 Update debian base image to v2.1.3
  pkg/azurediskplugin/Dockerfile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#521 test: add Windows unit test pipeline
  .github/workflows/windows.yml
  pkg/azuredisk/azure_common_test.go
  pkg/azuredisk/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/test, size/S

#523 chore: set provisioner timeout as 15s
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-controller.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, size/XS

#522 fix: unit test failure on Windows
  .github/workflows/windows.yml
  pkg/azuredisk/azure_test.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, kind/test, lgtm, ok-to-test, size/S

#532 fix: create snapshot on external resource group failure
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
Labels: approved, cncf-cla: yes, kind/bug, size/L

#529 Add metrics for azure disk attach and detach operations
  go.mod
  go.sum
  pkg/azuredisk/controllerserver.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_standard.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_vmss.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_routes.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_standard.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_vmss.go
  vendor/k8s.io/legacy-cloud-providers/azure/cache/azure_cache.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/armclient/azure_armclient.go
  vendor/k8s.io/legacy-cloud-providers/azure/metrics/azure_metrics.go
  vendor/k8s.io/legacy-cloud-providers/azure/retry/azure_error.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#527 chore: change image repo address
  README.md
  charts/README.md
  deploy/example/snapshot/README.md
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/documentation, size/S

#537 doc: cut v0.9.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v0.9.0/azuredisk-csi-driver-v0.9.0.tgz
  charts/v0.9.0/azuredisk-csi-driver/Chart.yaml
  charts/v0.9.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v0.9.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v0.9.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v0.9.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v0.9.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v0.9.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v0.9.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v0.9.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v0.9.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v0.9.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v0.9.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v0.9.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v0.9.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v0.9.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v0.9.0/azuredisk-csi-driver/values.yaml
  deploy/v0.9.0/crd-csi-snapshot.yaml
  deploy/v0.9.0/csi-azuredisk-controller.yaml
  deploy/v0.9.0/csi-azuredisk-driver.yaml
  deploy/v0.9.0/csi-azuredisk-node-windows.yaml
  deploy/v0.9.0/csi-azuredisk-node.yaml
  deploy/v0.9.0/csi-snapshot-controller.yaml
  deploy/v0.9.0/rbac-csi-azuredisk-controller.yaml
  deploy/v0.9.0/rbac-csi-azuredisk-node.yaml
  deploy/v0.9.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v0.9.0.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XXL

#543 test: migration test on Windows
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/test, size/S

#545 Make GO111MODULE on by default in Makefile
  Makefile
  test/sanity/run-tests-all-clouds.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#546 test: add example test
  Makefile
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/test, size/S

#548 test: switch to use mcr nginx image
  deploy/example/cloning/nginx-pod-restored-cloning.yaml
  deploy/example/deployment.yaml
  deploy/example/nginx-pod-azuredisk.yaml
  deploy/example/rawblock/README.md
  deploy/example/rawblock/nginx-pod-azuredisk.yaml
  deploy/example/sharedisk/README.md
  deploy/example/sharedisk/deployment.yaml
  deploy/example/snapshot/nginx-pod-restored-snapshot.yaml
  docs/known-issues/node-shutdown-recovery/statefulset-azuredisk.yaml
Labels: approved, cncf-cla: yes, kind/test, size/S

#550 test: increase windows test vm size
  test/e2e/manifest/migration-windows.json
  test/utils/azuredisk_log.sh
Labels: approved, cncf-cla: yes, kind/test, size/XS

#552 CI: Add `golangci-linter` to github actions
  .github/workflows/static.yaml
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/S

#554 chore: field name refactor
  Makefile
  deploy/example/deployment.yaml
  deploy/example/windows/deployment.yaml
  deploy/example/windows/statefulset.yaml
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  test/utils/check_driver_pods_restart.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#557 test: print restart pod logs once
  test/e2e/suite_test.go
  test/utils/check_driver_pods_restart.sh
Labels: approved, cncf-cla: yes, kind/test, size/S

#558 fix: create nonroot user in Dockerfile
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node.yaml
  pkg/azurediskplugin/Dockerfile
  pkg/azurediskplugin/dev.Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, size/S
