Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2020-06, with the labels that each got.

#418 Add resource group parameter to volumesnapshot
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#420 Add Unit tests
  pkg/azuredisk/identityserver_test.go
  pkg/azuredisk/version_test.go
  pkg/mounter/safe_mounter_unix_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/L

#422 Add Unit tests in pkg/azuredisk/controllerserver_test.
  pkg/azuredisk/controllerserver_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/L

#423 doc: rename storage class to managed-csi
  .github/PULL_REQUEST_TEMPLATE.md
  deploy/example/cloning/pvc-azuredisk-cloning.yaml
  deploy/example/deployment.yaml
  deploy/example/pvc-azuredisk-csi.yaml
  deploy/example/rawblock/README.md
  deploy/example/rawblock/pvc-azuredisk-csi.yaml
  deploy/example/resize/README.md
  deploy/example/sharedisk/README.md
  deploy/example/sharedisk/deployment.yaml
  deploy/example/snapshot/pvc-azuredisk-snapshot-restored.yaml
  deploy/example/storageclass-azuredisk-csi-allowed-topologies.yaml
  deploy/example/storageclass-azuredisk-csi-topology.yaml
  deploy/example/storageclass-azuredisk-csi.yaml
  deploy/example/topology/README.md
  deploy/example/windows/deployment.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#425 doc: fix partition doc
  docs/driver-parameters.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#426 Charts: refine helm installation
  charts/README.md
  charts/index.yaml
  charts/v0.6.0/azuredisk-csi-driver-v0.6.0.tgz
  charts/v0.7.0/azuredisk-csi-driver-v0.7.0.tgz
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#429 Delete common crd-csi-node-info.yaml and fix usage of helm3
  charts/README.md
  charts/latest/azuredisk-csi-driver/templates/crd-csi-node-info.yaml
  charts/v0.6.0/azuredisk-csi-driver-v0.6.0.tgz
  charts/v0.6.0/azuredisk-csi-driver/templates/crd-csi-node-info.yaml
  charts/v0.7.0/azuredisk-csi-driver-v0.7.0.tgz
  charts/v0.7.0/azuredisk-csi-driver/templates/crd-csi-node-info.yaml
  deploy/crd-csi-node-info.yaml
  deploy/install-driver.sh
  deploy/uninstall-driver.sh
  deploy/v0.6.0/crd-csi-node-info.yaml
  deploy/v0.7.0/crd-csi-node-info.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#430 fix: incorrect max azure disk max count
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: approved, cncf-cla: yes, kind/bug, size/M

#432 feat: update provider lib to use force detach
  go.mod
  go.sum
  vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_standard.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_vmss.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_instances.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, size/M

#431 test: add multiple PVs e2e tests
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_pod_with_multiple_pv.go
  test/e2e/testsuites/specs.go
Labels: approved, cncf-cla: yes, kind/test, size/M

#435 test: fix failure in running multiple volume e2e test
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, size/XS
