Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2020-08, with the labels that each got.

#471 test: add unit-test for unimplemented method
  pkg/azuredisk/controllerserver_test.go
  pkg/csi-common/controllerserver-default_test.go
  pkg/csi-common/fake_driver_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/L

#474 test: add unit-test for azuredisk nodeserver and createvolume.
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/L

#477 test: add unit-test in controllerserver and serve
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azurediskplugin/main.go
  pkg/csi-common/server.go
  pkg/csi-common/server_test.go
  pkg/csi-common/utils.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#475 chore: reduce limit of CPUand Memory
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  deploy/csi-snapshot-controller.yaml
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/L

#479 test: add unit-test in controllerserver and nodeserver
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/nodeserver_test.go
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, kind/test, ok-to-test, size/L

#478 test: fix in-tree resie e2e test failure
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
Labels: approved, cncf-cla: yes, size/S

#481 doc: cut v0.8.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v0.8.0/azuredisk-csi-driver-v0.8.0.tgz
  charts/v0.8.0/azuredisk-csi-driver/Chart.yaml
  charts/v0.8.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v0.8.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v0.8.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v0.8.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v0.8.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v0.8.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v0.8.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v0.8.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v0.8.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v0.8.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v0.8.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v0.8.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v0.8.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v0.8.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v0.8.0/azuredisk-csi-driver/values.yaml
  deploy/v0.8.0/crd-csi-snapshot.yaml
  deploy/v0.8.0/csi-azuredisk-controller.yaml
  deploy/v0.8.0/csi-azuredisk-driver.yaml
  deploy/v0.8.0/csi-azuredisk-node-windows.yaml
  deploy/v0.8.0/csi-azuredisk-node.yaml
  deploy/v0.8.0/csi-snapshot-controller.yaml
  deploy/v0.8.0/rbac-csi-azuredisk-controller.yaml
  deploy/v0.8.0/rbac-csi-azuredisk-node.yaml
  deploy/v0.8.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v0.8.0.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XXL

#476 ci: add options to skip installing / uninstalling azuredisk-csi-driver during e2e test
  Makefile
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#482 ci: add E2E_HELM_OPTIONS to Makefile
  Makefile
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#484 test: add more logs in e2e tests
  deploy/example/deployment.yaml
  deploy/example/sharedisk/deployment.yaml
  deploy/example/statefulset.yaml
  deploy/example/windows/deployment.yaml
  test/e2e/suite_test.go
  test/utils/azuredisk_log.sh
  test/utils/controller-manager-log.sh
Labels: approved, cncf-cla: yes, kind/test, size/M

#485 test: add disk detach e2e-test
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_detach_tester.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/L

#486 ci: remove --prefix when using kubectl to ensure backward compatibility
  test/utils/azuredisk_log.sh
  test/utils/controller-manager-log.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#489 test: add disk detach e2e-test in in-tree situation.
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_detach_tester.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/XS

#490 test: add unit-test in azuredisk_and csi-common.
  pkg/azuredisk/azuredisk_test.go
  pkg/csi-common/driver_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/S

#487 chore: refactor the snapshot code
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#488 test: add disk statefulset e2e-test
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_statefulset_e2e_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/L

#491 doc: add node-shutdown-recovery-doc
  docs/node-shutdown-recovery/README.md
  docs/node-shutdown-recovery/statefulset-azuredisk.yaml
  hack/verify-yamllint.sh
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#492 build: build binary outside of builder container to allow binary signing
  Makefile
  pkg/azurediskplugin/Dockerfile
  pkg/azurediskplugin/Windows.Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M

#499 feat: add dangling error support
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, kind/feature, size/S

#494 fix: Add imagePullSecrets in Helm chart for secret used to pull Docker images
  charts/README.md
  charts/latest/azuredisk-csi-driver/templates/_helpers.tpl
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#502 test: add containerd e2e test config
  deploy/example/windows/statefulset.yaml
  test/e2e/manifest/multi-az.json
  test/utils/azuredisk_log.sh
Labels: approved, cncf-cla: yes, kind/cleanup, size/XS

#503 doc: add volume expansion doc
  deploy/example/resize/volume-expansion.md
  docs/known-issues/node-shutdown-recovery/README.md
  docs/known-issues/node-shutdown-recovery/statefulset-azuredisk.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#504 test: add unit-test in csi-common.
  pkg/csi-common/driver_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/S

#506 feat: enable windows feature installation by default
  .github/PULL_REQUEST_TEMPLATE.md
  charts/README.md
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/example/windows/README.md
  deploy/install-driver.sh
Labels: approved, cncf-cla: yes, kind/feature, size/S

#507 test: add shared disk e2e test
  test/e2e/pre_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/test, size/M

#509 doc: fix metrics doc
  deploy/example/e2e_usage.md
  deploy/example/metrics/README.md
  deploy/example/metrics/csi-azuredisk-controller-svc.yaml
  test/e2e/pre_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#511 test: add metrics logs in e2e test
  Makefile
  charts/README.md
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows.yaml
  test/e2e/suite_test.go
  test/utils/azuredisk_log.sh
Labels: approved, cncf-cla: yes, kind/test, size/S

#512 test: make metrics test mandatory
  deploy/example/metrics/README.md
  test/utils/azuredisk_log.sh
Labels: approved, cncf-cla: yes, kind/test, size/S

#514 fix: azure disk resize error if source does not exist
  go.mod
  go.sum
  vendor/k8s.io/legacy-cloud-providers/azure/azure.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_backoff.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_blobDiskController.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_common.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_fakes.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_instances.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_standard.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_utils.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_vmss.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_vmss_cache.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_zones.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/azure_client_config.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/containerserviceclient/azure_containerserviceclient.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/deploymentclient/azure_deploymentclient.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/diskclient/azure_diskclient.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/diskclient/interface.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/diskclient/mockdiskclient/interface.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/interfaceclient/azure_interfaceclient.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/loadbalancerclient/azure_loadbalancerclient.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/publicipclient/azure_publicipclient.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/routeclient/azure_routeclient.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/routetableclient/azure_routetableclient.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/securitygroupclient/azure_securitygroupclient.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/snapshotclient/azure_snapshotclient.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/storageaccountclient/azure_storageaccountclient.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/subnetclient/azure_subnetclient.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/vmclient/azure_vmclient.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/vmsizeclient/azure_vmsizeclient.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/vmssclient/azure_vmssclient.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/vmssvmclient/azure_vmssvmclient.go
  vendor/k8s.io/utils/mount/mount_windows.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/bug, size/XL

#516 doc: add volume limits doc
  README.md
  deploy/example/volumelimits/README.md
Labels: approved, cncf-cla: yes, kind/documentation, size/M
