Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2020-04, with the labels that each got.

#344 chore: remove cluster driver registrar
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  hack/verify-helm-chart.sh
Labels: cncf-cla: yes, kind/cleanup, size/M

#345 test: deflake deployment test case
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
Labels: cncf-cla: yes, size/S

#334 test: run CSI driver e2e tests on Windows clusters
  Makefile
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node-windows.yaml
  test/e2e/pre_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#347 chore: expose azure.KubeClient
  vendor/k8s.io/legacy-cloud-providers/azure/azure.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_config.go
Labels: approved, cncf-cla: yes, kind/cleanup, size/XS

#348 fix: typo in Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#346 chore: remove volumeLifecycleModes in CSIDriver
  Makefile
  README.md
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v0.6.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  deploy/csi-azuredisk-driver.yaml
  deploy/v0.6.0/csi-azuredisk-driver.yaml
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/S

#349 fix: set cpu,memory limit to a higher value
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#351 doc: fix doc error
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  deploy/example/windows/README.md
  docs/install-csi-driver-master.md
  docs/install-csi-driver-v0.6.0.md
Labels: approved, cncf-cla: yes, kind/documentation, size/S

#352 feat: read cloud config from secret
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-secret.yaml
  charts/latest/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  deploy/install-driver.sh
  deploy/rbac-csi-azuredisk-controller.yaml
  deploy/rbac-csi-azuredisk-node.yaml
  deploy/uninstall-driver.sh
  docs/read-from-secret.md
  pkg/azuredisk/azure.go
  pkg/azuredisk/azure_test.go
  pkg/azuredisk/azuredisk.go
  pkg/azurediskplugin/main.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/documentation, kind/feature, kind/flake, lgtm, size/L

#353 chore: add linux.enabled parameter to helm chart
  Makefile
  charts/README.md
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#355 fix: remove the unnecessary check in NodeGetVolumeStats
  pkg/azuredisk/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#356 doc: cut v0.7.0 release
  README.md
  charts/v0.7.0/azuredisk-csi-driver/Chart.yaml
  charts/v0.7.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v0.7.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v0.7.0/azuredisk-csi-driver/templates/crd-csi-node-info.yaml
  charts/v0.7.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v0.7.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v0.7.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v0.7.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v0.7.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v0.7.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v0.7.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v0.7.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-secret.yaml
  charts/v0.7.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v0.7.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v0.7.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v0.7.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v0.7.0/azuredisk-csi-driver/values.yaml
  deploy/v0.7.0/crd-csi-node-info.yaml
  deploy/v0.7.0/crd-csi-snapshot.yaml
  deploy/v0.7.0/csi-azuredisk-controller.yaml
  deploy/v0.7.0/csi-azuredisk-driver.yaml
  deploy/v0.7.0/csi-azuredisk-node-windows.yaml
  deploy/v0.7.0/csi-azuredisk-node.yaml
  deploy/v0.7.0/csi-snapshot-controller.yaml
  deploy/v0.7.0/rbac-csi-azuredisk-controller.yaml
  deploy/v0.7.0/rbac-csi-azuredisk-node.yaml
  deploy/v0.7.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v0.7.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XXL

#359 feat: support tags in snapshot
  deploy/example/snapshot/storageclass-azuredisk-snapshot.yaml
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#362 chore: add secret rbac file
  deploy/install-driver.sh
  deploy/rbac-csi-azuredisk-secret.yaml
  deploy/uninstall-driver.sh
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/M

#364 Revert "chore: add secret rbac file"
  deploy/install-driver.sh
  deploy/rbac-csi-azuredisk-secret.yaml
  deploy/uninstall-driver.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#369 Do not install golangci-lint with 'go get'
  hack/verify-golint.sh
Labels: approved, cncf-cla: yes, kind/flake, lgtm, ok-to-test, size/XS

#367 test: add disk type tests
  hack/verify-yamllint.sh
  test/e2e/driver/azuredisk_driver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_invalid_mount_options.go
  test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
  test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go
  test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/test, size/L

#371 test: improve golint check script
  hack/verify-golint.sh
Labels: approved, cncf-cla: yes, kind/test, size/XS

#368 Remove deprecated csi-provisioner args
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v0.5.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v0.6.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v0.7.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/v0.5.0/csi-azuredisk-controller.yaml
  deploy/v0.6.0/csi-azuredisk-controller.yaml
  deploy/v0.7.0/csi-azuredisk-controller.yaml
Labels: cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#375 test: switch to use busybox
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/S

#374 chore: separate secret RBAC
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  deploy/rbac-csi-azuredisk-controller.yaml
  deploy/rbac-csi-azuredisk-node.yaml
Labels: approved, cncf-cla: yes, kind/flake, kind/test, lgtm, size/M

#376 test: run e2e tests on Ubuntu 18.04
  deploy/install-driver.sh
  deploy/uninstall-driver.sh
  test/e2e/manifest/single-az.json
Labels: approved, cncf-cla: yes, kind/test, size/XS

#379 Fix golangci-lint findings
  .golangci.yml
  hack/verify-golint.sh
  pkg/azuredisk/azure_common_linux.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/nodeserver.go
  test/utils/azure/azure_helpers.go
  test/utils/credentials/credentials.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/L

#377 chore: upgrade csi-attacher to v2.2.0
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/rbac-csi-azuredisk-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/S

#380 fix: disable IMDS in controller to support MSI
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-controller.yaml
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#383 test: enable topology for azure disk in-tree e2e tests
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/test, size/S

#384 Revert "test: enable topology for azure disk in-tree e2e tests"
  test/e2e/dynamic_provisioning_test.go
Labels: cncf-cla: yes
