Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2021-05, with the labels that each got.

#813 test: run external e2e test using 1.21 branch
  test/external-e2e/manifest/testdriver.yaml
  test/external-e2e/run.sh
Labels: approved, cncf-cla: yes, kind/test, size/XS

#820 fix: remove namespace in ClusterRole
  charts/latest/azuredisk-csi-driver-v1.2.0.tgz
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  deploy/rbac-csi-azuredisk-controller.yaml
  deploy/rbac-csi-azuredisk-node.yaml
  deploy/rbac-csi-snapshot-controller.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/S

#821 doc: cut v1.2.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.2.0/azuredisk-csi-driver-v1.2.0.tgz
  charts/v1.2.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.2.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.2.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.2.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.2.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.2.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.2.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.2.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.2.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.2.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.2.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.2.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.2.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.2.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.2.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.2.0/azuredisk-csi-driver/values.yaml
  deploy/v1.2.0/crd-csi-snapshot.yaml
  deploy/v1.2.0/csi-azuredisk-controller.yaml
  deploy/v1.2.0/csi-azuredisk-driver.yaml
  deploy/v1.2.0/csi-azuredisk-node-windows.yaml
  deploy/v1.2.0/csi-azuredisk-node.yaml
  deploy/v1.2.0/csi-snapshot-controller.yaml
  deploy/v1.2.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.2.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.2.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.2.0.md
Labels: approved, cncf-cla: yes, kind/feature, size/XXL

#822 chore: switch master branch to use v1.3.0
  Makefile
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.2.0.tgz
  charts/latest/azuredisk-csi-driver-v1.3.0.tgz
  charts/latest/azuredisk-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, size/M

#823 fix: remove VolumeSnapshotDataSource feature gate
  test/e2e/manifest/in-tree-vmss.json
  test/e2e/manifest/in-tree.json
  test/e2e/manifest/migration-windows.json
  test/e2e/manifest/migration.json
  test/e2e/manifest/multi-az.json
  test/e2e/manifest/single-az.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#824 Adjust PVC capacity to mirror in-tree behavior
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#825 add a new helm parameter for livenessProbe health port
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.3.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#828 add a new helm parameter for image pull secrets
  charts/latest/azuredisk-csi-driver-v1.3.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#792 test: add test cases to increase coverage for util
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/L

#831 fix: set correct DisableAvailabilitySetNodes in disk driver
  charts/latest/azuredisk-csi-driver-v1.3.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azurediskplugin/main.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/bug, size/M

#830 test: fix containerd Windows e2e test failure
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_statefulset_e2e_tester.go
Labels: approved, cncf-cla: yes, size/S

#833 fix: increase csi-attacher work-threads as 100 by default
  charts/latest/azuredisk-csi-driver-v1.3.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#836 chore: upgrade apiextensions.k8s.io/v1beta1 and storage.k8s.io/v1beta1
  README.md
  charts/latest/azuredisk-csi-driver-v1.3.0.tgz
  charts/latest/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  deploy/crd-csi-snapshot.yaml
  deploy/csi-azuredisk-driver.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, size/XXL

#835 fix: reduce crp throttling in attach disk scenario
  go.mod
  go.sum
  pkg/azuredisk/azure.go
  pkg/azuredisk/controllerserver.go
  test/e2e/testsuites/dynamically_provisioned_statefulset_e2e_tester.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/loadbalancerclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/loadbalancerclient/mockloadbalancerclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_config.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
Labels: approved, cncf-cla: yes, kind/bug, size/L

#840 feat: decrease provisioner worker threads
  charts/latest/azuredisk-csi-driver-v1.3.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#842 fix: GetDisk operation throttling issue
  go.mod
  go.sum
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/fake_azuredisk.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
Labels: approved, cncf-cla: yes, kind/bug, size/L

#844 fix: no sleep when GetDisk is throttled
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
Labels: approved, cncf-cla: yes, kind/bug, size/S

#845 test: add ZRS e2e test
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/test, size/S

#847 doc: adjust kubelet chart config
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.3.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/S

#848 fix: CentOS/RedHat cert issue in chart installation
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.3.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/S

#849 test: run test on install_driver.sh script
  hack/verify-examples.sh
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/test, size/M

#852 fix: RedHat/CentOS issue in helm installation
  charts/latest/azuredisk-csi-driver-v1.3.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  test/e2e/pre_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/bug, size/S

#854 fix: remove unnecessary lock in NodePublish
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/bug, size/M

#856 chore: upgrade sidecar container versions
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.3.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  test/e2e/testsuites/dynamically_provisioned_statefulset_e2e_tester.go
Labels: approved, cncf-cla: yes, kind/feature, size/M

#857 chore: update azure_dd_max_disk_count
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: approved, cncf-cla: yes, kind/cleanup, size/XS

#859 feat: add pv/pvc tags
  charts/latest/azuredisk-csi-driver-v1.3.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-controller.yaml
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_tag_tester.go
Labels: approved, cncf-cla: yes, kind/feature, size/M

#858 doc: cut v1.3.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.3.0/azuredisk-csi-driver-v1.3.0.tgz
  charts/v1.3.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.3.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.3.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.3.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.3.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.3.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.3.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.3.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.3.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.3.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.3.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.3.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.3.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.3.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.3.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.3.0/azuredisk-csi-driver/values.yaml
  deploy/v1.3.0/crd-csi-snapshot.yaml
  deploy/v1.3.0/csi-azuredisk-controller.yaml
  deploy/v1.3.0/csi-azuredisk-driver.yaml
  deploy/v1.3.0/csi-azuredisk-node-windows.yaml
  deploy/v1.3.0/csi-azuredisk-node.yaml
  deploy/v1.3.0/csi-snapshot-controller.yaml
  deploy/v1.3.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.3.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.3.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.3.0.md
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/documentation, size/XXL

#860 chore: switch master branch to use v1.4.0
  Makefile
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.3.0.tgz
  charts/latest/azuredisk-csi-driver-v1.4.0.tgz
  charts/latest/azuredisk-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/M

#863 test: wait for detach complete in e2e test
  test/e2e/testsuites/dynamically_provisioned_azuredisk_detach_tester.go
Labels: approved, cncf-cla: yes, kind/test, size/S

#843 feat: Update device settings to drive better performance
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.4.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-node.yaml
  docs/enhancements/feat-add-ability-to-tune-azuredisk-performance-parameters.md
  hack/calc_device_rand_latency.py
  hack/gen-disk-skus-map.go
  pkg/azuredisk/azure.go
  pkg/azuredisk/azure_skus_map.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/azuredisk_v1.go
  pkg/azuredisk/azuredisk_v1_test.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azuredisk/device_perf_optimization.go
  pkg/azuredisk/device_perf_optimization_helper.go
  pkg/azuredisk/device_perf_optimization_helper_test.go
  pkg/azuredisk/device_perf_optimization_linux.go
  pkg/azuredisk/device_perf_optimization_linux_test.go
  pkg/azuredisk/device_perf_optimization_test.go
  pkg/azuredisk/device_perf_optimization_unsupported.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azuredisk/fake_azuredisk_v2.go
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
  pkg/azuredisk/nodeserver_v2.go
  pkg/azuredisk/skus.go
  pkg/azuredisk/skus_test.go
  pkg/azurediskplugin/main.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
  test/performance/end-perfrun.sh
  test/performance/kubestone-benchmarks.yaml
  test/performance/kubestone-storageclass.yaml
  test/performance/start-perfrun.sh
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XXL

#871 feat: support fsGroupPolicy feature
  Makefile
  charts/latest/azuredisk-csi-driver-v1.4.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  test/external-e2e/manifest/testdriver.yaml
  test/external-e2e/run.sh
Labels: approved, cncf-cla: yes, kind/feature, size/S

#872 doc: add fsGroupPolicy doc
  README.md
  charts/README.md
  deploy/example/fsgroup/README.md
  deploy/example/resize/README.md
  deploy/example/resize/volume-expansion.md
Labels: approved, cncf-cla: yes, kind/documentation, size/L

#867 bug: fix perfProfile in the storageclass for performance test
  test/performance/kubestone-storageclass.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS
