Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2021-01, with the labels that each got.

#652 feat: switch to use csi-proxy beta API
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node-windows.yaml
  go.mod
  go.sum
  pkg/mounter/safe_mounter_windows.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/disk/v1alpha1/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/disk/v1alpha1/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/disk/v1beta2/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/disk/v1beta2/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v1beta1/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v1beta1/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/volume/v1beta2/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/volume/v1beta2/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/go.mod
  vendor/github.com/kubernetes-csi/csi-proxy/client/go.sum
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/disk/v1alpha1/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/disk/v1beta2/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/filesystem/v1beta1/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/volume/v1alpha1/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/volume/v1beta2/client_generated.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, size/XXL

#653 fix: cache data loss issue on Windows when unmount disk
  pkg/mounter/safe_mounter_windows.go
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/bug, size/S

#654 doc: cut v0.10.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v0.10.0/azuredisk-csi-driver-v0.10.0.tgz
  charts/v0.10.0/azuredisk-csi-driver/Chart.yaml
  charts/v0.10.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v0.10.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v0.10.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v0.10.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v0.10.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v0.10.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v0.10.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v0.10.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v0.10.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v0.10.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v0.10.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v0.10.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v0.10.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v0.10.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v0.10.0/azuredisk-csi-driver/values.yaml
  deploy/example/windows/README.md
  deploy/v0.10.0/crd-csi-snapshot.yaml
  deploy/v0.10.0/csi-azuredisk-controller.yaml
  deploy/v0.10.0/csi-azuredisk-driver.yaml
  deploy/v0.10.0/csi-azuredisk-node-windows.yaml
  deploy/v0.10.0/csi-azuredisk-node.yaml
  deploy/v0.10.0/csi-snapshot-controller.yaml
  deploy/v0.10.0/rbac-csi-azuredisk-controller.yaml
  deploy/v0.10.0/rbac-csi-azuredisk-node.yaml
  deploy/v0.10.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v0.10.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XXL

#655 test: enable GH actions on all branches
  .github/workflows/darwin.yaml
  .github/workflows/linux.yml
  .github/workflows/windows.yml
Labels: approved, cncf-cla: yes, kind/test, size/S

#659 doc: update charts doc
  charts/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#666 fix: ssl cert issue on non-debian agent node
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#661 feat: Add LogicalSectorSize support for UltraSSD
  go.mod
  go.sum
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/diskclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#667 chore: upgrade resizer to v1.1.0
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/rbac-csi-azuredisk-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/S

#668 feat: add kubeletPath support in Helm chart
  charts/README.md
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#669 fix: mount certs for Azure Stack
  Makefile
  README.md
  charts/README.md
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#672 fix: update v0.10.0 chart
  charts/v0.10.0/azuredisk-csi-driver-v0.10.0.tgz
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#670 test: Test driver config for external e2e k8s tests
  test/external-e2e/manifest/testdriver.yaml
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/XS

#677 fix: remove ssl config in v0.10.0
  charts/v0.10.0/azuredisk-csi-driver-v0.10.0.tgz
  charts/v0.10.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v0.10.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  deploy/v0.10.0/csi-azuredisk-controller.yaml
  deploy/v0.10.0/csi-azuredisk-node.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/S

#680 fix: Exclude os disks from the ListVolumes response
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#676 test: Use the resource group's managedBy property if none provided
  test/utils/azure/azure_helpers.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#681 feat: upgrade to snapshotter v3.0.3
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/feature, size/XS

#682 cleanup: remove unmanaged disk support
  pkg/azuredisk/azure_common.go
  pkg/azuredisk/azure_common_test.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/cleanup, size/L

#674 test: Add e2e test for snapshot restore
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/M

#657 fix: resize filesystem if cloned volume capacity is larger than the source volume
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/nodeserver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/L

#684 test: disable clone test in multi-zone cluster
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, size/XS

#665 test: Improve unit test coverage of nodeserver.go
  pkg/azuredisk/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/M

#686 chore: remove klog v1
  go.mod
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
  test/e2e/driver/azuredisk_driver.go
  test/e2e/testsuites/testsuites.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, size/XXL

#683 feat: Handle concurrency for node stage/unstage publish/unpublish
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azuredisk/nodeserver.go
  pkg/util/util.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#691 fix: passing CLOUD correctly in Makefile for Azure Stack
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#690 test: refactor example verification test
  Makefile
  deploy/example/statefulset-nonroot.yaml
  deploy/example/windows/deployment.yaml
  deploy/example/windows/statefulset.yaml
  hack/verify-examples.sh
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/test, size/L

#692 fix: reduce driver logs
  .github/workflows/windows.yml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  deploy/csi-snapshot-controller.yaml
  hack/verify-examples.sh
  pkg/csi-common/controllerserver-default.go
  pkg/csi-common/identityserver-default.go
  pkg/csi-common/nodeserver-default.go
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
Labels: approved, cncf-cla: yes, kind/bug, size/L

#694 chore: upgrade livenessprobe to v2.2.0
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  deploy/example/sharedisk/README.md
  docs/driver-parameters.md
  hack/verify-examples.sh
Labels: approved, cncf-cla: yes, kind/feature, size/S

#696 feat: add more controller metrics
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/feature, size/M

#693 fix: throw error when unsupported resources are requested on Azure Stack
  README.md
  deploy/example/snapshot/storageclass-azuredisk-snapshot.yaml
  deploy/example/storageclass-azuredisk-csi-azurestack.yaml
  docs/limitations.md
  hack/verify-examples.sh
  pkg/azuredisk/azure.go
  pkg/azuredisk/azure_common.go
  pkg/azuredisk/azure_common_test.go
  pkg/azuredisk/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/specs.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/L

#695 feat: add controller lock
  deploy/example/windows/README.md
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/feature, size/M

#660 test: add dangling error e2e test
  test/e2e/pre_provisioning_test.go
  test/e2e/testsuites/pre_provisioned_dangling_attach_volume_tester.go
  test/e2e/testsuites/testsuites.go
  test/sanity/sanity_test.go
  test/utils/credentials/credentials.go
  test/utils/credentials/credentials_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#700 fix: Use new windows server image to avoid driver daemonset failure
  test/e2e/manifest/migration-windows.json
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#699 feat: upgrade csi-provisioner to v1.6.1
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/identityserver.go
  pkg/azuredisk/nodeserver.go
Labels: approved, cncf-cla: yes, kind/feature, size/S

#701 feat: remove securityContext on Windows deployment
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node-windows.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#698 chore: upgrade azure lib
  go.mod
  go.sum
  pkg/azuredisk/azure_dd_max_disk_count.go
  vendor/k8s.io/cloud-provider/cloud.go
  vendor/k8s.io/cloud-provider/go.mod
  vendor/k8s.io/cloud-provider/go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/azure_armclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/diskclient/azure_diskclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/interfaceclient/azure_interfaceclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/interfaceclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/loadbalancerclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/publicipclient/azure_publicipclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/publicipclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routeclient/azure_routeclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routeclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routetableclient/azure_routetableclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routetableclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/securitygroupclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/snapshotclient/azure_snapshotclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/snapshotclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/storageaccountclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/subnetclient/azure_subnetclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/subnetclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmclient/azure_vmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmsizeclient/azure_vmsizeclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmsizeclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssclient/azure_vmssclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_backoff.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_instances.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/feature, size/XL

#704 fix: add latest helm chart
  .gitignore
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.0.0.tgz
  charts/latest/azuredisk-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#705 test: add chart tgz file verification
  docs/known-issues/sizegrow.md
  hack/verify-helm-chart.sh
Labels: approved, cncf-cla: yes, kind/test, size/S

#706 test: add chart tgz files verification
  hack/verify-helm-chart.sh
Labels: approved, cncf-cla: yes, kind/test, size/S
