Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2021-09, with the labels that each got.

#996 chore: Add edreed to reviewers
  OWNERS
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/cleanup

#997 fix: remove ClusterFirstWithHostNet dnsPolicy
  charts/latest/azuredisk-csi-driver-v1.7.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/bug, do-not-merge/hold, size/XS, approved, cncf-cla: yes

#995 test: Improve unit test coverage of nodeserver.go
  pkg/azuredisk/azure_common_darwin.go
  pkg/azuredisk/azure_common_linux.go
  pkg/azuredisk/azure_common_test.go
  pkg/azuredisk/azure_common_windows.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azuredisk/fake_azuredisk_v2.go
  pkg/azuredisk/fake_mounter.go
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
  pkg/azuredisk/nodeserver_v2.go
  pkg/azureutils/fake_hostutil.go
  pkg/azureutils/fake_iohandler.go
  pkg/azureutils/osiohandler.go
  pkg/mounter/fake_safe_mounter.go
  pkg/mounter/fake_safe_mounter_test.go
  pkg/optimization/mockoptimization/doc.go
  pkg/optimization/mockoptimization/interface.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: approved, lgtm, cncf-cla: yes, size/XXL, kind/test

#998 feat: switch to sync detach disk
  go.mod
  go.sum
  hack/verify-examples.sh
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/fileclient/azure_fileclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_blobDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storage.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets.go
Labels: kind/feature, approved, cncf-cla: yes, size/L

#1000 fix: panic when vm size not in SkuMap table
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes

#999 feat: allow storage class setting of useragent
  docs/driver-parameters.md
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
Labels: kind/feature, size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1001 test: specify userAgentSuffix in e2e test
  Makefile
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1002 chore: upgrade sidcar container versions
  charts/latest/azuredisk-csi-driver-v1.7.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/feature, size/S, approved, lgtm, cncf-cla: yes

#1005 fix: enable avset setting by default
  pkg/azurediskplugin/main.go
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes

#1006 test: upgrade csi-provisioner to v3.0.0 in external e2e test
  test/external-e2e/run.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#990 feat: expose metadata for static PV attachment
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/L

#1004 doc: fix shared disk doc
  deploy/example/sharedisk/README.md
  deploy/example/sharedisk/deployment.yaml
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#1008 feat: support disable-avset-nodes in install-driver.sh script
  deploy/csi-azuredisk-controller.yaml
  deploy/install-driver.sh
  pkg/azurediskplugin/main.go
Labels: kind/feature, size/S, approved, lgtm, cncf-cla: yes

#1010 refactor: Move remaining device perf helpers to optimization package
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/device_perf_optimization_helper.go
  pkg/azuredisk/device_perf_optimization_helper_test.go
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_v2.go
  pkg/optimization/device_perf_helper.go
  pkg/optimization/device_perf_helper_test.go
Labels: approved, lgtm, cncf-cla: yes, size/L, kind/cleanup, ok-to-test

#1011 doc: cut v1.7.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.7.0/azuredisk-csi-driver-v1.7.0.tgz
  charts/v1.7.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.7.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.7.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.7.0/azuredisk-csi-driver/templates/crd-csi-snapshot-ga.yaml
  charts/v1.7.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.7.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.7.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.7.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.7.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.7.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.7.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.7.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.7.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.7.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.7.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.7.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.7.0/azuredisk-csi-driver/values.yaml
  deploy/v1.7.0/crd-csi-snapshot-ga.yaml
  deploy/v1.7.0/crd-csi-snapshot.yaml
  deploy/v1.7.0/csi-azuredisk-controller.yaml
  deploy/v1.7.0/csi-azuredisk-driver.yaml
  deploy/v1.7.0/csi-azuredisk-node-windows.yaml
  deploy/v1.7.0/csi-azuredisk-node.yaml
  deploy/v1.7.0/csi-snapshot-controller.yaml
  deploy/v1.7.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.7.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.7.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.7.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1012 chore: switch master branch to use v1.8.0
  Makefile
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.7.0.tgz
  charts/latest/azuredisk-csi-driver-v1.8.0.tgz
  charts/latest/azuredisk-csi-driver/Chart.yaml
Labels: kind/documentation, size/M, approved, cncf-cla: yes

#1015 test: remove deprecated test configs
  test/e2e/manifest/in-tree-vmss.json
  test/e2e/manifest/in-tree.json
  test/e2e/manifest/migration-windows.json
  test/e2e/manifest/migration.json
  test/e2e/manifest/multi-az.json
  test/e2e/manifest/single-az.json
  test/external-e2e/manifest/single-az.json
Labels: size/S, approved, cncf-cla: yes, kind/test

#1017 test: run v1.22 external test
  test/external-e2e/run.sh
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1018 feat: reduce vmss cache refresh
  go.mod
  go.sum
  vendor/github.com/Azure/go-autorest/autorest/adal/sender.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/go.mod
  vendor/github.com/onsi/gomega/go.sum
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/matchers/have_http_body_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_http_header_with_value_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_http_status_matcher.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
Labels: kind/feature, approved, cncf-cla: yes, size/L

#1019 feat: ReadWriteOncePod support
  go.mod
  go.sum
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azureutils/azure_disk_utils.go
  test/sanity/run-test.sh
  test/sanity/run-tests-all-clouds.sh
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/modules.txt
Labels: kind/feature, size/XL, approved, cncf-cla: yes

#1020 test: pre-provisioning-test should clean up created volumes unless told not to
  test/e2e/pre_provisioning_test.go
Labels: kind/bug, size/S, approved, lgtm, cncf-cla: yes, ok-to-test, kind/test

#1023 chore: Abstract release and beta CSI Proxy behind interface
  pkg/azuredisk/azure_common_windows.go
  pkg/mounter/safe_mounter_v1beta_windows.go
  pkg/mounter/safe_mounter_windows.go
Labels: approved, lgtm, cncf-cla: yes, size/L, kind/cleanup

#1022 fix: add AccessMode_SINGLE_NODE_READER_ONLY cap
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#1024 feat: upgrade snapshot CRD to v4.2.1
  charts/latest/azuredisk-csi-driver-v1.8.0.tgz
  charts/latest/azuredisk-csi-driver/templates/crd-csi-snapshot-ga.yaml
  deploy/crd-csi-snapshot-ga.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/feature, size/M, approved, lgtm, cncf-cla: yes

#1027 feat: add ReadWriteOncePod cap
  Makefile
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
  test/sanity/run-test.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1028 fix: upgrade to debian 11.0 to fix vulnerability
  .github/workflows/trivy.yaml
  Makefile
  pkg/azurediskplugin/Dockerfile
  pkg/azurediskplugin/dev.Dockerfile
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes

#1030 Added WS2022 to Makefile build process
  Makefile
  docs/csi-dev.md
Labels: kind/feature, kind/documentation, size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#1029 feat: add affinity and node affinity as values
  charts/latest/azuredisk-csi-driver-v1.8.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
Labels: kind/feature, size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1033 fix: driver pod crash issue on Windows
  charts/latest/azuredisk-csi-driver-v1.8.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes

#1032 feat: add 20H2 Windows image support
  Makefile
  docs/csi-dev.md
Labels: kind/feature, size/XS, approved, lgtm, cncf-cla: yes

#1034 feat: switch back to csi-proxy v1beta interface on Windows
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azuredisk/fake_azuredisk_v2.go
  pkg/azurediskplugin/main.go
  pkg/mounter/fake_safe_mounter.go
  pkg/mounter/safe_mounter_unix.go
  pkg/mounter/safe_mounter_unix_test.go
  pkg/mounter/safe_mounter_windows.go
Labels: kind/feature, size/M, approved, lgtm, cncf-cla: yes
