Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2021-12, with the labels that each got.

#1103 fix: update v1.9.0 chart file
  charts/index.yaml
  charts/v1.9.0/azuredisk-csi-driver-v1.9.0.tgz
  charts/v1.9.0/azuredisk-csi-driver/Chart.yaml
  hack/verify-helm-chart.sh
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes

#1105 fix: detach disk should return error when throttled
  go.mod
  go.sum
  vendor/github.com/Azure/go-autorest/autorest/adal/go.mod
  vendor/github.com/Azure/go-autorest/autorest/adal/go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/azure_armclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_backoff.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1106 cleanup: remove arm64 build workaround
  Makefile
Labels: size/XS, approved, cncf-cla: yes, kind/cleanup

#1100 chore: Revert "flake: Disable failing test"
  test/e2e/pre_provisioning_test.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/cleanup

#1108 feat: remove 1903 1909 2004 Windows image which is end of life
  Makefile
Labels: kind/feature, size/XS, approved, lgtm, cncf-cla: yes

#1111 Revert "cleanup: remove arm64 build workaround"
  Makefile
Labels: size/XS, approved, cncf-cla: yes

#1112 test: add apiVersion deprecation test
  .github/workflows/pluto.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes, kind/test

#1116 test: add more apiVersion check test
  .github/workflows/pluto.yaml
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1117 fix: CVE-2021-43618 in Ubuntu image
  .github/workflows/pluto.yaml
  pkg/azurediskplugin/Dockerfile
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#1119 fix: CVE-2021-38561 with golang lib
  go.mod
  go.sum
  vendor/golang.org/x/text/internal/language/language.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/language/parse.go
  vendor/modules.txt
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1121 cleanup: remove cpu limits
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.10.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  deploy/csi-snapshot-controller.yaml
Labels: size/M, approved, cncf-cla: yes, kind/cleanup

#1124 doc: cut v1.10.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.10.0.tgz
  charts/v1.10.0/azuredisk-csi-driver-v1.10.0.tgz
  charts/v1.10.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.10.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.10.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.10.0/azuredisk-csi-driver/templates/crd-csi-snapshot-ga.yaml
  charts/v1.10.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.10.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.10.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.10.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.10.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.10.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.10.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.10.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.10.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.10.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.10.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.10.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.10.0/azuredisk-csi-driver/values.yaml
  deploy/v1.10.0/crd-csi-snapshot-ga.yaml
  deploy/v1.10.0/crd-csi-snapshot.yaml
  deploy/v1.10.0/csi-azuredisk-controller.yaml
  deploy/v1.10.0/csi-azuredisk-driver.yaml
  deploy/v1.10.0/csi-azuredisk-node-windows.yaml
  deploy/v1.10.0/csi-azuredisk-node.yaml
  deploy/v1.10.0/csi-snapshot-controller.yaml
  deploy/v1.10.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.10.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.10.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.10.0.md
Labels: kind/documentation, do-not-merge/hold, approved, cncf-cla: yes, size/XXL

#1125 chore: switch master branch to use v1.11.0
  Makefile
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.10.0.tgz
  charts/latest/azuredisk-csi-driver-v1.11.0.tgz
  charts/latest/azuredisk-csi-driver/Chart.yaml
Labels: kind/documentation, size/M, approved, cncf-cla: yes
