Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2021-02, with the labels that each got.

#713 test: add expand volume test to integration test
  test/integration/run-test.sh
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/XS

#715 fix: volume expansion failure on node
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#720 test: add verify-helm-chart-files.sh script
  charts/index.yaml
  hack/verify-all.sh
  hack/verify-helm-chart-files.sh
  hack/verify-helm-chart.sh
Labels: approved, cncf-cla: yes, kind/test, size/L

#721 doc: cut v1.0.0 GA release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.0.0/azuredisk-csi-driver-v1.0.0.tgz
  charts/v1.0.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.0.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.0.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.0.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.0.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.0.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.0.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.0.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.0.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.0.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.0.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.0.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.0.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.0.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.0.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.0.0/azuredisk-csi-driver/values.yaml
  deploy/v1.0.0/crd-csi-snapshot.yaml
  deploy/v1.0.0/csi-azuredisk-controller.yaml
  deploy/v1.0.0/csi-azuredisk-driver.yaml
  deploy/v1.0.0/csi-azuredisk-node-windows.yaml
  deploy/v1.0.0/csi-azuredisk-node.yaml
  deploy/v1.0.0/csi-snapshot-controller.yaml
  deploy/v1.0.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.0.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.0.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.0.0.md
  pkg/csi-common/utils.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/documentation, size/XXL

#726 chore: switch master branch to use v1.1.0
  Makefile
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.0.0.tgz
  charts/latest/azuredisk-csi-driver-v1.1.0.tgz
  charts/latest/azuredisk-csi-driver/Chart.yaml
  charts/latest/azuredisk-csi-driver/templates/NOTES.txt
  charts/latest/azuredisk-csi-driver/templates/_helpers.tpl
  charts/latest/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/S

#728 test: add logLevel and more logs in e2e tests
  Makefile
  charts/latest/azuredisk-csi-driver-v1.1.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/test, size/S

#730 chore: set loglevel on windows node
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.1.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
Labels: approved, cncf-cla: yes, kind/test, size/XS

#723 test: write unit test for getDevicePathWithMountPath function
  pkg/azuredisk/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/M

#731 fix: add taints to Windows daemonset
  Makefile
  charts/latest/azuredisk-csi-driver-v1.1.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node-windows.yaml
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
Labels: approved, cncf-cla: yes, kind/bug, size/S

#735 fix: broken chart index
  charts/index.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/S

#738 test: fix windows ut failure
  pkg/azuredisk/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, size/M

#737 feat: support disable AzureStack
  charts/latest/azuredisk-csi-driver-v1.1.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-controller.yaml
  hack/verify-helm-chart-files.sh
  pkg/azuredisk/azure.go
  pkg/azuredisk/azure_common.go
  pkg/azuredisk/azure_common_test.go
  pkg/azuredisk/azure_test.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/controllerserver.go
  pkg/azurediskplugin/main.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/feature, size/L

#742 doc: cut v1.1.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.1.0/azuredisk-csi-driver-v1.1.0.tgz
  charts/v1.1.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.1.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.1.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.1.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.1.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.1.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.1.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.1.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.1.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.1.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.1.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.1.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.1.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.1.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.1.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.1.0/azuredisk-csi-driver/values.yaml
  deploy/v1.1.0/crd-csi-snapshot.yaml
  deploy/v1.1.0/csi-azuredisk-controller.yaml
  deploy/v1.1.0/csi-azuredisk-driver.yaml
  deploy/v1.1.0/csi-azuredisk-node-windows.yaml
  deploy/v1.1.0/csi-azuredisk-node.yaml
  deploy/v1.1.0/csi-snapshot-controller.yaml
  deploy/v1.1.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.1.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.1.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.1.0.md
  hack/verify-helm-chart-files.sh
Labels: approved, cncf-cla: yes, kind/documentation, size/XXL

#745 chore: switch master branch to use v1.2.0
  Makefile
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.1.0.tgz
  charts/latest/azuredisk-csi-driver-v1.2.0.tgz
  charts/latest/azuredisk-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, size/S

#744 fix: dynamically generate key pair for vm creation in tests
  test/utils/azure/azure_helpers.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#739 Updates to resize e2e test
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#746 feat: Add support for NodeExpandVolume on Windows
  pkg/azuredisk/azure_common_unix.go
  pkg/azuredisk/azure_common_windows.go
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
  pkg/mounter/safe_mounter_windows.go
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#747 test: add more golint checks
  .github/workflows/static.yaml
Labels: approved, cncf-cla: yes, kind/test, size/XS
