Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2021-11, with the labels that each got.

#1062 fix: missing static PV data in VolumeAttachments
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
Labels: kind/bug, size/S, approved, lgtm, cncf-cla: yes

#1063 chore: increase sidecar contianer cpu limit in controller
  charts/latest/azuredisk-csi-driver-v1.9.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-controller.yaml
Labels: kind/feature, size/S, approved, lgtm, cncf-cla: yes

#1064 feat: support disk online resize
  go.mod
  go.sum
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azurediskplugin/main.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1065 fix: increase registrar container cpu limit
  charts/latest/azuredisk-csi-driver-v1.9.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#1066 fix: snapshot throttling issue
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azureutils/azure_disk_utils.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1060 chore: Refactoring cloud provider initialization to merge v1 and v2 driver implementations.
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
Labels: approved, lgtm, cncf-cla: yes, size/L, ok-to-test

#1068 fix: increase registrar probe timeout value on Windows
  charts/latest/azuredisk-csi-driver-v1.9.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node-windows.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#1072 chore: update max datadisk list
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/feature, approved, cncf-cla: yes, size/L

#1071 chore: set default replica num of snapshot controller as 2
  charts/latest/azuredisk-csi-driver-v1.9.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#1078 feat: add btrfs file system support
  docs/driver-parameters.md
  pkg/azurediskplugin/Dockerfile
  test/e2e/dynamic_provisioning_test.go
  test/integration/run-test.sh
Labels: kind/feature, size/S, approved, lgtm, cncf-cla: yes

#1079 test: only run btrfs in CSI driver e2e tests
  test/e2e/dynamic_provisioning_test.go
Labels: size/S, kind/failing-test, approved, lgtm, cncf-cla: yes

#1077 feat: add allowEmptyCloudConfig config in chart
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.9.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/controllerserver.go
  pkg/azurediskplugin/main.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
  test/integration/integration_test.go
  test/integration/run-test.sh
Labels: kind/feature, approved, cncf-cla: yes, size/L

#1080 feat: upgrade sidecar container version to support WS2022
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.9.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/feature, size/M, approved, lgtm, cncf-cla: yes

#1081 fix: upgrade azure lib to fix panic issue on node driver
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/privatednsclient/azure_privatednsclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/privateendpointclient/azure_privateendpointclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_instances.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_routes.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_utils.go
Labels: kind/bug, approved, lgtm, cncf-cla: yes, size/L

#1082 feat: support resources config in chart
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.9.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
Labels: kind/feature, do-not-merge/hold, approved, cncf-cla: yes, size/L

#1083 chore: MCR pipeline support for V2 driver build
  Makefile
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/cleanup

#1089 chore: Update Driver v2 design doc
  docs/design-v2.md
  docs/images/csi_driver_v2.png
  docs/images/mandalay_arch.png
Labels: kind/documentation, size/S, lgtm, cncf-cla: yes

#1091 test: fix Windows containerd test failures
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_statefulset_e2e_tester.go
Labels: kind/flake, size/S, kind/failing-test, approved, cncf-cla: yes

#1092 feat: increase sidecar container cpu limits
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.9.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1094 doc: cut v1.9.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.9.0.tgz
  charts/v1.9.0/azuredisk-csi-driver-v1.9.0.tgz
  charts/v1.9.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.9.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.9.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.9.0/azuredisk-csi-driver/templates/crd-csi-snapshot-ga.yaml
  charts/v1.9.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.9.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.9.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.9.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.9.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.9.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.9.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.9.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.9.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.9.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.9.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.9.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.9.0/azuredisk-csi-driver/values.yaml
  deploy/v1.9.0/crd-csi-snapshot-ga.yaml
  deploy/v1.9.0/crd-csi-snapshot.yaml
  deploy/v1.9.0/csi-azuredisk-controller.yaml
  deploy/v1.9.0/csi-azuredisk-driver.yaml
  deploy/v1.9.0/csi-azuredisk-node-windows.yaml
  deploy/v1.9.0/csi-azuredisk-node.yaml
  deploy/v1.9.0/csi-snapshot-controller.yaml
  deploy/v1.9.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.9.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.9.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.9.0.md
Labels: kind/feature, do-not-merge/hold, approved, cncf-cla: yes, size/XXL

#1095 chore: switch master branch to use v1.10.0
  Makefile
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.10.0.tgz
  charts/latest/azuredisk-csi-driver-v1.9.0.tgz
  charts/latest/azuredisk-csi-driver/Chart.yaml
Labels: kind/documentation, size/M, approved, cncf-cla: yes

#1096 feat: add location parameter in snapshot class
  docs/driver-parameters.md
  pkg/azuredisk/controllerserver.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1098 chore: Add edreed to approvers
  OWNERS
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/cleanup
