Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2021-08, with the labels that each got.

#959 Update README.md
  charts/README.md
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#960 fix: disable networkAccessPolicy on Azure Stack Cloud
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
Labels: kind/bug, size/S, approved, lgtm, cncf-cla: yes, ok-to-test

#964 fix: disable networkAccessPolicy on Azure Stack Cloud
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#966 doc: add v1.5.1 artifacts in master branch
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.5.1/azuredisk-csi-driver-v1.5.1.tgz
  charts/v1.5.1/azuredisk-csi-driver/Chart.yaml
  charts/v1.5.1/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.5.1/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.5.1/azuredisk-csi-driver/templates/crd-csi-snapshot-ga.yaml
  charts/v1.5.1/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.5.1/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.5.1/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.5.1/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.5.1/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.5.1/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.5.1/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.5.1/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.5.1/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.5.1/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.5.1/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.5.1/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.5.1/azuredisk-csi-driver/values.yaml
  deploy/v1.5.1/crd-csi-snapshot-ga.yaml
  deploy/v1.5.1/crd-csi-snapshot.yaml
  deploy/v1.5.1/csi-azuredisk-controller.yaml
  deploy/v1.5.1/csi-azuredisk-driver.yaml
  deploy/v1.5.1/csi-azuredisk-node-windows.yaml
  deploy/v1.5.1/csi-azuredisk-node.yaml
  deploy/v1.5.1/csi-snapshot-controller.yaml
  deploy/v1.5.1/rbac-csi-azuredisk-controller.yaml
  deploy/v1.5.1/rbac-csi-azuredisk-node.yaml
  deploy/v1.5.1/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.5.1.md
Labels: kind/documentation, approved, lgtm, cncf-cla: yes, size/XXL

#968 feat: support maxUnavailable config in helm chart
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.6.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#969 feat: change default userAgent
  pkg/azuredisk/azure.go
  pkg/azuredisk/azure_test.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/version.go
Labels: kind/feature, size/S, approved, lgtm, cncf-cla: yes

#970 fix: driver register issue on Windows node
  charts/latest/azuredisk-csi-driver-v1.6.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes

#972 fix: remove kubelet-registration-probe on Linux
  charts/latest/azuredisk-csi-driver-v1.6.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#973 fix: set default userAgent issue
  go.mod
  go.sum
  pkg/azuredisk/azure.go
  pkg/azuredisk/azure_test.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
  vendor/github.com/Azure/azure-sdk-for-go/NOTICE
  vendor/github.com/Azure/azure-sdk-for-go/NOTICE.txt
  vendor/github.com/Azure/azure-sdk-for-go/storage/README.md
  vendor/github.com/Azure/azure-sdk-for-go/version/version.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/env.go
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/internal/assertion.go
  vendor/github.com/onsi/gomega/internal/async_assertion.go
  vendor/github.com/onsi/gomega/internal/defaults/env.go
  vendor/github.com/onsi/gomega/internal/duration_bundle.go
  vendor/github.com/onsi/gomega/internal/gomega.go
  vendor/github.com/onsi/gomega/internal/oraclematcher/oracle_matcher.go
  vendor/github.com/onsi/gomega/internal/testingtsupport/testing_t_support.go
  vendor/github.com/onsi/gomega/matchers/and.go
  vendor/github.com/onsi/gomega/matchers/not.go
  vendor/github.com/onsi/gomega/matchers/or.go
  vendor/github.com/onsi/gomega/matchers/with_transform.go
  vendor/github.com/onsi/gomega/types/types.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_config.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_instances.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
Labels: kind/bug, approved, cncf-cla: yes, size/XXL

#975 feat: support custom userAgent in driver setting
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.6.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/version.go
  pkg/azuredisk/version_test.go
  pkg/azurediskplugin/main.go
Labels: kind/feature, size/M, approved, cncf-cla: yes

#979 fix: disable disk related rate limit
  pkg/azuredisk/azure.go
  pkg/azuredisk/azure_test.go
  pkg/azuredisk/version.go
  pkg/azuredisk/version_test.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#978 feat: upgrade to snapshot-controller v4.2.0
  charts/latest/azuredisk-csi-driver-v1.6.0.tgz
  charts/latest/azuredisk-csi-driver/Chart.yaml
  charts/latest/azuredisk-csi-driver/templates/NOTES.txt
  charts/latest/azuredisk-csi-driver/templates/_helpers.tpl
  charts/latest/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#980 fix: ignore GetDisk throttling in DeleteDisk
  go.mod
  go.sum
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/retry/azure_error.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#981 chore: update max data disk count table
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#982 doc: cut v1.6.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.6.0/azuredisk-csi-driver-v1.6.0.tgz
  charts/v1.6.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.6.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.6.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.6.0/azuredisk-csi-driver/templates/crd-csi-snapshot-ga.yaml
  charts/v1.6.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.6.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.6.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.6.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.6.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.6.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.6.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.6.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.6.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.6.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.6.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.6.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.6.0/azuredisk-csi-driver/values.yaml
  deploy/v1.6.0/crd-csi-snapshot-ga.yaml
  deploy/v1.6.0/crd-csi-snapshot.yaml
  deploy/v1.6.0/csi-azuredisk-controller.yaml
  deploy/v1.6.0/csi-azuredisk-driver.yaml
  deploy/v1.6.0/csi-azuredisk-node-windows.yaml
  deploy/v1.6.0/csi-azuredisk-node.yaml
  deploy/v1.6.0/csi-snapshot-controller.yaml
  deploy/v1.6.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.6.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.6.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.6.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#983 chore: switch master branch to use v1.7.0
  Makefile
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.6.0.tgz
  charts/latest/azuredisk-csi-driver-v1.7.0.tgz
  charts/latest/azuredisk-csi-driver/Chart.yaml
Labels: kind/documentation, size/M, approved, cncf-cla: yes

#985 feat: add CSIDriver annotations
  charts/latest/azuredisk-csi-driver-v1.7.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  deploy/csi-azuredisk-driver.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#987 test: improve UT coverage for controllerserver.go
  pkg/azuredisk/controllerserver_test.go
Labels: approved, lgtm, cncf-cla: yes, size/L, ok-to-test, kind/test

#986 feat: add base repo in chart
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.7.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  hack/verify-helm-chart.sh
Labels: kind/feature, approved, cncf-cla: yes, size/L

#991 chore: upgrade to snapshot v4.2.1
  charts/latest/azuredisk-csi-driver-v1.7.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#992 chore: upgrade azure lib
  go.mod
  go.sum
  hack/verify-examples.sh
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
Labels: kind/bug, size/M, approved, cncf-cla: yes
