Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2021-04, with the labels that each got.

#776 test: disable statefulset test for Windows in-tree driver
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/XS

#778 fix: disable invalid storage class parameters
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azuredisk/nodeserver.go
Labels: approved, cncf-cla: yes, kind/feature, size/M

#777 fix: support create snapshot in parallel
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
Labels: approved, cncf-cla: yes, kind/bug, size/S

#774 test: use `WaitForFirstConsumer` for in-tree storage driver
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/S

#781 test: add test cases for volume lock acquisition
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azuredisk/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/L

#783 feat: add new controlplane taints for v1.20
  charts/latest/azuredisk-csi-driver-v1.2.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/XS

#784 feat: upgrade node driver registrar to v2.1.0
  charts/latest/azuredisk-csi-driver-v1.2.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/XS

#786 test: Schedule pod to same zone as source disk in multi-az clone tests
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/failing-test, kind/flake, kind/test, lgtm, size/M

#785 feat: support topology.kubernetes.io/zone key
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_v2.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/feature, size/M

#789 test: add inline volume test
  test/e2e/pre_provisioning_test.go
  test/e2e/testsuites/pre_provisioned_inline_volume_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/test, size/L

#794 test: disable inline volume test for in-tree driver
  test/e2e/pre_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/test, size/XS

#790 fix: delete the sockets when stopping the pod on Windows
  charts/latest/azuredisk-csi-driver-v1.2.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node-windows.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#791 feat: support ZRS disk
  .github/workflows/windows.yml
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, kind/feature, size/M

#798 test: skip inline test for in-tree Windows
  test/e2e/pre_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/test, size/XS

#797 fix: disk attach issue when vm in failed status
  go.mod
  go.sum
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_mock_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets.go
Labels: approved, cncf-cla: yes, kind/bug, size/L

#801 feat: support ZRS disk on non-zone nodes
  deploy/example/topology/README.md
  docs/driver-parameters.md
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, size/S

#802 feat: support allowedTopologies in storage class for ZRS disk
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, kind/feature, size/S

#804 fix: potential race condition in detach disk
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_backoff.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_mock_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss_cache.go
Labels: approved, cncf-cla: yes, kind/feature, size/L

#806 feat: add ARM64 support
  Makefile
  pkg/azurediskplugin/Dockerfile
Labels: approved, cncf-cla: yes, kind/feature, size/S

#807 test: switch to use MCR windows images
  deploy/example/windows/deployment.yaml
  deploy/example/windows/statefulset.yaml
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/test, size/S

#808 fix: random arm64 build failure
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#805 Setup k8s external e2e tests
  Makefile
  test/external-e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#809 test: print out driver logs
  test/external-e2e/manifest/testdriver.yaml
  test/external-e2e/run.sh
Labels: approved, cncf-cla: yes, kind/test, size/S

#810 fail external-e2e prow job on test failure
  test/external-e2e/manifest/testdriver.yaml
  test/external-e2e/run.sh
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/S

#812 chore: Fix arm64 container build
  Makefile
  docs/csi-dev.md
  pkg/azurediskplugin/Dockerfile
  pkg/azurediskplugin/Windows.Dockerfile
  pkg/azurediskplugin/dev.Dockerfile
  test/integration/run-test.sh
  test/sanity/run-test.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#817 feat: support edge zone managed disk
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/deploymentclient/azure_deploymentclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/diskclient/azure_diskclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/interfaceclient/azure_interfaceclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/publicipclient/azure_publicipclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routeclient/azure_routeclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routetableclient/azure_routetableclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/snapshotclient/azure_snapshotclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/subnetclient/azure_subnetclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmasclient/azure_vmasclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmclient/azure_vmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmsizeclient/azure_vmsizeclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssclient/azure_vmssclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_routes.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/reconcile_schema.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/remove.go
Labels: approved, cncf-cla: yes, kind/feature, size/L
