Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2021-03, with the labels that each got.

#751 feat: remove support-azure-stack flag
  charts/latest/azuredisk-csi-driver-v1.2.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-controller.yaml
  pkg/azuredisk/azure.go
  pkg/azuredisk/azure_common.go
  pkg/azuredisk/azure_common_test.go
  pkg/azuredisk/azure_test.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v1.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azurediskplugin/main.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#750 fix: increate csi-resizer memory limit
  charts/latest/azuredisk-csi-driver-v1.2.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-controller.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#752 chore: switch master branch to use v1.1.1
  Makefile
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.1.1.tgz
  charts/latest/azuredisk-csi-driver-v1.2.0.tgz
  charts/latest/azuredisk-csi-driver/Chart.yaml
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, size/M

#753 doc: cut v1.1.1 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.1.1/azuredisk-csi-driver-v1.1.1.tgz
  charts/v1.1.1/azuredisk-csi-driver/Chart.yaml
  charts/v1.1.1/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.1.1/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.1.1/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.1.1/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.1.1/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.1.1/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.1.1/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.1.1/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.1.1/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.1.1/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.1.1/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.1.1/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.1.1/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.1.1/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.1.1/azuredisk-csi-driver/values.yaml
  deploy/v1.1.1/crd-csi-snapshot.yaml
  deploy/v1.1.1/csi-azuredisk-controller.yaml
  deploy/v1.1.1/csi-azuredisk-driver.yaml
  deploy/v1.1.1/csi-azuredisk-node-windows.yaml
  deploy/v1.1.1/csi-azuredisk-node.yaml
  deploy/v1.1.1/csi-snapshot-controller.yaml
  deploy/v1.1.1/rbac-csi-azuredisk-controller.yaml
  deploy/v1.1.1/rbac-csi-azuredisk-node.yaml
  deploy/v1.1.1/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.1.1.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XXL

#754 chore: switch master branch to use v1.2.0
  Makefile
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.1.1.tgz
  charts/latest/azuredisk-csi-driver-v1.2.0.tgz
  charts/latest/azuredisk-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#757 test: fix go mod issue with go1.16
  .github/workflows/darwin.yaml
  .github/workflows/linux.yml
  .github/workflows/windows.yml
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/test, size/M

#756 feat: Add v2 driver and container build to support e2e tests
  Makefile
  charts/index.yaml
  charts/v2.0.0-alpha.1/azuredisk-csi-driver-v2.0.0-alpha.1.tgz
  charts/v2.0.0-alpha.1/azuredisk-csi-driver/Chart.yaml
  charts/v2.0.0-alpha.1/azuredisk-csi-driver/templates/NOTES.txt
  charts/v2.0.0-alpha.1/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v2.0.0-alpha.1/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v2.0.0-alpha.1/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v2.0.0-alpha.1/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v2.0.0-alpha.1/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v2.0.0-alpha.1/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v2.0.0-alpha.1/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v2.0.0-alpha.1/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v2.0.0-alpha.1/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v2.0.0-alpha.1/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v2.0.0-alpha.1/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v2.0.0-alpha.1/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v2.0.0-alpha.1/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v2.0.0-alpha.1/azuredisk-csi-driver/values.yaml
  deploy/v2.0.0-alpha.1/crd-csi-snapshot.yaml
  deploy/v2.0.0-alpha.1/csi-azuredisk-controller.yaml
  deploy/v2.0.0-alpha.1/csi-azuredisk-driver.yaml
  deploy/v2.0.0-alpha.1/csi-azuredisk-node-windows.yaml
  deploy/v2.0.0-alpha.1/csi-azuredisk-node.yaml
  deploy/v2.0.0-alpha.1/csi-snapshot-controller.yaml
  deploy/v2.0.0-alpha.1/rbac-csi-azuredisk-controller.yaml
  deploy/v2.0.0-alpha.1/rbac-csi-azuredisk-node.yaml
  deploy/v2.0.0-alpha.1/rbac-csi-snapshot-controller.yaml
  docs/csi-dev.md
  pkg/azurediskplugin/Dockerfile
  pkg/azurediskplugin/Windows.Dockerfile
  pkg/azurediskplugin/dev.Dockerfile
  test/e2e/README.md
Labels: approved, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, size/XXL

#758 fix: add a wait period for statefulset update in e2e tests
  test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#759 fix: windows e2e test helm install command
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#761 chore: upgrade azure lib
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/deploymentclient/azure_deploymentclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/fileclient/azure_fileclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/fileclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_instance_metadata.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#762 feat: increase driver memory limit
  charts/latest/azuredisk-csi-driver-v1.2.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/S

#764 chore: upgrade csi-provisioner to v2.1.0
  README.md
  charts/latest/azuredisk-csi-driver-v1.2.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/S

#765 feat: upgrade csi-attacher to v3.1.0
  charts/latest/azuredisk-csi-driver-v1.2.0.tgz
  charts/latest/azuredisk-csi-driver/templates/_helpers.tpl
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/rbac-csi-azuredisk-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/S

#766 test: print out node labels
  test/utils/azuredisk_log.sh
  test/utils/controller-manager-log.sh
Labels: approved, cncf-cla: yes, kind/test, size/XS

#768 fix: check disk state before attach disk
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/auth/azure_auth.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/doc.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/metrics/azure_metrics.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_backoff.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_blobDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_config.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_fakes.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_instance_metadata.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_instances.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_mock_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_ratelimit.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storage.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_wrap.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_zones.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/retry/azure_error.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/bug, size/XXL

#770 docs: Add summary design documentation for Azure Disk CSI Driver V2
  docs/design-v2.md
  docs/images/mandalay_arch.png
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/L

#771 fix: listVolumes should not return error when no volume was found
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S
