Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2022-03, with the labels that each got.

#1196 feat: add supportZone param in chart config
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.13.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  pkg/azuredisk/azure_dd_max_disk_count.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azuredisk/fake_azuredisk_v2.go
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
  pkg/azuredisk/nodeserver_v2.go
  pkg/azurediskplugin/main.go
  test/integration/run-test.sh
  test/sanity/run-test.sh
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1200 fix: GetNodeInfo should succeed when IMDS is unavailable
  Makefile
  charts/latest/azuredisk-csi-driver-v1.13.0.tgz
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/install-driver.sh
  deploy/rbac-csi-azuredisk-node.yaml
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
  pkg/azuredisk/nodeserver_v2.go
  pkg/azurediskplugin/main.go
  test/external-e2e/run.sh
Labels: kind/bug, approved, lgtm, cncf-cla: yes, size/L

#1203 cleanup: remove unnecessary namespace config in ClusterRole
  deploy/rbac-csi-azuredisk-controller.yaml
  deploy/rbac-csi-azuredisk-node.yaml
Labels: do-not-merge/hold, size/XS, approved, cncf-cla: yes, kind/cleanup

#1205 chore: Fix script to check for driver pod restarts
  test/utils/check_driver_pods_restart.sh
Labels: size/M, approved, lgtm, cncf-cla: yes, kind/cleanup

#1204 feat: add getNodeInfoFromLabels in chart config
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.13.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/testsuites.go
Labels: kind/feature, size/S, approved, lgtm, cncf-cla: yes

#1209 cleanup: get zone info in in driver initialization
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/optimization/device_perf_linux_test.go
  pkg/optimization/skus.go
  pkg/optimization/skus_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes, kind/cleanup

#1213 fix: disable disk capacity check in CreateVolume
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azurediskplugin/main.go
  test/sanity/run-test.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1214 doc: cut v1.13.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.13.0.tgz
  charts/v1.13.0/azuredisk-csi-driver-v1.13.0.tgz
  charts/v1.13.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.13.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.13.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.13.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.13.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.13.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.13.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.13.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.13.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.13.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.13.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.13.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.13.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.13.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.13.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.13.0/azuredisk-csi-driver/values.yaml
  deploy/v1.13.0/crd-csi-snapshot.yaml
  deploy/v1.13.0/csi-azuredisk-controller.yaml
  deploy/v1.13.0/csi-azuredisk-driver.yaml
  deploy/v1.13.0/csi-azuredisk-node-windows.yaml
  deploy/v1.13.0/csi-azuredisk-node.yaml
  deploy/v1.13.0/csi-snapshot-controller.yaml
  deploy/v1.13.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.13.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.13.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.13.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1215 chore: switch master branch to use v1.14.0
  Makefile
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.13.0.tgz
  charts/latest/azuredisk-csi-driver-v1.14.0.tgz
  charts/latest/azuredisk-csi-driver/Chart.yaml
Labels: kind/documentation, size/M, approved, cncf-cla: yes

#1222 fix: CVE-2022-0778 in image build
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azurediskplugin/Dockerfile
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1223 [V2] fix: Fix CVE-2022-0778
  pkg/azurediskplugin/Dockerfile
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes

#1221 test: fix capz test failure
  Makefile
  test/e2e/testsuites/pre_provisioned_dangling_attach_volume_tester.go
  test/e2e/testsuites/testsuites.go
Labels: size/S, kind/failing-test, approved, cncf-cla: yes

#1225 feat: add support for btrfs resize
  go.mod
  go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/klog/v2/klog_file_others.go
  vendor/k8s.io/klog/v2/klog_file_windows.go
  vendor/k8s.io/mount-utils/OWNERS
  vendor/k8s.io/mount-utils/README.md
  vendor/k8s.io/mount-utils/mount_helper_unix.go
  vendor/k8s.io/mount-utils/resizefs_linux.go
  vendor/k8s.io/utils/clock/clock.go
  vendor/k8s.io/utils/clock/testing/fake_clock.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/modules.txt
Labels: kind/feature, approved, cncf-cla: yes, size/L

#1231 [V2] fix: Fix CVE-2022-0778 for libretls
  pkg/azurediskplugin/Dockerfile
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes

#1229 [V2] fix: prevent race between controller reconciler and controller recovery
  pkg/azuredisk/azuredisk_v2.go
  pkg/controller/attach_detach.go
  pkg/controller/azdrivernode.go
  pkg/controller/azvolume.go
  pkg/controller/common.go
  pkg/controller/common_test.go
  pkg/controller/node_availability.go
  pkg/controller/pod.go
  pkg/controller/pv.go
  pkg/controller/replica.go
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1230 chore: refine prometheus metrics
  go.mod
  go.sum
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
  vendor/github.com/Azure/azure-sdk-for-go/version/version.go
  vendor/github.com/spf13/cobra/MAINTAINERS
  vendor/github.com/spf13/cobra/Makefile
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/projects_using_cobra.md
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/user_guide.md
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_can_convert.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_legacy.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/metrics/azure_metrics.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_backoff.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_routes.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes

#1232 feat: add azureGoSDKLogLevel config in chart
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.14.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  test/external-e2e/run.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1233 test: fix volume cloning test failure on capz
  test/e2e/dynamic_provisioning_test.go
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#1228 [V2] bug: controller operation queue fix
  pkg/controller/common.go
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1236 Add nearora to the reviewers/approvers list for main_v2 branch
  OWNERS
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1238 fix: leader-election namespace issue
  charts/latest/azuredisk-csi-driver-v1.14.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-snapshot-controller.yaml
  hack/verify-all.sh
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1239 chore: upgrade azure lib
  go.mod
  go.sum
  vendor/github.com/Azure/azure-sdk-for-go/version/version.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/cache/azure_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss_cache.go
Labels: kind/feature, approved, cncf-cla: yes, size/L

#1241 doc: cut v1.14.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.14.0.tgz
  charts/v1.14.0/azuredisk-csi-driver-v1.14.0.tgz
  charts/v1.14.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.14.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.14.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.14.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.14.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.14.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.14.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/v1.14.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.14.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.14.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.14.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.14.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.14.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.14.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.14.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.14.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.14.0/azuredisk-csi-driver/values.yaml
  deploy/v1.14.0/crd-csi-snapshot.yaml
  deploy/v1.14.0/csi-azuredisk-controller.yaml
  deploy/v1.14.0/csi-azuredisk-driver.yaml
  deploy/v1.14.0/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.14.0/csi-azuredisk-node-windows.yaml
  deploy/v1.14.0/csi-azuredisk-node.yaml
  deploy/v1.14.0/csi-snapshot-controller.yaml
  deploy/v1.14.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.14.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.14.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.14.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1243 chore: switch master branch to use v1.15.0
  Makefile
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.14.0.tgz
  charts/latest/azuredisk-csi-driver-v1.15.0.tgz
  charts/latest/azuredisk-csi-driver/Chart.yaml
Labels: kind/documentation, size/M, approved, cncf-cla: yes

#1240 [V2] chore: Fixing azuredisk csi node sa permissions and v2.0.0-alpha tag
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.1.tgz
  charts/latest-v2/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v2.0.0-alpha.1/azuredisk-csi-driver-v2.0.0-alpha.1.tgz
  deploy/latest-v2/rbac-csi-azuredisk-node.yaml
  deploy/v2.0.0-alpha.1/csi-azuredisk-controller.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1249 fix: CVE issues in image build
  pkg/azurediskplugin/Dockerfile
  pkg/azurediskplugin/Windows.Dockerfile
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#1114 test: run external 1.23 tests
  test/external-e2e/run.sh
Labels: do-not-merge/hold, size/XS, approved, cncf-cla: yes, kind/test

#1248 fix: disk attach/detach failure when operation is preempted
  go.mod
  go.sum
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/RELEASING.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/matchers/contain_element_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_each_matcher.go
  vendor/golang.org/x/net/http2/go118.go
  vendor/golang.org/x/net/http2/not_go118.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/term/codereview.cfg
  vendor/golang.org/x/term/term.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmclient/azure_vmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#1245 [V2] chore: Adding flags for qps and disabling listvolume by default.
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/nodeserver_v2.go
  pkg/azurediskplugin/main.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1247 [V2] fix: Avoid calling detach for ControllerUnpublish Volume
  pkg/provisioner/crdprovisioner.go
Labels: kind/bug, approved, lgtm, cncf-cla: yes, size/L

#1246 [V2] bug: fix AzVolumeAttachment clean-up
  pkg/controller/common.go
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#1250 [V2] bug: UnpublishVolume should not delete the CRI without detaching
  pkg/controller/common.go
  pkg/provisioner/crdprovisioner.go
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1251 [V2] chore: Create helm charts and release files for v2.0.0-beta.1 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver-v2.0.0-beta.1.tgz
  charts/v2.0.0-beta.1/azuredisk-csi-driver/Chart.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/side-by-side-values.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/NOTES.txt
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/csi-azuredisk-controller-cleanup.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/csi-azuredisk-controller-monitor.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/csi-azuredisk-controller-service.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/csi-azuredisk-scheduler-extender-monitor.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/csi-azuredisk-scheduler-extender-service.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/csi-azuredisk-scheduler-extender.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/csi-azuredisk-storage-class.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/disk.csi.azure.com_azdrivernodes.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/disk.csi.azure.com_azvolumeattachments.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/disk.csi.azure.com_azvolumes.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/namespace-azure-disk-csi.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/rbac-csi-azuredisk-scheduler-extender.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-scheduler-extender.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v2.0.0-beta.1/azuredisk-csi-driver/values.yaml
  deploy/example/failover/README.md
  deploy/v2.0.0-beta.1/crd-csi-snapshot.yaml
  deploy/v2.0.0-beta.1/csi-azuredisk-controller.yaml
  deploy/v2.0.0-beta.1/csi-azuredisk-driver.yaml
  deploy/v2.0.0-beta.1/csi-azuredisk-node-windows.yaml
  deploy/v2.0.0-beta.1/csi-azuredisk-node.yaml
  deploy/v2.0.0-beta.1/csi-azuredisk-scheduler-extender.yaml
  deploy/v2.0.0-beta.1/csi-snapshot-controller.yaml
  deploy/v2.0.0-beta.1/disk.csi.azure.com_azdrivernodes.yaml
  deploy/v2.0.0-beta.1/disk.csi.azure.com_azvolumeattachments.yaml
  deploy/v2.0.0-beta.1/disk.csi.azure.com_azvolumes.yaml
  deploy/v2.0.0-beta.1/namespace-azure-disk-csi.yaml
  deploy/v2.0.0-beta.1/rbac-csi-azuredisk-controller.yaml
  deploy/v2.0.0-beta.1/rbac-csi-azuredisk-node.yaml
  deploy/v2.0.0-beta.1/rbac-csi-azuredisk-scheduler-extender.yaml
  deploy/v2.0.0-beta.1/rbac-csi-snapshot-controller.yaml
Labels: approved, lgtm, cncf-cla: yes, size/XXL

#1252 [V2] chore: Address ShellCheck warnings in azure-cluster-up.sh
  hack/azure-cluster-up.sh
Labels: size/M, approved, lgtm, cncf-cla: yes, kind/cleanup
