Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2022-10, with the labels that each got.

#1539 fix: increase csi-attacher client QPS
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-controller.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#1540 [V2] chore: increase kubeclient qps
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.8.tgz
  charts/latest-v2/azuredisk-csi-driver/values.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes, kind/cleanup

#1531 [V2] feat: added attach_volume_latency metric for controllerserver
  pkg/azuredisk/controllerserver_v2.go
  pkg/provisioner/fake_crdprovisioner.go
Labels: size/S, approved, lgtm, cncf-cla: yes, ok-to-test, kind/test

#1543 chore: upgrde azure cloud provider lib with vmss flex change
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_instance_metadata.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_instances.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmssflex_cache.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes

#1533 doc: add config doc for edge zone
  README.md
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#1523 [V2] test: add a failover scale test
  test/e2e/testsuites/azdiskschedulerextender_pod_scheduling_on_failover_multiple_pv_perf_tester.go
  test/e2e/testsuites/dynamically_provisioned_garbage_collection_replica_attachment_tester.go
  test/e2e/testsuites/dynamically_provisioned_pod_failover_tester.go
  test/e2e/testsuites/dynamically_provisioned_pod_failover_with_replicas_tester.go
  test/e2e/testsuites/dynamically_provisioned_pod_scale_up_with_replicas.go
  test/e2e/testsuites/pre_provisioned_dangling_attach_volume_tester.go
  test/resources/pod.go
  test/scale/azdisk_scale_test.go
  test/scale/flags.go
  test/scale/scale_tester.go
  test/utils/node/node_utils.go
  test/utils/pod/pod_utils.go
  test/utils/volume/vol_utils.go
Labels: approved, lgtm, cncf-cla: yes, size/L, ok-to-test, kind/test

#1545 [V2] test: Enable dynamically provisioned volume snapshot test in Windows cluster
  Makefile
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
  test/utils/testutil/env_utils.go
  test/utils/testutil/test_ops_util.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test, kind/test

#1548 test: Enable dynamically provisioned volume snapshot test in Windows cluster
  Makefile
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
  test/e2e/testsuites/testsuites.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test, kind/test

#1549 [V2] test: Enable test in windows
  test/e2e/dynamic_provisioning_test.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test, kind/test

#1542 [V2] feat: add preferred affinity logic and unit tests for prioritize and filter logic
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.8.tgz
  charts/latest-v2/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  deploy/latest-v2/rbac-csi-azuredisk-controller.yaml
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/azuredisk_v2_test.go
  pkg/controller/common.go
  pkg/controller/common_test.go
  pkg/controller/shared_state.go
  pkg/controller/shared_state_test.go
  pkg/provisioner/crdprovisioner_test.go
  test/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/XXL

#1550 [V2] bug: fix in conversion for scheduler extender latency log
  pkg/azdiskschedulerextender/azdiskschedulerextender_metrics.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#1552 [V2] fix: adding cluster provisioner variable
  test/podFailover/workload/chart/templates/workload.yaml
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#1553 [V2] feat: backload API DELETE call to deload api server calls upon detachment
  pkg/controller/attach_detach.go
  pkg/controller/attach_detach_test.go
  pkg/controller/azdrivernode_test.go
  pkg/controller/azvolume_test.go
  pkg/controller/common.go
  pkg/controller/replica.go
  pkg/controller/replica_test.go
  pkg/controller/shared_state.go
  pkg/provisioner/crdprovisioner.go
  pkg/provisioner/crdprovisioner_test.go
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/L

#1559 feat: increase api qps limit of csi-provisioner and csi-attacher
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1554 [V2] test: make maxShares configurable to scale test
  Makefile
  test/scale/azdisk_scale_test.go
  test/scale/flags.go
  test/scale/scale_tester.go
  test/utils/pod/pod_utils.go
  test/utils/volume/vol_utils.go
Labels: approved, lgtm, cncf-cla: yes, size/L, ok-to-test, kind/test

#1561 cleanup: remove unnecessary tp nil check
  pkg/azureutils/azure_snapshot_utils.go
Labels: size/XS, approved, cncf-cla: yes, kind/cleanup

#1565 doc: cut v1.24.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/v1.24.0/azuredisk-csi-driver-v1.24.0.tgz
  charts/v1.24.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.24.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.24.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.24.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.24.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.24.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.24.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/v1.24.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.24.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.24.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.24.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.24.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.24.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.24.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.24.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.24.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.24.0/azuredisk-csi-driver/values.yaml
  deploy/v1.24.0/crd-csi-snapshot.yaml
  deploy/v1.24.0/csi-azuredisk-controller.yaml
  deploy/v1.24.0/csi-azuredisk-driver.yaml
  deploy/v1.24.0/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.24.0/csi-azuredisk-node-windows.yaml
  deploy/v1.24.0/csi-azuredisk-node.yaml
  deploy/v1.24.0/csi-snapshot-controller.yaml
  deploy/v1.24.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.24.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.24.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.24.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1566 [V2] fix: fix kubeclient configuration in Helm chart
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.8.tgz
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes

#1571 [V2] chore: add caller to WaitFor(Attach|Detach)
  pkg/provisioner/crdprovisioner.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/cleanup
