Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2022-01, with the labels that each got.

#1126 test: add more golint checks
  .github/workflows/static.yaml
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1127 doc: change snapshot v1beta1 to v1
  deploy/example/snapshot/README.md
  deploy/example/snapshot/azuredisk-volume-snapshot.yaml
  deploy/example/snapshot/storageclass-azuredisk-snapshot.yaml
  docs/driver-parameters.md
Labels: kind/documentation, size/S, approved, cncf-cla: yes

#1130 test: change helm install method
  .github/workflows/linux.yml
  .github/workflows/static.yaml
  hack/helm-signing.asc
  hack/verify-all.sh
  hack/verify-helm-chart-files.sh
Labels: size/M, approved, lgtm, cncf-cla: yes, kind/test

#1110 bug: Adding supported VolumeCapabilites verification check to CSI RPC requests.
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
  pkg/azuredisk/nodeserver_v2.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/e2e/testsuites/pre_provisioned_dangling_attach_volume_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
Labels: approved, lgtm, cncf-cla: yes, size/XXL, ok-to-test

#1136 test: fix kcm log print issue
  test/utils/controller-manager-log.sh
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#1134 chore: Improve unit test coverage of pkg/azureutils
  pkg/azuredisk/controllerserver_test.go
  pkg/azureutils/azure_disk_utils_test.go
  pkg/azureutils/osiohandler_test.go
Labels: approved, lgtm, cncf-cla: yes, size/L, kind/cleanup

#1133 test: add workaround for capz tests
  Makefile
  hack/parse-prow-creds.sh
Labels: size/M, kind/failing-test, approved, cncf-cla: yes

#1138 test: fix get kcm logs error in e2e test
  test/utils/controller-manager-log.sh
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1140 fix: tag parsing issue in CreateSnapshot
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes

#1141 feat: upgrade to csi-attacher v3.4.0
  .github/workflows/static.yaml
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.11.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1144 feat: update max data disk count
  .github/workflows/static.yaml
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#1145 feat: upgrade to csi-snapshotter v5.0.1
  .github/workflows/static.yaml
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.11.0.tgz
  charts/latest/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/crd-csi-snapshot.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-snapshot-controller.yaml
  deploy/rbac-csi-azuredisk-controller.yaml
  deploy/rbac-csi-snapshot-controller.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1146 fix: add leases rbac delete permission
  charts/latest/azuredisk-csi-driver-v1.11.0.tgz
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  deploy/rbac-csi-azuredisk-controller.yaml
  deploy/rbac-csi-snapshot-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1147 fix: patchable CVEs in 1.2.0
  go.mod
  go.sum
  pkg/azurediskplugin/Dockerfile
  vendor/golang.org/x/text/encoding/simplifiedchinese/hzgb2312.go
  vendor/golang.org/x/text/internal/language/language.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/language/go1_1.go
  vendor/golang.org/x/text/language/go1_2.go
  vendor/golang.org/x/text/language/language.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/language/tables.go
  vendor/golang.org/x/text/secure/bidirule/bidirule10.0.0.go
  vendor/golang.org/x/text/secure/bidirule/bidirule9.0.0.go
  vendor/golang.org/x/text/unicode/bidi/bidi.go
  vendor/golang.org/x/text/unicode/bidi/core.go
  vendor/golang.org/x/text/unicode/bidi/tables10.0.0.go
  vendor/golang.org/x/text/unicode/bidi/tables11.0.0.go
  vendor/golang.org/x/text/unicode/bidi/tables12.0.0.go
  vendor/golang.org/x/text/unicode/bidi/tables13.0.0.go
  vendor/golang.org/x/text/unicode/bidi/tables9.0.0.go
  vendor/golang.org/x/text/unicode/norm/tables10.0.0.go
  vendor/golang.org/x/text/unicode/norm/tables11.0.0.go
  vendor/golang.org/x/text/unicode/norm/tables12.0.0.go
  vendor/golang.org/x/text/unicode/norm/tables13.0.0.go
  vendor/golang.org/x/text/unicode/norm/tables9.0.0.go
  vendor/k8s.io/kubernetes/pkg/apis/core/annotation_key_constants.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: size/XL, approved, lgtm, cncf-cla: yes, ok-to-test

#1149 fix: patch CVE-2021-3995 and CVE-2021-3996
  pkg/azurediskplugin/Dockerfile
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#1150 fix: CVE-2021-3996 in image build
  pkg/azurediskplugin/Dockerfile
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes

#1154 cleanup: remove unnecessary packages
  pkg/azurediskplugin/Dockerfile
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/cleanup

#1156 test: Add shared disk E2E tests that match supported scenario
  test/e2e/driver/azuredisk_driver.go
  test/e2e/driver/driver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_shared_disk_tester.go
  test/e2e/testsuites/pre_provisioned_shared_disk_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
Labels: size/XL, approved, lgtm, cncf-cla: yes, kind/test

#1159 chore: Remove obsolete & redundant test shared disk case
  test/e2e/pre_provisioning_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes, kind/cleanup

#1158 cleanup: remove useless csi-common code
  pkg/csi-common/controllerserver-default.go
  pkg/csi-common/controllerserver-default_test.go
  pkg/csi-common/identityserver-default.go
  pkg/csi-common/identityserver-default_test.go
  pkg/csi-common/nodeserver-default.go
  pkg/csi-common/nodeserver-default_test.go
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
Labels: size/XL, approved, lgtm, cncf-cla: yes, kind/cleanup

#1163 test: add more go linters
  .github/workflows/static.yaml
  pkg/azurediskplugin/main.go
  pkg/azureutils/azure_disk_utils.go
  pkg/util/util_test.go
Labels: size/S, approved, cncf-cla: yes, kind/test
