Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2022-04, with the labels that each got.

#1256 chore: update max data disk count table
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1259 [V2] bug: expandVolume does not get retriggered upon failed operation
  pkg/provisioner/crdprovisioner.go
  pkg/provisioner/crdprovisioner_test.go
Labels: size/S, approved, lgtm, cncf-cla: yes, ok-to-test

#1260 doc: cut v1.15.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.15.0.tgz
  charts/v1.15.0/azuredisk-csi-driver-v1.15.0.tgz
  charts/v1.15.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.15.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.15.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.15.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.15.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.15.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.15.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/v1.15.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.15.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.15.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.15.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.15.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.15.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.15.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.15.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.15.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.15.0/azuredisk-csi-driver/values.yaml
  deploy/v1.15.0/crd-csi-snapshot.yaml
  deploy/v1.15.0/csi-azuredisk-controller.yaml
  deploy/v1.15.0/csi-azuredisk-driver.yaml
  deploy/v1.15.0/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.15.0/csi-azuredisk-node-windows.yaml
  deploy/v1.15.0/csi-azuredisk-node.yaml
  deploy/v1.15.0/csi-snapshot-controller.yaml
  deploy/v1.15.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.15.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.15.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.15.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1262 chore: switch master branch to use v1.16.0
  Makefile
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.15.0.tgz
  charts/latest/azuredisk-csi-driver-v1.16.0.tgz
  charts/latest/azuredisk-csi-driver/Chart.yaml
Labels: kind/documentation, size/M, approved, cncf-cla: yes

#1254 [V2] chore: Switch main_v2 branch to v2.0.0-beta.2 version
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.1.tgz
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.2.tgz
  charts/latest-v2/azuredisk-csi-driver/Chart.yaml
Labels: size/M, approved, cncf-cla: yes, kind/cleanup

#1264 fix: CVE-2018-25032 in image build
  pkg/azurediskplugin/Dockerfile
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes

#1265 chore: upgrade azure cloud provider lib
  go.mod
  go.sum
  vendor/github.com/Azure/azure-sdk-for-go/version/version.go
  vendor/github.com/Azure/go-autorest/autorest/mocks/go_mod_tidy_hack.go
  vendor/github.com/Azure/go-autorest/autorest/mocks/mocks.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/auth/azure_auth.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/cache/azure_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer_backendpool.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss_cache.go
Labels: kind/feature, approved, cncf-cla: yes, size/L

#1266 test: add codeql-analysis github action
  .github/workflows/codeql-analysis.yml
Labels: size/M, approved, cncf-cla: yes, kind/test

#1263 doc: refine static PV example
  deploy/example/pv-azuredisk-csi.yaml
  deploy/example/pvc-azuredisk-csi-static.yaml
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#1268 test: fix golinter error
  .github/workflows/static.yaml
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#1267 Bump prometheus/client_golang to v1.11.1
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/build_info_pre_1.12.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/desc.go
  vendor/github.com/prometheus/client_golang/prometheus/expvar_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/prometheus/client_golang/prometheus/value.go
  vendor/github.com/prometheus/client_golang/prometheus/vec.go
  vendor/github.com/prometheus/client_golang/prometheus/wrap.go
  vendor/modules.txt
Labels: size/XL, approved, lgtm, cncf-cla: yes

#1269 [V2] test: fix golinter error
  .github/workflows/static.yaml
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1257 [V2] chore: make CRD status a sub-resource
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.2.tgz
  charts/latest-v2/azuredisk-csi-driver/templates/disk.csi.azure.com_azvolumeattachments.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/disk.csi.azure.com_azvolumes.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  deploy/latest-v2/disk.csi.azure.com_azvolumeattachments.yaml
  deploy/latest-v2/disk.csi.azure.com_azvolumes.yaml
  deploy/latest-v2/rbac-csi-azuredisk-node.yaml
  deploy/uninstall-driver.sh
  pkg/apis/azuredisk/v1beta1/types.go
  pkg/apis/azuredisk/v1beta1/zz_generated.deepcopy.go
  pkg/apis/config/disk.csi.azure.com_azvolumeattachments.yaml
  pkg/apis/config/disk.csi.azure.com_azvolumes.yaml
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azuredisk/interface_v2.go
  pkg/azuredisk/mockprovisioner/interface.go
  pkg/azuredisk/nodeserver_v2.go
  pkg/azuredisk/nodeserver_v2_test.go
  pkg/azureutils/azure_disk_utils.go
  pkg/controller/attach_detach.go
  pkg/controller/attach_detach_test.go
  pkg/controller/azvolume.go
  pkg/controller/azvolume_test.go
  pkg/controller/common.go
  pkg/controller/common_test.go
  pkg/controller/pv.go
  pkg/controller/replica.go
  pkg/controller/replica_test.go
  pkg/provisioner/crdprovisioner.go
  pkg/provisioner/crdprovisioner_test.go
  pkg/provisioner/fake_crdprovisioner.go
  test/integration/controller/controller_test.go
  test/latest/azuredisk-csi-driver/templates/disk.csi.azure.com_azvolumeattachments.yaml
  test/latest/azuredisk-csi-driver/templates/disk.csi.azure.com_azvolumes.yaml
Labels: size/XL, approved, lgtm, cncf-cla: yes, kind/cleanup, ok-to-test

#1270 [V2] chore: Updating cloud provider azure
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1271 test: enable external slow tests
  test/external-e2e/run.sh
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1274 [v2] chore: Re-generating index file for helm charts.
  charts/index.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1275 chore: update max data disk count table
  .github/workflows/windows.yml
  go.mod
  go.sum
  pkg/azuredisk/azure_dd_max_disk_count.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
  vendor/github.com/Azure/azure-sdk-for-go/version/version.go
  vendor/github.com/Azure/go-autorest/autorest/azure/environments.go
  vendor/github.com/Azure/go-autorest/autorest/azure/rp.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/storageaccountclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
Labels: kind/feature, approved, cncf-cla: yes, size/L

#1276 test: run more external fsType tests
  test/external-e2e/manifest/testdriver.yaml
  test/external-e2e/run.sh
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1278 test: enable external pvcDataSource test
  test/external-e2e/manifest/testdriver.yaml
  test/external-e2e/run.sh
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1279 chore: Update golang.org/x/crypto for CVE-2022-27191
  go.mod
  go.sum
  vendor/golang.org/x/crypto/chacha20/chacha_s390x.go
  vendor/golang.org/x/crypto/curve25519/internal/field/fe_amd64.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_generic.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_s390x.go
  vendor/golang.org/x/crypto/ssh/certs.go
  vendor/golang.org/x/crypto/ssh/cipher.go
  vendor/golang.org/x/crypto/ssh/client.go
  vendor/golang.org/x/crypto/ssh/client_auth.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/doc.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/kex.go
  vendor/golang.org/x/crypto/ssh/keys.go
  vendor/golang.org/x/crypto/ssh/messages.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/session.go
  vendor/golang.org/x/crypto/ssh/transport.go
  vendor/modules.txt
Labels: size/XL, approved, lgtm, cncf-cla: yes, kind/cleanup

#1281 doc: cut v1.16.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.16.0.tgz
  charts/v1.16.0/azuredisk-csi-driver-v1.16.0.tgz
  charts/v1.16.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.16.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.16.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.16.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.16.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.16.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.16.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/v1.16.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.16.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.16.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.16.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.16.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.16.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.16.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.16.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.16.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.16.0/azuredisk-csi-driver/values.yaml
  deploy/v1.16.0/crd-csi-snapshot.yaml
  deploy/v1.16.0/csi-azuredisk-controller.yaml
  deploy/v1.16.0/csi-azuredisk-driver.yaml
  deploy/v1.16.0/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.16.0/csi-azuredisk-node-windows.yaml
  deploy/v1.16.0/csi-azuredisk-node.yaml
  deploy/v1.16.0/csi-snapshot-controller.yaml
  deploy/v1.16.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.16.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.16.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.16.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1283 chore: switch master branch to use v1.17.0
  Makefile
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.16.0.tgz
  charts/latest/azuredisk-csi-driver-v1.17.0.tgz
  charts/latest/azuredisk-csi-driver/Chart.yaml
Labels: kind/documentation, size/M, approved, cncf-cla: yes

#1280 test: support Win2022 test on capz
  hack/verify-examples.sh
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, size/L, kind/test

#1285 [V2] fix: Fix script to check for driver pod restarts🐞
  test/utils/check_driver_pods_restart.sh
Labels: kind/bug, size/S, approved, lgtm, cncf-cla: yes, ok-to-test

#1287 feat: add controller.vmssCacheTTLInSeconds in helm chart config
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.17.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  pkg/azuredisk/azuredisk.go
  pkg/azurediskplugin/main.go
  test/external-e2e/run.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1289 fix: CVE-2022-1271 in image build
  pkg/azurediskplugin/Dockerfile
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#1290 [V2] fix: Fix verify-examples.sh leak resources created 🐞
  hack/verify-examples.sh
Labels: size/S, approved, lgtm, cncf-cla: yes, kind/cleanup, ok-to-test

#1291 chore: refine package patching in image build
  pkg/azurediskplugin/Dockerfile
Labels: size/XS, approved, cncf-cla: yes, kind/cleanup

#1296 chore: refine metrics naming
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
Labels: size/M, do-not-merge/hold, approved, cncf-cla: yes, kind/cleanup

#1294 [V2] bug: failed operation should not be requeued if operation queue is scheduled for deletion
  pkg/controller/azvolume.go
  pkg/controller/common.go
Labels: kind/bug, size/S, approved, lgtm, cncf-cla: yes, ok-to-test

#1303 [V2] chore: Address linter issues in az-analyze tool
  .golangci.yml
  cmd/az-analyze/cmd/azv.go
Labels: size/S, approved, cncf-cla: yes, kind/cleanup

#1273 [V2] feat: add end to end workflow logging
  go.mod
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azureutils/azure_disk_utils.go
  pkg/controller/attach_detach.go
  pkg/controller/attach_detach_test.go
  pkg/controller/azdrivernode.go
  pkg/controller/azdrivernode_test.go
  pkg/controller/azvolume.go
  pkg/controller/azvolume_test.go
  pkg/controller/common.go
  pkg/controller/node_availability.go
  pkg/controller/node_availability_test.go
  pkg/controller/pod.go
  pkg/controller/pod_test.go
  pkg/controller/pv.go
  pkg/controller/pv_test.go
  pkg/controller/replica.go
  pkg/controller/replica_test.go
  pkg/provisioner/cloudprovisioner.go
  pkg/provisioner/cloudprovisioner_test.go
  pkg/provisioner/conditionwaiter.go
  pkg/provisioner/crdprovisioner.go
  pkg/provisioner/crdprovisioner_test.go
  pkg/workflow/logger.go
  pkg/workflow/workflow.go
  pkg/workflow/workflow_test.go
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/XXL, ok-to-test

#1298 [V2] bug: collocated pod tester fix
  test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#1304 chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.17.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/feature, size/S, approved, lgtm, cncf-cla: yes

#1310 doc: cut v1.17.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.17.0.tgz
  charts/v1.17.0/azuredisk-csi-driver-v1.17.0.tgz
  charts/v1.17.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.17.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.17.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.17.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.17.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.17.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.17.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/v1.17.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.17.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.17.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.17.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.17.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.17.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.17.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.17.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.17.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.17.0/azuredisk-csi-driver/values.yaml
  deploy/v1.17.0/crd-csi-snapshot.yaml
  deploy/v1.17.0/csi-azuredisk-controller.yaml
  deploy/v1.17.0/csi-azuredisk-driver.yaml
  deploy/v1.17.0/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.17.0/csi-azuredisk-node-windows.yaml
  deploy/v1.17.0/csi-azuredisk-node.yaml
  deploy/v1.17.0/csi-snapshot-controller.yaml
  deploy/v1.17.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.17.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.17.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.17.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1312 chore: switch master branch to use v1.18.0
  Makefile
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.17.0.tgz
  charts/latest/azuredisk-csi-driver-v1.18.0.tgz
  charts/latest/azuredisk-csi-driver/Chart.yaml
Labels: kind/documentation, size/M, approved, cncf-cla: yes
