Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2022-09, with the labels that each got.

#1494 fix: Ultra Disk DefaultDiskMBPSReadWrite calc issue
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/util/util.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1495 [V2] refactor: move funtions to shared_state.go
  pkg/controller/attach_detach.go
  pkg/controller/azvolume.go
  pkg/controller/shared_state.go
Labels: approved, lgtm, cncf-cla: yes, size/L, kind/cleanup, ok-to-test

#1498 fix: reduce VMSS throttling when throttling happens
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#1504 fix: adding optional workload value to pod-failover
  test/e2e/manifest/pod-failover.json
  test/podFailover/workload/chart/templates/workload.yaml
  test/podFailover/workload/scenarios/azDiskV2-Replicas.yaml
  test/podFailover/workload/scenarios/azDiskV2-noReplicas.yaml
Labels: kind/feature, size/S, approved, lgtm, cncf-cla: yes, ok-to-test

#1502 [V2] test: add unit test to azvolume.go
  pkg/controller/azvolume_test.go
Labels: size/S, approved, lgtm, cncf-cla: yes, ok-to-test, kind/test

#1503 [V2] test: add unit tests to attach_detach.go
  pkg/controller/attach_detach_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test, kind/test

#1500 [V2] test: add and edit unit tests to replica.go
  pkg/controller/replica_test.go
Labels: approved, lgtm, cncf-cla: yes, size/L, ok-to-test, kind/test

#1501 [V2] test: add and edit unit tests to pod.go
  pkg/controller/pod_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test, kind/test

#1499 [V2] test: add unit tests to pv.go
  pkg/controller/common_test.go
  pkg/controller/pv.go
  pkg/controller/pv_test.go
Labels: approved, lgtm, cncf-cla: yes, size/L, ok-to-test, kind/test

#1508 [V2] fix: adding scheduler to pod-failover workload pods
  test/e2e/manifest/pod-failover.json
  test/podFailover/controller/cmd/main.go
  test/podFailover/workload/chart/templates/workload.yaml
  test/podFailover/workload/scenarios/azDiskV2-Replicas.yaml
  test/podFailover/workload/scenarios/sameNodeFailover.yaml
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1510 chore: upgrade azure cloud provider lib
  go.mod
  go.sum
  pkg/azuredisk/azure_dd_max_disk_count.go
  vendor/golang.org/x/net/html/render.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
Labels: kind/feature, approved, cncf-cla: yes, size/L

#1516 [V2] chore: update net/http to fix CVE-2022-27664 vulnerability
  go.mod
  go.sum
  vendor/golang.org/x/net/AUTHORS
  vendor/golang.org/x/net/CONTRIBUTORS
  vendor/golang.org/x/net/context/context.go
  vendor/golang.org/x/net/context/go17.go
  vendor/golang.org/x/net/context/pre_go17.go
  vendor/golang.org/x/net/html/render.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http/httpguts/httplex.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/errors.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/hpack/huffman.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/golang.org/x/net/idna/trieval.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/modules.txt
Labels: size/XL, approved, lgtm, cncf-cla: yes

#1513 test: run sanity test on csi-test v5.0.0
  test/sanity/run-test.sh
  test/sanity/run-tests-all-clouds.sh
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1517 [V2] test: add unit tests for UpdateCRIWithRetry
  pkg/azureutils/azure_disk_utils_test.go
  pkg/azureutils/mockclient/doc.go
  pkg/azureutils/mockclient/interface.go
  pkg/controller/attach_detach_test.go
  pkg/controller/azdrivernode_test.go
  pkg/controller/azvolume_test.go
  pkg/controller/common_test.go
  pkg/controller/node_availability_test.go
  pkg/controller/pod_test.go
  pkg/controller/pv_test.go
  pkg/controller/replica_test.go
  pkg/controller/shared_state_test.go
  pkg/controller/volumeattachment_test.go
Labels: approved, cncf-cla: yes, size/XXL, kind/test

#1519 [V2] fix: minor bugfix in replic management logic
  pkg/controller/attach_detach.go
  pkg/controller/azvolume.go
  pkg/controller/common.go
  pkg/controller/replica.go
  pkg/controller/shared_state.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#1506 [V2] chore: update values as per p50 numbers
  charts/latest-v2/azuredisk-csi-driver/values.yaml
  deploy/latest-v2/csi-azuredisk-scheduler-extender.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1515 [V2] Adding options to configure attach/detach rate limiter on azure client
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest-v2/azuredisk-csi-driver/values.yaml
  go.mod
  go.sum
  pkg/apis/azuredisk/v1beta2/types.go
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/controllerserver.go
  pkg/azurediskplugin/main.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
  pkg/provisioner/cloudprovisioner.go
  test/e2e/suite_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
Labels: approved, lgtm, cncf-cla: yes, size/L

#1521 fix: zone format check when cloud config is empty
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1522 [V2] feat: make initial attach/detach disk batch delay configurable
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.7.tgz
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest-v2/azuredisk-csi-driver/values.yaml
  go.mod
  go.sum
  pkg/apis/azuredisk/v1beta2/types.go
  pkg/azureconstants/azure_constants.go
  pkg/azurediskplugin/main.go
  pkg/azureutils/azure_disk_utils.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_ratelimit.go
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/L

#1518 [V2] fix: CRI recovery should not overwrite existing values
  go.mod
  go.sum
  pkg/apis/azuredisk/v1beta2/types.go
  pkg/azureconstants/azure_constants.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
  pkg/controller/attach_detach.go
  pkg/controller/attach_detach_test.go
  pkg/controller/azvolume_test.go
  pkg/controller/common.go
  pkg/controller/common_test.go
  pkg/controller/pod_test.go
  pkg/controller/shared_state.go
  pkg/provisioner/crdprovisioner.go
  test/const/test_consts.go
  test/upgrade/flags.go
  test/upgrade/upgrade_test.go
  vendor/k8s.io/csi-translation-lib/LICENSE
  vendor/k8s.io/csi-translation-lib/plugins/aws_ebs.go
  vendor/k8s.io/csi-translation-lib/plugins/azure_disk.go
  vendor/k8s.io/csi-translation-lib/plugins/azure_file.go
  vendor/k8s.io/csi-translation-lib/plugins/const.go
  vendor/k8s.io/csi-translation-lib/plugins/gce_pd.go
  vendor/k8s.io/csi-translation-lib/plugins/in_tree_volume.go
  vendor/k8s.io/csi-translation-lib/plugins/openstack_cinder.go
  vendor/k8s.io/csi-translation-lib/plugins/portworx.go
  vendor/k8s.io/csi-translation-lib/plugins/rbd.go
  vendor/k8s.io/csi-translation-lib/plugins/vsphere_volume.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, cncf-cla: yes, size/XXL

#1524 [V2] chore: add the caller to ConditionWaiter.Wait workflow
  pkg/watcher/conditionwaiter.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/cleanup

#1525 [V2] chore: add retry details to workflow logging in UpdateCRIWithRetry
  pkg/azureconstants/azure_constants.go
  pkg/azureutils/azure_disk_utils.go
Labels: size/S, approved, lgtm, cncf-cla: yes, kind/cleanup

#1526 [V2] feat: enable configuration of KubeClient burst setting
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.7.tgz
  charts/latest-v2/azuredisk-csi-driver/azuredisk-csi-driver-v2.0.0-beta.6.tgz
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest-v2/azuredisk-csi-driver/values.yaml
  pkg/apis/azuredisk/v1beta2/types.go
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azurediskplugin/main.go
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/L

#1529 chore: adjust rate limiter to drive to target CRP limits
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.7.tgz
  charts/latest-v2/azuredisk-csi-driver/values.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes, kind/cleanup

#1507 chore: update values as per p50 numbers
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.7.tgz
  charts/latest-v2/azuredisk-csi-driver/values.yaml
  deploy/latest-v2/csi-azuredisk-scheduler-extender.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes

#1530 [V2] fix: az-log panics when getting the controller logs
  cmd/az-log/README.md
  cmd/az-log/cmd/common.go
  cmd/az-log/cmd/controller.go
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1496 feat(helm): add support for labels, annotations and podAnnotations
  charts/README.md
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.7.tgz
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-controller-monitor.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-scheduler-extender.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest-v2/azuredisk-csi-driver/values.yaml
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/L, ok-to-test

#1535 doc: cut v1.23.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/v1.23.0/azuredisk-csi-driver-v1.23.0.tgz
  charts/v1.23.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.23.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.23.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.23.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.23.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.23.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.23.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/v1.23.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.23.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.23.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.23.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.23.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.23.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.23.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.23.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.23.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.23.0/azuredisk-csi-driver/values.yaml
  deploy/v1.23.0/crd-csi-snapshot.yaml
  deploy/v1.23.0/csi-azuredisk-controller.yaml
  deploy/v1.23.0/csi-azuredisk-driver.yaml
  deploy/v1.23.0/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.23.0/csi-azuredisk-node-windows.yaml
  deploy/v1.23.0/csi-azuredisk-node.yaml
  deploy/v1.23.0/csi-snapshot-controller.yaml
  deploy/v1.23.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.23.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.23.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.23.0.md
  hack/verify-helm-chart-index.sh
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1538 chore: upgrade base image debian-base:bullseye-v1.4.2
  pkg/azurediskplugin/Dockerfile
Labels: kind/feature, size/XS, approved, cncf-cla: yes
