Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2022-06, with the labels that each got.

#1300 [V2] chore: DeleteVolume should wait for replicas to be fully deleted
  pkg/azureconstants/azure_constants.go
  pkg/controller/azvolume.go
  pkg/controller/azvolume_test.go
  pkg/controller/common.go
  pkg/controller/replica.go
  pkg/controller/replica_test.go
  pkg/provisioner/crdprovisioner.go
  pkg/provisioner/crdprovisioner_test.go
  pkg/watcher/conditionwaiter.go
  pkg/watcher/conditionwatcher.go
Labels: approved, lgtm, cncf-cla: yes, size/L, ok-to-test

#1350 [V2] fix: cache data loss issue on Windows when unmount disk
  pkg/azuredisk/azure_common_windows.go
  pkg/provisioner/nodeprovisioner_windows.go
  test/e2e/dynamic_provisioning_test.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#1367 chore: update max_disk_count table
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1366 feat: add controller.runOnControlPlane in chart config
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.19.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  test/external-e2e/run.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1368 fix: NodeGetVolumeStats failure on Windows node
  pkg/azuredisk/azure_common_darwin.go
  pkg/azuredisk/azure_common_linux.go
  pkg/azuredisk/azure_common_windows.go
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
  pkg/azuredisk/nodeserver_v2.go
  pkg/mounter/safe_mounter_v1beta_windows.go
  pkg/mounter/safe_mounter_windows.go
  test/external-e2e/run.sh
Labels: kind/bug, approved, cncf-cla: yes, size/L

#1372 doc: cut v1.19.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.19.0.tgz
  charts/v1.19.0/azuredisk-csi-driver-v1.19.0.tgz
  charts/v1.19.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.19.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.19.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.19.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.19.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.19.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.19.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/v1.19.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.19.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.19.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.19.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.19.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.19.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.19.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.19.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.19.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.19.0/azuredisk-csi-driver/values.yaml
  deploy/v1.19.0/crd-csi-snapshot.yaml
  deploy/v1.19.0/csi-azuredisk-controller.yaml
  deploy/v1.19.0/csi-azuredisk-driver.yaml
  deploy/v1.19.0/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.19.0/csi-azuredisk-node-windows.yaml
  deploy/v1.19.0/csi-azuredisk-node.yaml
  deploy/v1.19.0/csi-snapshot-controller.yaml
  deploy/v1.19.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.19.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.19.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.19.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1374 chore: switch master branch to use v1.20.0
  Makefile
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.19.0.tgz
  charts/latest/azuredisk-csi-driver-v1.20.0.tgz
  charts/latest/azuredisk-csi-driver/Chart.yaml
Labels: kind/documentation, size/M, approved, cncf-cla: yes

#1365 [V2] fix az-analyze tool and add docs
  Makefile
  cmd/az-analyze/README.md
  cmd/az-analyze/cmd/common.go
  cmd/az-analyze/cmd/root.go
  cmd/az-analyze/config/az-analyze.yaml
Labels: kind/bug, kind/documentation, size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1363 [V2] fix: Rename parameters passed during v2 initialization
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.4.tgz
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-controller.yaml
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/azuredisk_v2.go
Labels: approved, lgtm, cncf-cla: yes, size/L, kind/cleanup

#1377 feat: add affinity, nodeSelector in chart config
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.20.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1379 [V2] chore: Disable failing test
  test/e2e/dynamic_provisioning_test.go
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1382 [V2] chore: Remove dead code from azuredisk_v2.go
  pkg/azuredisk/azuredisk_v2.go
Labels: size/S, approved, lgtm, cncf-cla: yes, kind/cleanup

#1383 chore: remove unncessary vm provisioning and azdriver-node register from integration test
  test/integration/integration_test.go
  test/integration/register-azdrivernode.sh
  test/integration/run-test-v2.sh
  test/integration/run-tests-all-clouds.sh
Labels: size/M, approved, lgtm, cncf-cla: yes

#1386 feat: upgrade sidecar image versions
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.20.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1390 [V2] flake: Disable flakey tests
  test/e2e/dynamic_provisioning_test.go
Labels: kind/flake, size/XS, approved, cncf-cla: yes, kind/test

#1391 [V2] bug: replica deletion sometimes does not trigger manageReplica operation
  pkg/controller/replica.go
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes

#1381 fix: Put GetDiskLun log after it is called
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/cleanup

#1361 [V2] feat: update volume attachment with publish context upon attachment completion
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.4.tgz
  charts/latest-v2/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  deploy/latest-v2/rbac-csi-azuredisk-controller.yaml
  go.mod
  go.sum
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azureutils/azure_disk_utils.go
  pkg/controller/attach_detach.go
  pkg/controller/attach_detach_test.go
  pkg/controller/azvolume.go
  pkg/controller/azvolume_test.go
  pkg/controller/common.go
  pkg/controller/common_test.go
  pkg/controller/mockattachmentprovisioner/interface.go
  pkg/controller/pv.go
  pkg/controller/replica.go
  pkg/controller/volumeattachment.go
  pkg/controller/volumeattachment_test.go
  pkg/provisioner/cloudprovisioner.go
  pkg/provisioner/cloudprovisioner_test.go
  pkg/provisioner/crdprovisioner.go
  pkg/provisioner/crdprovisioner_test.go
  pkg/provisioner/fake_crdprovisioner.go
  test/integration/register-pv.sh
  test/integration/register-volumeattachment.sh
  test/integration/run-test-v2.sh
  test/integration/run-test.sh
  test/integration/wait-for-attach.sh
  test/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/batch/batch.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
Labels: kind/bug, approved, lgtm, cncf-cla: yes, size/XXL

#1389 [V2] feat: Skipping prioritize/(filter) extender processing for non-v2 disks
  pkg/azdiskschedulerextender/azdiskschedulerextender.go
  pkg/azdiskschedulerextender/azdiskschedulerextender_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#1395 [V2] fix: Fix for intermittent failure for NodeStageVolume request
  pkg/azuredisk/nodeserver_v2.go
Labels: size/S, approved, lgtm, cncf-cla: yes, ok-to-test

#1398 [V2] chore: Run serial external e2e tests sequentially
  test/external-e2e/run.sh
Labels: size/S, approved, lgtm, cncf-cla: yes, kind/cleanup, kind/test

#1399 [V2] fix: Fix CRI update on error recovery
  pkg/azureutils/azure_disk_utils.go
  pkg/controller/attach_detach.go
  pkg/controller/azvolume.go
  pkg/controller/pv.go
  pkg/controller/replica.go
  pkg/controller/volumeattachment.go
  pkg/provisioner/crdprovisioner.go
Labels: kind/bug, approved, cncf-cla: yes, size/L, kind/cleanup, kind/regression

#1401 [V2] fix: fix retry of failed attach
  pkg/provisioner/crdprovisioner.go
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes, kind/regression

#1400 chore: shorten userAgent
  pkg/azuredisk/version.go
  pkg/azuredisk/version_test.go
Labels: size/XS, approved, cncf-cla: yes, kind/cleanup

#1404 [V2] test: Ensure original pods exit before clone is mounted
  test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go
  test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
Labels: kind/flake, size/S, approved, cncf-cla: yes, kind/test

#1402 chore: switch to mcr oss/kubernetes-csi image
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.20.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  charts/v1.17.0/azuredisk-csi-driver-v1.17.0.tgz
  charts/v1.17.0/azuredisk-csi-driver/values.yaml
  charts/v1.18.0/azuredisk-csi-driver-v1.18.0.tgz
  charts/v1.18.0/azuredisk-csi-driver/values.yaml
  charts/v1.19.0/azuredisk-csi-driver-v1.19.0.tgz
  charts/v1.19.0/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/v1.17.0/csi-azuredisk-controller.yaml
  deploy/v1.17.0/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.17.0/csi-azuredisk-node-windows.yaml
  deploy/v1.17.0/csi-azuredisk-node.yaml
  deploy/v1.18.0/csi-azuredisk-controller.yaml
  deploy/v1.18.0/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.18.0/csi-azuredisk-node-windows.yaml
  deploy/v1.18.0/csi-azuredisk-node.yaml
  deploy/v1.19.0/csi-azuredisk-controller.yaml
  deploy/v1.19.0/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.19.0/csi-azuredisk-node-windows.yaml
  deploy/v1.19.0/csi-azuredisk-node.yaml
Labels: size/M, approved, cncf-cla: yes, kind/cleanup

#1396 [V2] chore: Merge master as of 2022-06-24
  charts/README.md
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.4.tgz
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-scheduler-extender.yaml
  charts/latest-v2/azuredisk-csi-driver/values.yaml
  charts/latest/azuredisk-csi-driver-v1.20.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  pkg/azuredisk/controllerserver.go
Labels: approved, cncf-cla: yes, size/L, kind/cleanup

#1405 [V2] flake: pod node selector test needs to wait long for pods on Windows
  test/e2e/testsuites/dynamically_provisioned_pod_node_selector.go
Labels: kind/flake, size/XS, approved, lgtm, cncf-cla: yes, kind/test

#1385 [V2] fix: ensure AzDriverNode recreated if deleted
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/azuredisk_v2_test.go
  pkg/azuredisk/fake_azuredisk_v2.go
  pkg/azuredisk/interface_v2.go
  pkg/azuredisk/mockprovisioner/interface.go
  pkg/provisioner/crdprovisioner.go
  pkg/provisioner/fake_crdprovisioner.go
  test/integration/controller/controller_test.go
Labels: kind/bug, size/XL, approved, lgtm, cncf-cla: yes
