Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2022-11, with the labels that each got.

#1569 [V2] chore: adding target to generate azure_dd_max_disk_count.go
  Makefile
  pkg/azureutils/azure_dd_max_disk_count.go
  pkg/tool/gen-disk-skus-map.go
Labels: approved, lgtm, cncf-cla: yes, size/XXL

#1572 [V2] feat: enable controller pod customization
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.8.tgz
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest-v2/azuredisk-csi-driver/values.yaml
Labels: kind/feature, size/M, approved, lgtm, cncf-cla: yes

#1573 [V2] chore: Add template for testing with cluster-autoscaler
  test/e2e/manifest/cluster-autoscaler.json
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test, kind/test

#1574 [V2]: Making qps and burst for csi attacher and provisioner configurable
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver/azuredisk-csi-driver-v2.0.0-beta.8.tgz
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest-v2/azuredisk-csi-driver/values.yaml
  deploy/latest-v2/csi-azuredisk-controller.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes

#1577 [V2] test: fix default artifacts directory
  Makefile
  test/const/test_consts.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/cleanup, kind/test

#1578 [v2] chore: increasing timeout for csi provisioner
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.9.tgz
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  deploy/latest-v2/csi-azuredisk-controller.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes

#1579 [V2] chore: fix CrdProvisioner.UnpublishVolume workflow result reporting
  pkg/provisioner/crdprovisioner.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/cleanup

#1580 [V2] fix: use correct context for delete of AzVolumeAttachment on detach
  pkg/controller/attach_detach.go
Labels: kind/bug, size/S, approved, lgtm, cncf-cla: yes

#1581 [V2] fix: cloud-provisioner should always report through result channel before returning
  pkg/provisioner/cloudprovisioner.go
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes

#1582 [V2] chore: reduce workflow logging verbosity
  pkg/azureutils/azure_disk_utils.go
  pkg/controller/attach_detach.go
  pkg/controller/azvolume.go
  pkg/controller/shared_state.go
  pkg/provisioner/crdprovisioner.go
Labels: size/S, approved, lgtm, cncf-cla: yes, kind/cleanup

#1584 [V2] chore: add missing cluster-autoscaler parameter to template
  test/e2e/manifest/cluster-autoscaler.json
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/cleanup, ok-to-test

#1564 Incorporating the VMSSVM cache changes from cloud-provider-azure lib
  go.mod
  go.sum
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/RELEASING.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/mockvmssvmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/cache/azure_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/nodemanager/nodemanager.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmssflex.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_mock_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmssflex.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmssflex_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/util/deepcopy/deepcopy.go
Labels: size/XL, approved, lgtm, cncf-cla: yes, ok-to-test

#1557 [V2] fix: replicas aren't getting cleaned up during driver uninstall
  pkg/controller/azdrivernode.go
  pkg/controller/azvolume.go
  pkg/controller/common.go
  pkg/controller/shared_state.go
Labels: approved, lgtm, cncf-cla: yes, size/L

#1588 [V2] fix: image tag in beta8 charts was still pointing to latest-v2
  charts/index.yaml
  charts/v2.0.0-beta.8/azuredisk-csi-driver-v2.0.0-beta.8.tgz
  charts/v2.0.0-beta.8/azuredisk-csi-driver/values.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes

#1593 [V2] chore: increase CAS node provisioning timeout
  test/e2e/manifest/cluster-autoscaler.json
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/cleanup, ok-to-test

#1597 cleanup: remove unused install docs
  docs/install-csi-driver-v0.10.0.md
  docs/install-csi-driver-v0.2.0.md
  docs/install-csi-driver-v0.3.0.md
  docs/install-csi-driver-v0.4.0.md
  docs/install-csi-driver-v0.5.0.md
  docs/install-csi-driver-v0.6.0.md
  docs/install-csi-driver-v0.7.0.md
  docs/install-csi-driver-v0.8.0.md
  docs/install-csi-driver-v0.9.0.md
Labels: approved, lgtm, cncf-cla: yes, size/L, kind/cleanup

#1598 [V2] fix: requeue reconciliation for deleted objects with grace period
  pkg/controller/attach_detach.go
  pkg/controller/azvolume.go
  pkg/controller/common.go
  pkg/controller/pv.go
  pkg/controller/shared_state.go
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes

#1596 feat: support perf profile device setting on Linux node
  README.md
  docs/driver-parameters.md
  docs/perf-profiles.md
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
  pkg/azuredisk/nodeserver_v2.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
  pkg/optimization/device_perf.go
  pkg/optimization/device_perf_helper.go
  pkg/optimization/device_perf_helper_test.go
  pkg/optimization/device_perf_linux.go
  pkg/optimization/device_perf_linux_test.go
  pkg/optimization/device_perf_test.go
  pkg/optimization/device_perf_unsupported.go
  pkg/optimization/mockoptimization/interface.go
  test/e2e/dynamic_provisioning_test.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes

#1601 fix: panic in vmss cache conversion
  go.mod
  go.sum
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/internal/gomega.go
  vendor/github.com/onsi/gomega/types/types.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/headermap.go
  vendor/golang.org/x/net/http2/hpack/static_table.go
  vendor/golang.org/x/net/http2/hpack/tables.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/sockcmsg_unix.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmssflex.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmssflex_cache.go
Labels: kind/bug, size/XL, approved, cncf-cla: yes

#1602 test: set disk perf in PremiumV2 test
  test/e2e/pre_provisioning_test.go
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1595 [V2] fix: add nodeDiskAvailabilityMap
  pkg/controller/attach_detach.go
  pkg/controller/attach_detach_test.go
  pkg/controller/azdrivernode.go
  pkg/controller/azdrivernode_test.go
  pkg/controller/common.go
  pkg/controller/common_test.go
  pkg/controller/node_availability_test.go
  pkg/controller/pod_test.go
  pkg/controller/replica_test.go
  pkg/controller/shared_state.go
  pkg/controller/shared_state_test.go
Labels: approved, lgtm, cncf-cla: yes, size/L, ok-to-test

#1586 [V2] chore: adding flow chart documentation for V2 driver csi calls
  docs/azure-disk-v2-driver-design/create-volume-csi-workflow.md
  docs/azure-disk-v2-driver-design/create-volume-static-provisioning.md
  docs/azure-disk-v2-driver-design/delete-volume-csi-workflow.md
  docs/azure-disk-v2-driver-design/delete-volume-static-provisioning.md
  docs/azure-disk-v2-driver-design/publish-volume-csi-workflow.md
  docs/azure-disk-v2-driver-design/replica-creation-workflow.md
  docs/azure-disk-v2-driver-design/unpublish-volume-csi-workflow.md
  pkg/provisioner/crdprovisioner.go
Labels: approved, lgtm, cncf-cla: yes, size/L

#1609 [chore] Fix E2E failure in VMSS Flex cluster
  Makefile
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes, ok-to-test, kind/test

#1585 test: use `T.Setenv` to set env vars in tests
  pkg/azuredisk/azuredisk_test.go
  pkg/azureutils/azure_disk_utils_test.go
  test/integration/integration_test.go
  test/sanity/sanity_test.go
  test/utils/credentials/credentials_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes, kind/cleanup, ok-to-test

#1613 fix: support noProxy in chart config
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
Labels: kind/bug, size/S, approved, lgtm, cncf-cla: yes, ok-to-test

#1610 fix: add disk lun check in AttachDisk to avoid race condition
  go.mod
  go.sum
  vendor/github.com/Azure/azure-sdk-for-go/version/version.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_utils.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#1611 fix: reduce VMSS cache refresh
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_utils.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss_cache.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1604 doc: cut v1.25.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/v1.25.0/azuredisk-csi-driver-v1.25.0.tgz
  charts/v1.25.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.25.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.25.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.25.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.25.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.25.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.25.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/v1.25.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.25.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.25.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.25.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.25.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.25.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.25.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.25.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.25.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.25.0/azuredisk-csi-driver/values.yaml
  deploy/v1.25.0/crd-csi-snapshot.yaml
  deploy/v1.25.0/csi-azuredisk-controller.yaml
  deploy/v1.25.0/csi-azuredisk-driver.yaml
  deploy/v1.25.0/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.25.0/csi-azuredisk-node-windows.yaml
  deploy/v1.25.0/csi-azuredisk-node.yaml
  deploy/v1.25.0/csi-snapshot-controller.yaml
  deploy/v1.25.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.25.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.25.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.25.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1620 Clean up .travis.yaml
  .travis.yml
Labels: size/S, approved, lgtm, cncf-cla: yes, kind/cleanup, ok-to-test

#1622 fix: volume metrics on Windows csi-proxy v1beta
  pkg/mounter/safe_mounter_v1beta_windows.go
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes

#1624 Test: Adding a new test to verify volume and nodes in different resource groups
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_external_rg_volume_tester.go
Labels: approved, lgtm, cncf-cla: yes, size/L, ok-to-test

#1621 chore: Update the VMSSVMCache struct vendor to csi driver
  go.mod
  go.sum
  vendor/golang.org/x/sync/LICENSE
  vendor/golang.org/x/sync/PATENTS
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/azure_armclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer_backendpool.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_mock_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_utils.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmssflex.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_wrap.go
Labels: size/XL, approved, lgtm, cncf-cla: yes, ok-to-test

#1626 [V2] chore: fix addition of details after creation
  pkg/workflow/workflow.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/cleanup

#1623 [V2] chore: increase max watch duration on CAS cluster
  test/e2e/manifest/cluster-autoscaler.json
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/cleanup, ok-to-test

#1627 [V2] feat: enable configuration of CRD controller worker threads
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.9.tgz
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest-v2/azuredisk-csi-driver/values.yaml
  deploy/latest-v2/csi-azuredisk-controller.yaml
  pkg/apis/azuredisk/v1beta2/types.go
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azurediskplugin/main.go
  pkg/controller/attach_detach.go
  pkg/controller/azdrivernode.go
  pkg/controller/azvolume.go
  pkg/controller/azvolume_test.go
  pkg/controller/common.go
  pkg/controller/common_test.go
  pkg/controller/node_availability.go
  pkg/controller/pod.go
  pkg/controller/pv.go
  pkg/controller/pv_test.go
  pkg/controller/replica.go
  pkg/controller/shared_state.go
  pkg/controller/volumeattachment.go
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/L
