Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2022-12, with the labels that each got.

#1625 [V2] fix: update PV controller's Recover function to log the error
  go.mod
  pkg/controller/pv.go
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1629 chore: upgrade sidecar container images
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/feature, size/M, approved, lgtm, cncf-cla: yes

#1612 [V2] refactor: combine azdrivernode and node_availability into one controller
  pkg/azuredisk/azuredisk_v2.go
  pkg/controller/node.go
  pkg/controller/node_availability.go
  pkg/controller/node_availability_test.go
  pkg/controller/node_test.go
Labels: approved, lgtm, cncf-cla: yes, size/L, kind/cleanup, ok-to-test

#1630 [V2] chore: upgrade cloud-provider-azure as of 2022-11-30
  go.mod
  go.sum
  pkg/provisioner/cloudprovisioner_test.go
  vendor/github.com/Azure/azure-sdk-for-go/version/version.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/RELEASING.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/internal/gomega.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/types/types.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/headermap.go
  vendor/golang.org/x/net/http2/hpack/static_table.go
  vendor/golang.org/x/net/http2/hpack/tables.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/golang.org/x/sys/unix/sockcmsg_unix.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/term/terminal.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
  vendor/k8s.io/cloud-provider/node/helpers/taints.go
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
  vendor/k8s.io/kubernetes/pkg/volume/util/util.go
  vendor/k8s.io/kubernetes/test/e2e/framework/nodes_util.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/azure_armclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/mockvmssvmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/batch/batch.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/cache/azure_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/metrics/azure_batch_metrics.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/nodemanager/nodemanager.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmssflex.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_fakes.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer_backendpool.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_mock_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_utils.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmssflex.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmssflex_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_wrap.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/mockfutureparser.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/retry/azure_error.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/util/deepcopy/deepcopy.go
Labels: approved, lgtm, cncf-cla: yes, size/XXL, kind/cleanup

#1632 fix: add disk lun check in VMSSFlex AttachDisk to avoid race condition
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmssflex.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_utils.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1615 [V2] fix: delete orphaned azdrivernode and update error logs in Recover function
  pkg/azuredisk/azuredisk_v2.go
  pkg/azureutils/azure_disk_utils.go
  pkg/controller/common_test.go
  pkg/controller/node.go
  pkg/controller/node_test.go
Labels: kind/bug, approved, lgtm, cncf-cla: yes, size/L, ok-to-test

#1634 chore: increase csi-provisioner timeout to 30s
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1637 [V2] fix: revert cloud-provider-azure 2022-11-30 changes
  go.mod
  go.sum
  pkg/provisioner/cloudprovisioner_test.go
  vendor/github.com/Azure/azure-sdk-for-go/version/version.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/RELEASING.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/internal/gomega.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/types/types.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/headermap.go
  vendor/golang.org/x/net/http2/hpack/static_table.go
  vendor/golang.org/x/net/http2/hpack/tables.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/golang.org/x/sys/unix/sockcmsg_unix.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/term/terminal.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
  vendor/k8s.io/cloud-provider/node/helpers/taints.go
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
  vendor/k8s.io/kubernetes/pkg/volume/util/util.go
  vendor/k8s.io/kubernetes/test/e2e/framework/nodes_util.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/azure_armclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/mockvmssvmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/batch/batch.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/cache/azure_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/metrics/azure_batch_metrics.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/nodemanager/nodemanager.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmssflex.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_fakes.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer_backendpool.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_mock_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_utils.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmssflex.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmssflex_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_wrap.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/mockfutureparser.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/retry/azure_error.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/util/deepcopy/deepcopy.go
Labels: kind/bug, approved, lgtm, cncf-cla: yes, size/XXL, kind/regression

#1639 fix: race condition in VMSS cache update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer_backendpool.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss_cache.go
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes

#1641 fix: Add missing machine in SKU listings
  pkg/optimization/azure_skus_map.go
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#1644 Update node_availability.go to node.go
  docs/azure-disk-v2-driver-design/replica-creation-workflow.md
Labels: kind/documentation, size/XS, needs-ok-to-test, approved, lgtm, cncf-cla: yes, kind/cleanup

#1645 [V2] chore: increase azuredisk kubeclient QPS
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.9.tgz
  charts/latest-v2/azuredisk-csi-driver/values.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes, kind/cleanup

#1633 [V2] perf: changed to use channel to communicate when delete azvolume
  pkg/controller/azvolume.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1607 [V2] refactor: start informers in one place
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/interface_v2.go
  pkg/azuredisk/mockprovisioner/interface.go
  pkg/azureutils/informer_common.go
  pkg/controller/common_test.go
  pkg/controller/shared_state.go
  pkg/provisioner/crdprovisioner.go
  pkg/provisioner/crdprovisioner_test.go
  pkg/watcher/conditionwatcher.go
  test/integration/controller/controller_test.go
Labels: size/XL, approved, lgtm, cncf-cla: yes, kind/cleanup, ok-to-test

#1646 [V2] chore: remove unneeded error return from NewConditionWaiter
  pkg/controller/azvolume.go
  pkg/controller/replica.go
  pkg/provisioner/crdprovisioner.go
  pkg/watcher/conditionwatcher.go
Labels: size/M, approved, lgtm, cncf-cla: yes, kind/cleanup

#1649 [V2] fix: don't return unncessary error in crdProvisioner.CreateVolume
  pkg/provisioner/crdprovisioner.go
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes

#1655 [V2] fix: CVE-2022-47417
  .github/workflows/codeql-analysis.yml
  .github/workflows/darwin.yaml
  .github/workflows/linux-v2.yml
  .github/workflows/linux.yml
  .github/workflows/trivy-v2.yaml
  .github/workflows/trivy.yaml
  .github/workflows/windows-v2.yml
  .github/workflows/windows.yml
  go.mod
  go.sum
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/headermap.go
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/hpack/static_table.go
  vendor/golang.org/x/net/http2/hpack/tables.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/execabs/execabs_go119.go
  vendor/golang.org/x/sys/unix/sockcmsg_unix.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: size/XL, approved, cncf-cla: yes

#1652 Add requirements.txt with fixed versions to use in pip install
  hack/requirements.txt
  hack/verify-helm-chart.sh
Labels: size/M, approved, lgtm, cncf-cla: yes, kind/cleanup

#1656 fix: CVE-2022-41717
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, cncf-cla: yes, size/L

#1654 [V2] chore: update cloud-provider-azure
  go.mod
  go.sum
  pkg/provisioner/cloudprovisioner_test.go
  vendor/github.com/Azure/azure-sdk-for-go/version/version.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/RELEASING.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/internal/gomega.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/types/types.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/azure_armclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmclient/azure_vmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/mockvmssvmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/batch/batch.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/cache/azure_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/metrics/azure_batch_metrics.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/nodemanager/nodemanager.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmssflex.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_fakes.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer_backendpool.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_mock_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_utils.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmssflex.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmssflex_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_wrap.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/mockfutureparser.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/retry/azure_error.go
Labels: approved, lgtm, cncf-cla: yes, size/XXL, kind/cleanup

#1657 [V2] feat: add optional pprof server
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.9.tgz
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-scheduler-extender.yaml
  charts/latest-v2/azuredisk-csi-driver/values.yaml
  docs/csi-debug.md
  pkg/apis/azuredisk/v1beta2/types.go
  pkg/azdiskschedulerextender/main.go
  pkg/azureconstants/azure_constants.go
  pkg/azurediskplugin/main.go
  pkg/profiler/profiler.go
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/L

#1653 [V2] fix: make recover annotation unique per recovery
  pkg/azuredisk/azuredisk_v2.go
  pkg/controller/attach_detach.go
  pkg/controller/attach_detach_test.go
  pkg/controller/azvolume.go
  pkg/controller/azvolume_test.go
  pkg/controller/node.go
  pkg/controller/node_test.go
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1599 [V2] fix: handle pre-provisioned volume deletion at the right time
  pkg/azureutils/azure_disk_utils.go
  pkg/controller/attach_detach.go
  pkg/controller/azvolume.go
  pkg/controller/common.go
  pkg/controller/common_test.go
  pkg/controller/node.go
  pkg/controller/pod_test.go
  pkg/controller/pv.go
  pkg/controller/pv_test.go
  pkg/controller/shared_state.go
Labels: approved, lgtm, cncf-cla: yes, size/L, kind/cleanup

#1663 [V2] fix: clear status error and detail in AzVolumeAttachment recovery if in in Attaching state 🐞
  pkg/controller/attach_detach.go
  pkg/controller/attach_detach_test.go
Labels: kind/bug, size/S, approved, lgtm, cncf-cla: yes, ok-to-test

#1669 Revert "fix e2e: disable podSecurity"
  test/e2e/manifest/migration-windows.json
  test/e2e/manifest/migration.json
  test/e2e/manifest/multi-az.json
  test/e2e/manifest/single-az.json
Labels: size/S, approved, cncf-cla: yes

#1658 [V2] feat: toggle for waitforlun
  .gitignore
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.10.tgz
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest-v2/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  pkg/apis/azuredisk/v1beta2/types.go
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azurediskplugin/main.go
  pkg/provisioner/crdprovisioner.go
  pkg/provisioner/crdprovisioner_test.go
  test/integration/controller/controller_test.go
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/L, ok-to-test

#1670 [V2] fix: changing scheduler name logic to install method
  test/podFailover/workload/chart/templates/workload.yaml
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#1643 feat: add disable-update-cache flag
  go.mod
  go.sum
  pkg/azuredisk/azuredisk.go
  pkg/azurediskplugin/main.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmssflex.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_utils.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmssflex_cache.go
Labels: kind/feature, approved, cncf-cla: yes, size/L

#1674 test: add helm lint test
  hack/verify-helm-chart.sh
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#1671 [V2] Fix: update uninstall path in crdProvisioner.DeleteVolume
  pkg/controller/shared_state.go
  pkg/provisioner/crdprovisioner.go
Labels: kind/bug, size/S, approved, lgtm, cncf-cla: yes, ok-to-test
