Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2022-07, with the labels that each got.

#1407 chore: set master branch chart version to v0.0.0
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver-v1.20.0.tgz
  charts/latest/azuredisk-csi-driver/Chart.yaml
Labels: kind/documentation, size/M, approved, cncf-cla: yes

#1409 chore: update max data disk count table
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1413 chore: increase node-registrar cpu requests on Windows
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  pkg/azurediskplugin/Dockerfile
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1411 [V2] bug: scale test regression fix
  pkg/azureconstants/azure_constants.go
  pkg/azureutils/azure_disk_utils.go
  pkg/controller/attach_detach.go
  pkg/controller/attach_detach_test.go
  pkg/controller/azvolume.go
  pkg/controller/common.go
  pkg/controller/pv.go
  pkg/controller/replica.go
  pkg/controller/volumeattachment.go
  pkg/controller/volumeattachment_test.go
  pkg/provisioner/cloudprovisioner.go
  pkg/provisioner/crdprovisioner.go
  pkg/provisioner/crdprovisioner_test.go
  pkg/watcher/conditionwaiter.go
  pkg/watcher/conditionwatcher.go
  pkg/workflow/workflow.go
  test/integration/run-test.sh
Labels: size/XL, approved, lgtm, cncf-cla: yes, kind/regression

#1417 [V2] test: adding flag for replicas to run scale tests
  test/scale/azdisk_scale_test.go
  test/scale/flags.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test, kind/test

#1418 fix: CSI function should return internal error
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_v2.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1422 chore: switch master branch to use v1.21.0
  Makefile
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#1406 [V2] feat: allow detaches of replica attachment for primary attachment
  pkg/azdiskschedulerextender/azdiskschedulerextender.go
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azureutils/azure_disk_utils.go
  pkg/controller/attach_detach.go
  pkg/controller/attach_detach_test.go
  pkg/controller/azdrivernode.go
  pkg/controller/azvolume.go
  pkg/controller/common.go
  pkg/controller/common_test.go
  pkg/controller/replica.go
  pkg/provisioner/cloudprovisioner_test.go
  pkg/provisioner/crdprovisioner.go
  pkg/provisioner/crdprovisioner_test.go
  test/e2e/testsuites/azdiskschedulerextender_pod_scheduling_on_failover_multiple_pv_perf_tester.go
  test/e2e/testsuites/dynamically_provisioned_garbage_collection_replica_attachment_tester.go
  test/e2e/testsuites/dynamically_provisioned_pod_failover_with_replicas_tester.go
  test/e2e/testsuites/dynamically_provisioned_pod_scale_up_with_replicas.go
  test/integration/controller/controller_test.go
  test/resources/utils.go
Labels: approved, lgtm, cncf-cla: yes, size/XXL

#1428 doc: cut v1.21.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/v1.21.0/azuredisk-csi-driver-v1.21.0.tgz
  charts/v1.21.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.21.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.21.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.21.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.21.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.21.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.21.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/v1.21.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.21.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.21.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.21.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.21.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.21.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.21.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.21.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.21.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.21.0/azuredisk-csi-driver/values.yaml
  deploy/v1.21.0/crd-csi-snapshot.yaml
  deploy/v1.21.0/csi-azuredisk-controller.yaml
  deploy/v1.21.0/csi-azuredisk-driver.yaml
  deploy/v1.21.0/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.21.0/csi-azuredisk-node-windows.yaml
  deploy/v1.21.0/csi-azuredisk-node.yaml
  deploy/v1.21.0/csi-snapshot-controller.yaml
  deploy/v1.21.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.21.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.21.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.21.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1430 chore: switch master branch to use v1.22.0
  Makefile
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#1431 chore: add node-role.kubernetes.io/control-plane to csi-snapshot-controller
  deploy/csi-snapshot-controller.yaml
Labels: kind/documentation, size/XS, approved, lgtm, cncf-cla: yes

#1380 [V2]feat: replace command line params with config file
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.5.tgz
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/latest-v2/azuredisk-csi-driver/values.yaml
  charts/latest/azuredisk-csi-driver-v1.20.0.tgz
  pkg/apis/azuredisk/v1beta2/types.go
  pkg/apis/azuredisk/v1beta2/zz_generated.deepcopy.go
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v1.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/fake_azuredisk_v2.go
  pkg/azurediskplugin/main.go
Labels: kind/feature, do-not-merge/hold, size/XL, approved, lgtm, cncf-cla: yes, ok-to-test

#1434 chore: gofmt 1.19 fixes
  pkg/apis/client/clientset/versioned/fake/register.go
  pkg/apis/client/clientset/versioned/scheme/register.go
  pkg/azdiskschedulerextender/azdiskschedulerextender_test.go
  pkg/azureutils/azure_disk_utils.go
  pkg/controller/attach_detach.go
  pkg/controller/azvolume.go
  pkg/controller/common.go
  pkg/controller/pod.go
  pkg/controller/pv.go
  pkg/controller/volumeattachment.go
  pkg/mounter/safe_mounter_v1beta_windows.go
  pkg/mounter/safe_mounter_windows.go
  pkg/optimization/skus.go
  test/e2e/testsuites/dynamically_provisioned_pod_affinity.go
  test/e2e/testsuites/dynamically_provisioned_pod_failover_tester.go
  test/e2e/testsuites/dynamically_provisioned_pod_failover_with_replicas_tester.go
  test/e2e/testsuites/dynamically_provisioned_pod_node_affinity.go
  test/e2e/testsuites/dynamically_provisioned_pod_node_selector.go
  test/e2e/testsuites/dynamically_provisioned_pod_scale_up_with_replicas.go
  test/e2e/testsuites/dynamically_provisioned_pod_toleration.go
Labels: approved, lgtm, cncf-cla: yes, size/L, kind/cleanup

#1410 [V2] feat: add rate limiter latency metric to find throttling
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/azuredisk_v2.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1433 [V2] test: add junit test output to scale test 🔧
  test/scale/scale_test.go
Labels: size/XS, cncf-cla: yes, ok-to-test

#1436 chore: gofmt 1.19 fixes
  pkg/azureutils/azure_disk_utils.go
  pkg/mounter/safe_mounter_v1beta_windows.go
  pkg/mounter/safe_mounter_windows.go
  pkg/optimization/skus.go
  test/e2e/testsuites/dynamically_provisioned_pod_failover_tester.go
Labels: approved, lgtm, cncf-cla: yes, size/L, kind/cleanup

#1439 test: Wait longer for colocated pods to start
  test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/test
