Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2023-04, with the labels that each got.

#1802 fix: fix attach failure panic
  pkg/controller/attach_detach.go
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes

#1805 fix: add securityContext.seccompProfile for driver controller
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1806 feat: add chart config value enableRegistrationProbe
  Makefile
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  test/utils/azuredisk_log.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1809 test(e2e): change the storageclass configuration method in the test file
  deploy/example/statefulset-nonroot.yaml
  deploy/example/statefulset-nozone.yaml
  deploy/example/statefulset.yaml
  deploy/example/windows/statefulset.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes, ok-to-test

#1808 [V2] fix: Fix pod failover ready
  test/podFailover/controller/cmd/main.go
Labels: kind/bug, size/S, lgtm, cncf-cla: yes, ok-to-test

#1812 [release-1.26] test: fix external e2e test failure
  test/external-e2e/run.sh
  test/utils/azuredisk_log.sh
Labels: size/S, kind/failing-test, approved, cncf-cla: yes

#1814 cleanup: replace deprecated ioutil method
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_v2.go
  pkg/azureutils/azure_disk_utils_test.go
  pkg/azureutils/fake_iohandler.go
  pkg/azureutils/fake_iohandler_test.go
  pkg/azureutils/osiohandler.go
  pkg/mounter/fake_safe_mounter_test.go
  pkg/tool/gen-disk-skus-map.go
  test/utils/credentials/credentials.go
  test/utils/credentials/credentials_test.go
Labels: approved, lgtm, cncf-cla: yes, size/L, kind/cleanup, ok-to-test

#1817 [V2] fix: update handleReplicaDelete function in replica controller
  pkg/controller/replica.go
Labels: kind/bug, size/S, approved, lgtm, cncf-cla: yes, ok-to-test

#1818 chore: update max data disk num table
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/feature, size/S, approved, cncf-cla: yes
