Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2023-09, with the labels that each got.

#1955 chore: update max data disk count table
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#1956 feat: enable HonorPVReclaimPolicy in csi-provisioner
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-controller.yaml
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#1962 doc: cut v1.29.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/v1.29.0/azuredisk-csi-driver-v1.29.0.tgz
  charts/v1.29.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.29.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.29.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.29.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.29.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.29.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.29.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/v1.29.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.29.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.29.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.29.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.29.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.29.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.29.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.29.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.29.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.29.0/azuredisk-csi-driver/values.yaml
  deploy/v1.29.0/crd-csi-snapshot.yaml
  deploy/v1.29.0/csi-azuredisk-controller.yaml
  deploy/v1.29.0/csi-azuredisk-driver.yaml
  deploy/v1.29.0/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.29.0/csi-azuredisk-node-windows.yaml
  deploy/v1.29.0/csi-azuredisk-node.yaml
  deploy/v1.29.0/csi-snapshot-controller.yaml
  deploy/v1.29.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.29.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.29.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.29.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1965 cleanup: refine Volume capabilities not supported error
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
  pkg/azuredisk/nodeserver_v2.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
Labels: size/M, approved, cncf-cla: yes, kind/cleanup

#1973 chore: refine create-volume metrics
  pkg/azuredisk/controllerserver.go
Labels: size/XS, approved, cncf-cla: yes, kind/cleanup

#1953 fix: Ultra and PremiumV2 disk snapshot delay issue
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azurediskplugin/main.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1979 fix: increase snapshot timeout to 20min
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-controller.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#1983 [release-1.28] fix: increase snapshot timeout to 20min
  charts/latest/azuredisk-csi-driver-v1.28.3.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-controller.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#1984 [release-1.28] fix: Ultra and PremiumV2 disk snapshot delay issue
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azurediskplugin/main.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1982 [release-1.29] fix: increase snapshot timeout to 20min
  charts/latest/azuredisk-csi-driver-v1.29.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-controller.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#1950 fix: allow resizing to min required size for performance plus disks
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
Labels: kind/bug, kind/feature, approved, lgtm, cncf-cla: yes, size/L
