Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2023-07, with the labels that each got.

#1901 cleanup: update new chart versions and remove deprecated versions
  README.md
  charts/index.yaml
  charts/v1.28.0/azuredisk-csi-driver-v1.28.0.tgz
  charts/v1.28.1/azuredisk-csi-driver-v1.28.1.tgz
  charts/v1.28.1/azuredisk-csi-driver/Chart.yaml
  charts/v1.28.1/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.28.1/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.28.1/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.28.1/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.28.1/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.28.1/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/v1.28.1/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.28.1/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.28.1/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.28.1/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.28.1/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.28.1/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.28.1/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.28.1/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.28.1/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.28.1/azuredisk-csi-driver/values.yaml
  deploy/v1.28.1/crd-csi-snapshot.yaml
  deploy/v1.28.1/csi-azuredisk-controller.yaml
  deploy/v1.28.1/csi-azuredisk-driver.yaml
  deploy/v1.28.1/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.28.1/csi-azuredisk-node-windows.yaml
  deploy/v1.28.1/csi-azuredisk-node.yaml
  deploy/v1.28.1/csi-snapshot-controller.yaml
  deploy/v1.28.1/rbac-csi-azuredisk-controller.yaml
  deploy/v1.28.1/rbac-csi-azuredisk-node.yaml
  deploy/v1.28.1/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.28.1.md
Labels: kind/documentation, approved, cncf-cla: yes, size/L

#1903 chore: update max data disk number table
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1902 cleanup: use InClusterConfig by default on Windows node
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
Labels: size/XS, approved, cncf-cla: yes, kind/cleanup

#1911 [V2] fix: fix segfault due to empty operation queue
  pkg/controller/common.go
  pkg/controller/shared_state.go
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes

#1912 feat: add otel trace instrumentation on gRPC calls in helm chart
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  go.mod
  go.sum
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/trace.go
  pkg/azurediskplugin/main.go
  pkg/csi-common/server.go
  pkg/csi-common/server_test.go
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/L, ok-to-test

#1909 fix: cloned volume could not be recognized on Windows node when source volume is mounted on the same node
  pkg/mounter/safe_mounter_host_process_windows.go
  pkg/os/disk/disk.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go
Labels: kind/bug, size/M, approved, cncf-cla: yes
