Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2023-01, with the labels that each got.

#1665 cleanup: Use k8s utils pointer instead of Azure autorest/to
  go.mod
  pkg/azuredisk/controllerserver_test.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
  test/e2e/testsuites/testsuites.go
  test/utils/azure/azure_helpers.go
Labels: size/M, approved, lgtm, cncf-cla: yes, kind/cleanup, ok-to-test

#1676 fix: set ForceAttemptHTTP2 as false to increase ARM throttling limit
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/azure_armclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/config/azure_ratelimit.go
Labels: approved, cncf-cla: yes, size/L

#1681 doc: cut v1.26.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/v1.26.0/azuredisk-csi-driver-v1.26.0.tgz
  charts/v1.26.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.26.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.26.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.26.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.26.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.26.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.26.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/v1.26.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.26.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.26.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.26.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.26.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.26.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.26.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.26.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.26.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.26.0/azuredisk-csi-driver/values.yaml
  deploy/v1.26.0/crd-csi-snapshot.yaml
  deploy/v1.26.0/csi-azuredisk-controller.yaml
  deploy/v1.26.0/csi-azuredisk-driver.yaml
  deploy/v1.26.0/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.26.0/csi-azuredisk-node-windows.yaml
  deploy/v1.26.0/csi-azuredisk-node.yaml
  deploy/v1.26.0/csi-snapshot-controller.yaml
  deploy/v1.26.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.26.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.26.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.26.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1680 [V2] fix: azvolume recovery bug fix - status update, parameter parsing
  pkg/azuredisk/controllerserver.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
  pkg/controller/shared_state.go
  pkg/provisioner/cloudprovisioner.go
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes

#1684 cleanup: remove useless storage class yaml files
  deploy/example/storageclass-azuredisk-csi-large-scale.yaml
  deploy/example/storageclass-azuredisk-csi-topology.yaml
Labels: size/S, approved, cncf-cla: yes, kind/cleanup

#1679 [V2]fix: update predicate function of node controller
  pkg/controller/node.go
  pkg/controller/shared_state.go
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1688 doc: cut v1.26.1 release
  Makefile
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/v1.26.1/azuredisk-csi-driver-v1.26.1.tgz
  charts/v1.26.1/azuredisk-csi-driver/Chart.yaml
  charts/v1.26.1/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.26.1/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.26.1/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.26.1/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.26.1/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.26.1/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/v1.26.1/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.26.1/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.26.1/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.26.1/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.26.1/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.26.1/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.26.1/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.26.1/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.26.1/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.26.1/azuredisk-csi-driver/values.yaml
  deploy/v1.26.1/crd-csi-snapshot.yaml
  deploy/v1.26.1/csi-azuredisk-controller.yaml
  deploy/v1.26.1/csi-azuredisk-driver.yaml
  deploy/v1.26.1/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.26.1/csi-azuredisk-node-windows.yaml
  deploy/v1.26.1/csi-azuredisk-node.yaml
  deploy/v1.26.1/csi-snapshot-controller.yaml
  deploy/v1.26.1/rbac-csi-azuredisk-controller.yaml
  deploy/v1.26.1/rbac-csi-azuredisk-node.yaml
  deploy/v1.26.1/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.26.1.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1677 [V2] fix: make uninstallation compatible with backload DELETE change
  pkg/controller/common.go
  pkg/controller/shared_state.go
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes

#1638 test: add external stress e2e tests
  test/external-e2e/manifest/testdriver.yaml
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1692 [V2] fix: update uninstallation path in replica.go
  pkg/controller/replica.go
Labels: kind/bug, size/S, approved, lgtm, cncf-cla: yes, ok-to-test

#1693 [V2] fix: prevent requesting replica attachment in a row for one volume
  pkg/controller/common.go
  pkg/controller/replica.go
  pkg/controller/shared_state.go
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1691 [V2] fix: only count replica attachments w/t deletion timestamp from cache client
  pkg/azuredisk/azuredisk_v2.go
  pkg/controller/shared_state.go
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1698 [V2] fix: only initialize perf optimization on node driver
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.11.tgz
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  pkg/azuredisk/azuredisk_v2.go
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes, kind/regression

#1678 [V2] feat: add PowerShell module for log/operation analysis
  docs/csi-debug.md
  hack/AzureDiskCSIDriver.psd1
  hack/AzureDiskCSIDriver.psm1
  hack/boilerplate/boilerplate.psd1.txt
  hack/boilerplate/boilerplate.psm1.txt
Labels: size/XL, approved, lgtm, cncf-cla: yes

#1695 [V2] fix: update logic to get correct nodes for creating replica attachments
  pkg/controller/shared_state.go
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#1703 Add missing v5 D & E SKUs to map
  pkg/optimization/azure_skus_map.go
Labels: kind/bug, approved, lgtm, cncf-cla: yes, size/L, ok-to-test

#1699 fix: panic when allow-empty-cloud-config is set
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azuredisk/fake_azuredisk_v2.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1704 fix: switch base image to fix CVEs
  pkg/azurediskplugin/Dockerfile
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#1700 [V2] refactor: relocate getVolumeCapabilityFromPv
  pkg/controller/azvolume.go
  pkg/controller/shared_state.go
Labels: size/M, approved, lgtm, cncf-cla: yes, kind/cleanup, ok-to-test
