Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2023-10, with the labels that each got.

#1981 fix: ensure Kubernets conformant format for location
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
Labels: kind/bug, size/S, approved, lgtm, cncf-cla: yes, ok-to-test

#1995 doc: fix code spelling errors
  .github/workflows/codespell.yml
  deploy/example/azure.json
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#1998 [release-1.27] doc: fix code spelling errors
  .github/workflows/codespell.yml
  deploy/example/azure.json
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#1997 [release-1.28] doc: fix code spelling errors
  .github/workflows/codespell.yml
  deploy/example/azure.json
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#1996 [release-1.29] doc: fix code spelling errors
  .github/workflows/codespell.yml
  deploy/example/azure.json
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#1994 [release-1.27] fix: upgrade mount-utils lib
  go.mod
  go.sum
  vendor/k8s.io/mount-utils/mount.go
  vendor/k8s.io/mount-utils/mount_linux.go
  vendor/k8s.io/mount-utils/mount_windows.go
  vendor/k8s.io/utils/exec/testing/fake_exec.go
  vendor/k8s.io/utils/lru/lru.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/L

#1993 [release-1.28] fix: upgrade mount-utils lib
  go.mod
  go.sum
  vendor/k8s.io/mount-utils/mount.go
  vendor/k8s.io/mount-utils/mount_linux.go
  vendor/k8s.io/mount-utils/mount_windows.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/L

#1999 test: skip anti-affinity in hpc deployment test
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
Labels: size/XS, approved, cncf-cla: yes, kind/test

#2001 test: fix verify-helm-chart failure
  hack/verify-helm-chart.sh
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#2014 cleanup: fix k8s.io/endpointslice dependency
  go.mod
  hack/verify-gomod.sh
  vendor/modules.txt
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#2016 doc: correct check azuredisk csi pod status doc
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/NOTES.txt
Labels: kind/documentation, size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#2023 chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes
