Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2023-11, with the labels that each got.

#2029 [release-1.29]chore: fix google.golang.org/grpc GHSA-m425-mq94-257g
  go.mod
  go.sum
  vendor/github.com/google/uuid/.travis.yml
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/CONTRIBUTING.md
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/uuid.go
  vendor/golang.org/x/oauth2/internal/client_appengine.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/field_behavior.pb.go
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/attributes/attributes.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/call.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/encoding/encoding.go
  vendor/google.golang.org/grpc/internal/backoff/backoff.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/status/status.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/resolver/manual/manual.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/tap/tap.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: size/XL, approved, lgtm, cncf-cla: yes

#2038 chore: update max data disk table
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/feature, size/M, approved, cncf-cla: yes

#2044 chore: CVE-2023-45142: bump otelhttp to v0.45.0
  go.mod
  go.sum
  vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/config.go
  vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/doc.go
  vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/interceptor.go
  vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/internal/parse.go
  vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/metadata_supplier.go
  vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/semconv.go
  vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/stats_handler.go
  vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/version.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/version.go
  vendor/modules.txt
Labels: size/XL, approved, lgtm, cncf-cla: yes

#2046 chore: upgrade snapshot version to v6.3.1
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2052 chore: support CSI spec v1.9.0
  go.mod
  go.sum
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/modules.txt
Labels: kind/feature, size/XL, approved, cncf-cla: yes

#2051 [release-1.29] feat: upgrade snapshot version to v6.3.1
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.29.1.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2061 [release-1.29] fix: v1.29.1.1-windows-hp image
  charts/v1.29.1/azuredisk-csi-driver-v1.29.1.tgz
  charts/v1.29.1/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.29.1/csi-azuredisk-node-windows-hostprocess.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2060 fix: v1.29.1.1-windows-hp image
  charts/v1.29.1/azuredisk-csi-driver-v1.29.1.tgz
  charts/v1.29.1/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.29.1/csi-azuredisk-node-windows-hostprocess.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2058 chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes

#2067 fix: CVE-2023-5528
  go.mod
  go.sum
  vendor/k8s.io/api/batch/v1/generated.proto
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/dispatcher.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/validating/dispatcher.go
  vendor/k8s.io/apiserver/pkg/cel/library/cost.go
  vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/server/options/encryptionconfig/config.go
  vendor/k8s.io/apiserver/pkg/server/secure_serving.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/test/e2e/framework/pod/wait.go
  vendor/k8s.io/mount-utils/mount_windows.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/L

#2072 [release-1.26] fix: CVE-2023-5528
  go.mod
  go.sum
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/internal/httprule/parse.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/context.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/convert.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/fieldmask.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/handler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/marshal_jsonpb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/mux.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/query.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/string_array_flag.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/golang.org/x/time/AUTHORS
  vendor/golang.org/x/time/CONTRIBUTORS
  vendor/golang.org/x/time/rate/rate.go
  vendor/golang.org/x/time/rate/sometimes.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/protobuf/types/known/structpb/struct.pb.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/XXL

#2073 test: upgrade golangci/golangci-lint-action to v1.54
  .github/workflows/static.yaml
  .golangci.yml
  pkg/azuredisk/azure_common_linux.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/identityserver.go
  pkg/azuredisk/nodeserver.go
  pkg/azurediskplugin/main.go
  pkg/azureutils/fake_iohandler.go
  pkg/csi-common/server_test.go
  pkg/mounter/fake_safe_mounter.go
  pkg/mounter/safe_mounter_unix.go
  pkg/optimization/azure_skus_map.go
  pkg/optimization/skus_test.go
  pkg/os/filesystem/filesystem.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_shared_disk_tester.go
  test/e2e/testsuites/dynamically_provisioned_statefulset_e2e_tester.go
  test/e2e/testsuites/pre_provisioned_inline_volume_tester.go
  test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/pre_provisioned_shared_disk_tester.go
  test/e2e/testsuites/specs.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test, kind/test

#2081 chore: update max data disk table
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2091 doc: fix readOnly setting doc
  deploy/example/nginx-pod-azuredisk.yaml
  deploy/example/nginx-pod-ephemeral.yaml
  deploy/example/pv-azuredisk-csi.yaml
  deploy/example/statefulset-nonroot.yaml
  deploy/example/statefulset-nozone.yaml
  deploy/example/statefulset.yaml
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#2093 fix: improve disk attach/detach error message
  pkg/azuredisk/controllerserver.go
Labels: kind/bug, size/S, approved, lgtm, cncf-cla: yes, ok-to-test

#2098 test: fix multi-zone test failure on capz multi-zone cluster
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
Labels: size/S, kind/failing-test, approved, cncf-cla: yes

#2103 doc: recommend available skuNames
  deploy/example/storageclass-azuredisk-csi-allowed-topology.yaml
  deploy/example/storageclass-azuredisk-csi.yaml
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#2101 [release-1.27] test: fix multi-zone test failure on capz multi-zone cluster
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
Labels: size/S, kind/failing-test, approved, cncf-cla: yes

#2102 [release-1.26] test: fix multi-zone test failure on capz multi-zone cluster
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
Labels: size/S, kind/failing-test, approved, cncf-cla: yes

#2035 chore: upgrade base image to alpine 3.18.4
  pkg/azurediskplugin/Dockerfile
  test/e2e/dynamic_provisioning_test.go
Labels: kind/feature, size/XS, approved, cncf-cla: yes
