Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2023-08, with the labels that each got.

#1916 chore: update max data disk count table
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#1915 [V2] fix: fix error handling of attach status updates
  pkg/azureutils/azure_disk_utils.go
  pkg/controller/attach_detach.go
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes

#1899 [V2] chore: adding logs when pod failover test cordons and deferring uncordon
  test/podFailover/controller/cmd/main.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test, kind/test

#1932 doc: add permissions for CSI driver controller
  docs/driver-parameters.md
Labels: kind/documentation, size/XS, approved, lgtm, cncf-cla: yes

#1935 feat(helm) Allow setting an alternate name of the configmap for the azure credential path
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
Labels: kind/feature, size/S, approved, lgtm, cncf-cla: yes

#1936 [V2] fix: retry annotation not being added for replica volume attachment CRI when context.DeadlineExceeded occurs on attach 🐞
  pkg/azurediskplugin/main.go
  pkg/controller/attach_detach.go
  pkg/controller/attach_detach_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1939 fix: use env var in powershell cmdlet
  pkg/azuredisk/nodeserver_test.go
  pkg/os/volume/volume.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1940 cleanup: windows mount code
  pkg/azuredisk/nodeserver_test.go
  pkg/os/disk/disk.go
  pkg/os/filesystem/filesystem.go
  pkg/os/volume/volume.go
Labels: size/M, approved, cncf-cla: yes, kind/cleanup

#1946 doc: update new chart versions
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.28.3/azuredisk-csi-driver-v1.28.3.tgz
  charts/v1.28.3/azuredisk-csi-driver/Chart.yaml
  charts/v1.28.3/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.28.3/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.28.3/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.28.3/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.28.3/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.28.3/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/v1.28.3/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.28.3/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.28.3/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.28.3/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.28.3/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.28.3/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.28.3/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.28.3/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.28.3/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.28.3/azuredisk-csi-driver/values.yaml
  deploy/v1.28.3/crd-csi-snapshot.yaml
  deploy/v1.28.3/csi-azuredisk-controller.yaml
  deploy/v1.28.3/csi-azuredisk-driver.yaml
  deploy/v1.28.3/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.28.3/csi-azuredisk-node-windows.yaml
  deploy/v1.28.3/csi-azuredisk-node.yaml
  deploy/v1.28.3/csi-snapshot-controller.yaml
  deploy/v1.28.3/rbac-csi-azuredisk-controller.yaml
  deploy/v1.28.3/rbac-csi-azuredisk-node.yaml
  deploy/v1.28.3/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.28.3.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL
