Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2023-03, with the labels that each got.

#1744 [release-1.26] fix: CVE-2022-41723
  go.mod
  go.sum
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/flow.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/trace/histogram.go
  vendor/golang.org/x/sys/cpu/cpu_gccgo_x86.c
  vendor/golang.org/x/sys/cpu/endian_big.go
  vendor/golang.org/x/sys/cpu/endian_little.go
  vendor/golang.org/x/sys/unix/gccgo_c.c
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_386.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_arm.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_arm64.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/timestruct.go
  vendor/golang.org/x/sys/unix/xattr_bsd.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/modules.txt
Labels: kind/bug, size/XL, approved, cncf-cla: yes

#1724 [V2] feat: add optimistic lun implementation
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/L, ok-to-test

#1748 tes: fix golint action failure
  .github/workflows/static.yaml
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#1751 test: fix golint action failure
  .github/workflows/static.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/cleanup

#1747 [V2] refactor: use function AppendToUpdateCRIFunc
  pkg/controller/attach_detach.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/cleanup, ok-to-test

#1752 [V2] style: delete duplicated import of k8s.io/apimachinery/pkg/api/errors
  pkg/controller/common_test.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/cleanup, ok-to-test

#1739 [V2] fix: enhance UpdateCRIWithRetry to fix the cachedClient Get not found…
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
  pkg/controller/attach_detach.go
  pkg/controller/shared_state.go
Labels: kind/bug, size/XL, approved, lgtm, cncf-cla: yes, ok-to-test

#1754 [V2] chore: limit max shares for all disks
  docs/design-v2.md
  pkg/azureutils/azure_disk_utils.go
Labels: size/S, approved, lgtm, cncf-cla: yes, kind/design, ok-to-test

#1760 [V2] style: clean up typo and duplicated imports
  pkg/azureutils/azure_disk_utils_test.go
  test/upgrade/flags.go
  test/utils/node/node_utils.go
Labels: size/S, approved, lgtm, cncf-cla: yes, kind/cleanup, ok-to-test

#1766 test: enable online expansion external test
  test/external-e2e/manifest/testdriver.yaml
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1771 doc: add accessModes doc
  .github/workflows/codeql-analysis.yml
  README.md
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#1762 [V2] chore: add parse max shares unit test
  pkg/azureutils/azure_disk_utils_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test, kind/test

#1756 [V2] fix: replica AzVolumeAttachment retries return inconsistent error type
  pkg/controller/attach_detach.go
  pkg/controller/replica.go
Labels: kind/bug, size/S, approved, lgtm, cncf-cla: yes, ok-to-test

#1776 [V2] chore: reporting pod failover downtime async
  test/podFailover/workload/cmd/main.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/cleanup, ok-to-test

#1777 [V2] fix: only create replica AzVolumeAttachments for the running pod when recovering pods
  pkg/controller/pod.go
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#1772 [V2] docs: add docs for different annotations.
  pkg/azureconstants/azure_constants.go
Labels: kind/documentation, size/S, cncf-cla: yes, ok-to-test

#1783 cleanup: remove 20H2 windows image build
  Makefile
Labels: size/XS, approved, cncf-cla: yes, kind/cleanup

#1787 [V2] fix: recover nodes with correct remaining capacity
  pkg/azureutils/azure_disk_utils.go
  pkg/controller/attach_detach.go
  pkg/controller/common.go
  pkg/controller/common_test.go
  pkg/controller/shared_state.go
  pkg/controller/shared_state_test.go
Labels: kind/bug, size/M, lgtm, cncf-cla: yes, ok-to-test

#1792 [V2] chore: use aks cli instead of aks-engine
  hack/azure-cluster-up.sh
Labels: approved, cncf-cla: yes, size/L, kind/cleanup

#1790 fix: PremiumV2_LRS caching mode issue
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
Labels: kind/bug, approved, lgtm, cncf-cla: yes, size/L

#1793 [V2] fix: add missing toleration for latest control plane taint
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.11.tgz
  charts/latest-v2/azuredisk-csi-driver/values.yaml
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes

#1800 [V2] chore: fix AKS preview extension update
  hack/azure-cluster-up.sh
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/cleanup
