Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2023-12, with the labels that each got.

#2111 test: remove zone restrictions in e2e tests
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
Labels: size/M, approved, cncf-cla: yes, kind/cleanup

#2117 [release-1.29] fix: avoid disk lun collision issue in edge case
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  go.mod
  go.sum
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/azuredisk_v1_test.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azuredisk/fake_azuredisk_v2.go
  pkg/azurediskplugin/main.go
  pkg/util/util.go
  pkg/util/util_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/configloader/config_loader.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/configloader/load.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/configloader/loader_empty.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/configloader/loader_file.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/configloader/loader_secret.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/configloader/loader_yaml.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_instance_metadata.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_instances_v1.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_instances_v2.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_routes.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_zones.go
Labels: kind/bug, size/XL, approved, cncf-cla: yes

#2114 chore: upgrade ginkgo to v2
  test/external-e2e/manifest/testdriver.yaml
  test/external-e2e/run.sh
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2119 test: upgrade to external 1.27 e2e tests
  test/external-e2e/run.sh
Labels: size/XS, approved, cncf-cla: yes, kind/test

#2124 Chores: put lint args into golangci-lint config file
  .github/workflows/static.yaml
  .golangci.yml
Labels: size/S, approved, lgtm, cncf-cla: yes, kind/cleanup

#2140 [release-1.27] test: upgrade golangci/golangci-lint-action to v1.54
  .github/workflows/static.yaml
  .golangci.yml
  pkg/azuredisk/azure_common_linux.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/identityserver.go
  pkg/azuredisk/nodeserver.go
  pkg/azurediskplugin/main.go
  pkg/azureutils/fake_iohandler.go
  pkg/csi-common/server_test.go
  pkg/mounter/fake_safe_mounter.go
  pkg/mounter/safe_mounter_unix.go
  pkg/optimization/azure_skus_map.go
  pkg/optimization/skus_test.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_shared_disk_tester.go
  test/e2e/testsuites/dynamically_provisioned_statefulset_e2e_tester.go
  test/e2e/testsuites/pre_provisioned_inline_volume_tester.go
  test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/pre_provisioned_shared_disk_tester.go
  test/e2e/testsuites/specs.go
  test/utils/azure/azure_helpers.go
Labels: size/M, cncf-cla: yes, ok-to-test, kind/test

#2141 [release-1.28] test: upgrade golangci/golangci-lint-action to v1.54
  .github/workflows/static.yaml
  .golangci.yml
  pkg/azuredisk/azure_common_linux.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/identityserver.go
  pkg/azuredisk/nodeserver.go
  pkg/azurediskplugin/main.go
  pkg/azureutils/fake_iohandler.go
  pkg/csi-common/server_test.go
  pkg/mounter/fake_safe_mounter.go
  pkg/mounter/safe_mounter_unix.go
  pkg/optimization/azure_skus_map.go
  pkg/optimization/skus_test.go
  pkg/os/filesystem/filesystem.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_shared_disk_tester.go
  test/e2e/testsuites/dynamically_provisioned_statefulset_e2e_tester.go
  test/e2e/testsuites/pre_provisioned_inline_volume_tester.go
  test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/pre_provisioned_shared_disk_tester.go
  test/e2e/testsuites/specs.go
  test/utils/azure/azure_helpers.go
Labels: size/M, cncf-cla: yes, ok-to-test, kind/test

#2136 [release-1.28] fix: CVE-2023-48795
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/ssh/channel.go
  vendor/golang.org/x/crypto/ssh/client.go
  vendor/golang.org/x/crypto/ssh/client_auth.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/tcpip.go
  vendor/golang.org/x/crypto/ssh/transport.go
  vendor/golang.org/x/sys/unix/fcntl.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_openbsd.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.s
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: kind/bug, size/XL, approved, cncf-cla: yes

#2142 [release-1.29] test: upgrade golangci/golangci-lint-action to v1.54
  .github/workflows/static.yaml
  .golangci.yml
  pkg/azuredisk/azure_common_linux.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/identityserver.go
  pkg/azuredisk/nodeserver.go
  pkg/azurediskplugin/main.go
  pkg/azureutils/fake_iohandler.go
  pkg/csi-common/server_test.go
  pkg/mounter/fake_safe_mounter.go
  pkg/mounter/safe_mounter_unix.go
  pkg/optimization/azure_skus_map.go
  pkg/optimization/skus_test.go
  pkg/os/filesystem/filesystem.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_shared_disk_tester.go
  test/e2e/testsuites/dynamically_provisioned_statefulset_e2e_tester.go
  test/e2e/testsuites/pre_provisioned_inline_volume_tester.go
  test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/pre_provisioned_shared_disk_tester.go
  test/e2e/testsuites/specs.go
  test/utils/azure/azure_helpers.go
Labels: size/M, approved, cncf-cla: yes, ok-to-test, kind/test

#2135 [release-1.29] fix: CVE-2023-48795
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/ssh/channel.go
  vendor/golang.org/x/crypto/ssh/client.go
  vendor/golang.org/x/crypto/ssh/client_auth.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/tcpip.go
  vendor/golang.org/x/crypto/ssh/transport.go
  vendor/golang.org/x/sys/unix/fcntl.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_openbsd.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.s
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: kind/bug, size/XL, approved, cncf-cla: yes

#2139 [release-1.26] test: upgrade golangci/golangci-lint-action to v1.54
  .github/workflows/static.yaml
  .golangci.yml
  pkg/azuredisk/azure_common_linux.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/identityserver.go
  pkg/azuredisk/nodeserver.go
  pkg/azurediskplugin/main.go
  pkg/azureutils/fake_iohandler.go
  pkg/csi-common/server_test.go
  pkg/mounter/fake_safe_mounter.go
  pkg/mounter/safe_mounter_unix.go
  pkg/optimization/azure_skus_map.go
  pkg/optimization/skus_test.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_shared_disk_tester.go
  test/e2e/testsuites/dynamically_provisioned_statefulset_e2e_tester.go
  test/e2e/testsuites/pre_provisioned_inline_volume_tester.go
  test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/pre_provisioned_shared_disk_tester.go
  test/e2e/testsuites/specs.go
  test/utils/azure/azure_helpers.go
Labels: size/M, approved, cncf-cla: yes, ok-to-test, kind/test

#2128 Refactor:Remove grpc wrapper
  go.mod
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azuredisk/fake_azuredisk_v2.go
  pkg/azurediskplugin/main.go
  pkg/csi-common/server.go
  pkg/csi-common/server_test.go
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
  test/e2e/suite_test.go
Labels: lgtm, cncf-cla: yes, size/L, kind/cleanup

#2123 Refactor: move flags definition to config functions
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_option.go
  pkg/azuredisk/azuredisk_option_test.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azurediskplugin/main.go
Labels: approved, lgtm, cncf-cla: yes, size/L, kind/cleanup
