Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2023-02, with the labels that each got.

#1714 feat: add dataAccessAuthMode parameter to snapshot storage class
  docs/driver-parameters.md
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
  test/e2e/driver/azuredisk_driver.go
  test/e2e/driver/driver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
  test/e2e/testsuites/specs.go
Labels: kind/feature, approved, cncf-cla: yes, size/L

#1712 [V2] build: disable provenance attestation to work around docker issue
  Makefile
  test/external-e2e/run.sh
Labels: size/S, approved, cncf-cla: yes, kind/cleanup

#1720 fix: buildx issue with provenance disabled
  Makefile
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#1721 [V2] feat: creating workload manifest to use for workload tests
  test/e2e/manifest/workload.json
Labels: kind/feature, size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1719 fix: increase csi-attacher worker-threads num
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  test/external-e2e/run.sh
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1723 chore: remove dependency on golang.org/x/text specific version
  go.mod
  go.sum
  vendor/golang.org/x/text/internal/language/compact/language.go
  vendor/golang.org/x/text/internal/language/language.go
  vendor/golang.org/x/text/internal/language/lookup.go
  vendor/golang.org/x/text/language/go1_1.go
  vendor/golang.org/x/text/language/go1_2.go
  vendor/golang.org/x/text/language/language.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/runes/runes.go
  vendor/golang.org/x/text/unicode/bidi/trieval.go
  vendor/modules.txt
Labels: size/M, approved, cncf-cla: yes, kind/cleanup

#1716 feat: integrate traffic manager proxy
  Makefile
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/controllerserver.go
  pkg/azurediskplugin/main.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
  test/utils/azuredisk_log.sh
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1726 chore: increase csi-attacher sidecar qps/burst/thread
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.11.tgz
  charts/latest-v2/azuredisk-csi-driver/values.yaml
  deploy/latest-v2/csi-azuredisk-controller.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes, kind/cleanup

#1725 Pin k8s.io/dynamic-resource-allocation version
  go.mod
  vendor/modules.txt
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/cleanup

#1728 fix: second expand volume failure on Ubuntu 22.04
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
  pkg/azuredisk/nodeserver_v2.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1727 [feat] support volumesnapshotclass in helm chart
  Makefile
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
Labels: kind/feature, size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#1730 doc: cut v1.27.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/v1.27.0/azuredisk-csi-driver-v1.27.0.tgz
  charts/v1.27.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.27.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.27.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.27.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.27.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.27.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.27.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/v1.27.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.27.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.27.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.27.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.27.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.27.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.27.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.27.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.27.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.27.0/azuredisk-csi-driver/values.yaml
  deploy/v1.27.0/crd-csi-snapshot.yaml
  deploy/v1.27.0/csi-azuredisk-controller.yaml
  deploy/v1.27.0/csi-azuredisk-driver.yaml
  deploy/v1.27.0/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.27.0/csi-azuredisk-node-windows.yaml
  deploy/v1.27.0/csi-azuredisk-node.yaml
  deploy/v1.27.0/csi-snapshot-controller.yaml
  deploy/v1.27.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.27.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.27.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.27.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1733 chore: update maxDataDiskCountMap
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1732 fix: CVE-2022-41723
  go.mod
  go.sum
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/flow.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/trace/histogram.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/L

#1736 cleanup: remove metrics-address on driver daemonset on the node
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  pkg/azurediskplugin/main.go
Labels: size/S, approved, cncf-cla: yes, kind/cleanup

#1738 [V2] fix: matching scale test manifest with aurora
  test/e2e/manifest/scale-test.json
Labels: size/XS, needs-ok-to-test, cncf-cla: yes, kind/test

#1737 [V2] chore: fix getting pods from alternate namespace
  hack/get-logs.sh
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/cleanup

#1650 [V2] fix: update replica attachment failure retries logic
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.11.tgz
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest-v2/azuredisk-csi-driver/values.yaml
  pkg/apis/azuredisk/v1beta2/types.go
  pkg/azureconstants/azure_constants.go
  pkg/azurediskplugin/main.go
  pkg/controller/attach_detach.go
  pkg/controller/replica.go
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/L, ok-to-test

#1740 [V2] feat: increasing kube-client limits
  charts/index.yaml
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.11.tgz
  charts/latest-v2/azuredisk-csi-driver/values.yaml
  deploy/latest-v2/csi-azuredisk-controller.yaml
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/L, ok-to-test
