Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2024-10, with the labels that each got.

#2538 chore: update max data disk count table
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2545 chore: update max data disk num for v6 vm sku
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/feature, size/M, approved, cncf-cla: yes

#2549 [release-1.30] feat: add extra-create-metadata=true on snapshot sidecar
  charts/latest/azuredisk-csi-driver-v1.30.4.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-controller.yaml
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/controllerserver.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2550 chore: reset as v1.28.11 release
  Makefile
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v1.28.11.tgz
  charts/latest/azuredisk-csi-driver-v1.28.12.tgz
  charts/latest/azuredisk-csi-driver/Chart.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  charts/v1.28.11/azuredisk-csi-driver-v1.28.11.tgz
  charts/v1.28.12/azuredisk-csi-driver-v1.28.12.tgz
  charts/v1.28.12/azuredisk-csi-driver/Chart.yaml
  charts/v1.28.12/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.28.12/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.28.12/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.28.12/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.28.12/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.28.12/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/v1.28.12/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.28.12/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.28.12/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.28.12/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.28.12/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.28.12/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.28.12/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.28.12/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.28.12/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.28.12/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  deploy/v.28.11/crd-csi-snapshot.yaml
  deploy/v.28.11/csi-azuredisk-controller.yaml
  deploy/v.28.11/csi-azuredisk-driver.yaml
  deploy/v.28.11/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v.28.11/csi-azuredisk-node-windows.yaml
  deploy/v.28.11/csi-azuredisk-node.yaml
  deploy/v.28.11/csi-snapshot-controller.yaml
  deploy/v.28.11/rbac-csi-azuredisk-controller.yaml
  deploy/v.28.11/rbac-csi-azuredisk-node.yaml
  deploy/v.28.11/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.28.12.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#2552 test: run windows ut with host process enabled
  pkg/azuredisk/fake_azuredisk.go
  pkg/azuredisk/fake_azuredisk_v2.go
Labels: size/XS, approved, cncf-cla: yes, kind/test

#2555 doc: cut v1.31.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/v1.31.0/azuredisk-csi-driver-1.31.0.tgz
  charts/v1.31.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.31.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.31.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.31.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.31.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.31.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.31.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/v1.31.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.31.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.31.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.31.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.31.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.31.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.31.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.31.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.31.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.31.0/azuredisk-csi-driver/values.yaml
  deploy/v1.31.0/crd-csi-snapshot.yaml
  deploy/v1.31.0/csi-azuredisk-controller.yaml
  deploy/v1.31.0/csi-azuredisk-driver.yaml
  deploy/v1.31.0/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.31.0/csi-azuredisk-node-windows.yaml
  deploy/v1.31.0/csi-azuredisk-node.yaml
  deploy/v1.31.0/csi-snapshot-controller.yaml
  deploy/v1.31.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.31.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.31.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.31.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#2559 test: add snapshot restore test on xfs file system
  test/e2e/dynamic_provisioning_test.go
Labels: size/XS, approved, cncf-cla: yes, kind/test

#2561 feat: add pre-defined tags in snapshot creation
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/azure_managedDiskController.go
  pkg/azuredisk/controllerserver.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2566 [release-1.30] fix: add CriticalAddonsOnly toleration into controller pod
  charts/latest/azuredisk-csi-driver-v1.30.5.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  charts/v1.30.5/azuredisk-csi-driver-v1.30.5.tgz
  charts/v1.30.5/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2564 [release-1.30] feat: add pre-defined tags in snapshot creation
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/azure_managedDiskController.go
  pkg/azuredisk/controllerserver.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2565 [release-1.31] fix: add CriticalAddonsOnly toleration into controller pod
  charts/latest/azuredisk-csi-driver-1.31.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  charts/v1.31.0/azuredisk-csi-driver-1.31.0.tgz
  charts/v1.31.0/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/v1.31.0/csi-azuredisk-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2568 doc: support example pod running on arm64 node
  charts/index.yaml
  deploy/example/cloning/nginx-pod-restored-cloning.yaml
  deploy/example/daemonset-azuredisk-ephemeral.yaml
  deploy/example/deployment.yaml
  deploy/example/nginx-pod-azuredisk.yaml
  deploy/example/nginx-pod-ephemeral.yaml
  deploy/example/rawblock/README.md
  deploy/example/rawblock/nginx-pod-azuredisk.yaml
  deploy/example/sharedisk/README.md
  deploy/example/sharedisk/deployment.yaml
  deploy/example/snapshot/nginx-pod-restored-snapshot.yaml
  deploy/example/statefulset-nonroot.yaml
  deploy/example/statefulset-nozone.yaml
  deploy/example/statefulset.yaml
  docs/known-issues/node-shutdown-recovery/statefulset-azuredisk.yaml
Labels: kind/documentation, approved, cncf-cla: yes, size/L

#2569 fix: support attach operations after premiumV2 disk migration
  pkg/azuredisk/azure_controller_common.go
Labels: size/XS, approved, lgtm, cncf-cla: yes
