Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2024-09, with the labels that each got.

#2480 chore: Replace deprecated "k8s.io/utils/pointer" with "k8s.io/utils/ptr"
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azure_controller_common_test.go
  pkg/azuredisk/azure_managedDiskController.go
  pkg/azuredisk/azure_managedDiskController_test.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
  test/e2e/testsuites/testsuites.go
Labels: approved, lgtm, cncf-cla: yes, size/L, ok-to-test

#2487 cleanup: upgrade golint version and fix golint errors
  .github/workflows/static.yaml
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azure_controller_common_test.go
  pkg/azuredisk/azure_managedDiskController.go
  pkg/azuredisk/azure_managedDiskController_test.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_option_test.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
  pkg/azuredisk/nodeserver_v2.go
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
  pkg/os/volume/volume.go
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
Labels: approved, lgtm, cncf-cla: yes, size/L, ok-to-test

#2490 chore: upgrade to base image alpine 3.20.2
  pkg/azurediskplugin/Dockerfile
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2488 fix: increase liveness-probe timeout on Windows node
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node-windows.yaml
  test/e2e/dynamic_provisioning_test.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2492 test: skip "should create a volume azuredisk with tag" test on Windows
  test/e2e/dynamic_provisioning_test.go
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#2498 chore: upgrade golang version
  .github/workflows/trivy.yaml
  go.mod
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#2503 fix: resize failure when cloning a volume with bigger size on Windows
  pkg/mounter/safe_mounter_host_process_windows.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2499 [release-1.30] chore: upgrade golang version
  .github/workflows/trivy.yaml
  go.mod
  vendor/k8s.io/kubernetes/test/e2e/framework/testfiles/testdata/a/foo.txt
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#2508 [release-1.29] cleanup: upgrade golint version and fix golint errors
  .github/workflows/static.yaml
  .golangci.yml
  pkg/azuredisk/azure_common_linux_test.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/azuredisk_v1.go
  pkg/azuredisk/azuredisk_v1_test.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
  pkg/azuredisk/nodeserver_v2.go
  pkg/azurediskplugin/main.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
  pkg/azureutils/azure_snapshot_utils.go
  pkg/azureutils/azure_snapshot_utils_test.go
  pkg/csi-common/server.go
  pkg/csi-common/utils_test.go
  pkg/os/disk/types.go
  pkg/os/volume/volume.go
  pkg/tool/gen-disk-skus-map.go
  pkg/util/util.go
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_detach_tester.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_tag_tester.go
  test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
  test/e2e/testsuites/testsuites.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
Labels: cncf-cla: yes, size/L, kind/cleanup, ok-to-test

#2501 [release-1.28] chore: upgrade golang version
  .github/workflows/trivy.yaml
  go.mod
  vendor/k8s.io/kubernetes/test/e2e/framework/testfiles/testdata/a/foo.txt
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#2510 fix: upgrade node-driver-registrar to fix register timeout issue
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  charts/v1.29.5/azuredisk-csi-driver-v1.29.5.tgz
  charts/v1.29.5/azuredisk-csi-driver/values.yaml
  charts/v1.29.7/azuredisk-csi-driver-v1.29.7.tgz
  charts/v1.29.7/azuredisk-csi-driver/values.yaml
  charts/v1.29.8/azuredisk-csi-driver-v1.29.8.tgz
  charts/v1.29.8/azuredisk-csi-driver/values.yaml
  charts/v1.30.2/azuredisk-csi-driver-v1.30.2.tgz
  charts/v1.30.2/azuredisk-csi-driver/values.yaml
  charts/v1.30.3/azuredisk-csi-driver-v1.30.3.tgz
  charts/v1.30.3/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  deploy/v1.29.5/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.29.5/csi-azuredisk-node-windows.yaml
  deploy/v1.29.5/csi-azuredisk-node.yaml
  deploy/v1.29.7/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.29.7/csi-azuredisk-node-windows.yaml
  deploy/v1.29.7/csi-azuredisk-node.yaml
  deploy/v1.29.8/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.29.8/csi-azuredisk-node-windows.yaml
  deploy/v1.29.8/csi-azuredisk-node.yaml
  deploy/v1.30.2/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.30.2/csi-azuredisk-node-windows.yaml
  deploy/v1.30.2/csi-azuredisk-node.yaml
  deploy/v1.30.3/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.30.3/csi-azuredisk-node-windows.yaml
  deploy/v1.30.3/csi-azuredisk-node.yaml
Labels: kind/bug, size/M, approved, cncf-cla: yes

#2500 [release-1.29] chore: upgrade golang version
  .github/workflows/trivy.yaml
  go.mod
  vendor/k8s.io/kubernetes/test/e2e/framework/testfiles/testdata/a/foo.txt
Labels: kind/failing-test, size/XS, approved, lgtm, cncf-cla: yes

#2512 [release-1.29] fix: upgrade node-driver-registrar to fix register timeout issue
  charts/latest/azuredisk-csi-driver-v1.29.9.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  charts/v1.29.5/azuredisk-csi-driver/values.yaml
  charts/v1.29.7/azuredisk-csi-driver-v1.29.7.tgz
  charts/v1.29.7/azuredisk-csi-driver/values.yaml
  charts/v1.29.8/azuredisk-csi-driver-v1.29.8.tgz
  charts/v1.29.8/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  deploy/v1.29.7/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.29.7/csi-azuredisk-node-windows.yaml
  deploy/v1.29.7/csi-azuredisk-node.yaml
  deploy/v1.29.8/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.29.8/csi-azuredisk-node-windows.yaml
  deploy/v1.29.8/csi-azuredisk-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2507 [release-1.28] cleanup: upgrade golint version and fix golint errors
  .github/workflows/static.yaml
  .golangci.yml
  pkg/azuredisk/azure_common_linux_test.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/azuredisk_v1.go
  pkg/azuredisk/azuredisk_v1_test.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
  pkg/azuredisk/nodeserver_v2.go
  pkg/azurediskplugin/main.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
  pkg/azureutils/azure_snapshot_utils.go
  pkg/azureutils/azure_snapshot_utils_test.go
  pkg/csi-common/utils_test.go
  pkg/os/disk/types.go
  pkg/os/volume/volume.go
  pkg/tool/gen-disk-skus-map.go
  pkg/util/util.go
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_detach_tester.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_tag_tester.go
  test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, size/L, kind/cleanup, ok-to-test

#2515 [release-1.28] fix: increase liveness-probe timeout on Windows node
  charts/latest/azuredisk-csi-driver-v1.28.11.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node-windows.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2513 [release-1.30] fix: increase liveness-probe timeout on Windows node
  charts/latest/azuredisk-csi-driver-v1.30.4.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node-windows.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2511 [release-1.30] fix: upgrade node-driver-registrar to fix register timeout issue
  charts/README.md
  charts/latest/azuredisk-csi-driver/values.yaml
  charts/v1.30.2/azuredisk-csi-driver-v1.30.2.tgz
  charts/v1.30.2/azuredisk-csi-driver/values.yaml
  charts/v1.30.3/azuredisk-csi-driver-v1.30.3.tgz
  charts/v1.30.3/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  deploy/v1.30.2/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.30.2/csi-azuredisk-node-windows.yaml
  deploy/v1.30.2/csi-azuredisk-node.yaml
  deploy/v1.30.3/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.30.3/csi-azuredisk-node-windows.yaml
  deploy/v1.30.3/csi-azuredisk-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2516 chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  deploy/csi-snapshot-controller.yaml
  test/e2e/dynamic_provisioning_test.go
Labels: kind/feature, size/M, approved, cncf-cla: yes

#2514 [release-1.29] fix: increase liveness-probe timeout on Windows node
  charts/latest/azuredisk-csi-driver-v1.29.9.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node-windows.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2520 [release-1.29] chore: upgrade sidecar image versions
  charts/latest/azuredisk-csi-driver-v1.29.9.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2521 fix: liveness probe failure when hostNetwork not enabled on linux node
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2524 chore: update static.yaml to avoid .golangci.yml dependency
  .github/workflows/static.yaml
  .golangci.yml
  hack/verify-golint.sh
Labels: size/S, cncf-cla: yes, ok-to-test

#2522 [release-1.28] fix golint and disable staticcheck
  .github/workflows/static.yaml
  pkg/azuredisk/azure_common_linux_test.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/azuredisk_v1.go
  pkg/azuredisk/azuredisk_v1_test.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
  pkg/azurediskplugin/main.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
  pkg/azureutils/azure_snapshot_utils.go
  pkg/os/disk/types.go
  pkg/util/util.go
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_detach_tester.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_tag_tester.go
  test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
  test/e2e/testsuites/testsuites.go
Labels: cncf-cla: yes, size/L, kind/cleanup, ok-to-test

#2523 [release-1.29] fix golint and disable staticcheck
  .github/workflows/static.yaml
  pkg/azuredisk/azure_common_linux_test.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/azuredisk_v1.go
  pkg/azuredisk/azuredisk_v1_test.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azuredisk/nodeserver.go
  pkg/azurediskplugin/main.go
  pkg/csi-common/server.go
  pkg/os/disk/types.go
  pkg/util/util.go
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_detach_tester.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_tag_tester.go
  test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
  test/e2e/testsuites/testsuites.go
Labels: cncf-cla: yes, size/L, kind/cleanup, ok-to-test

#2527 chore: update max data disk num table
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2525 [release-1.30] fix: liveness probe failure when hostNetwork not enabled on linux node
  charts/latest/azuredisk-csi-driver-v1.30.4.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2526 [release-1.29] fix: liveness probe failure when hostNetwork not enabled on linux node
  charts/latest/azuredisk-csi-driver-v1.29.9.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2532 feat: add extra-create-metadata=true on snapshot sidecar
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-controller.yaml
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/controllerserver.go
Labels: kind/feature, size/S, approved, cncf-cla: yes
