Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2024-03, with the labels that each got.

#2208 fix: enable check-disk-lun-collision during disk attach by default
  pkg/azuredisk/azuredisk_option.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2211 fix: use force detach as backoff when disk detach failed
  go.mod
  go.sum
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_option.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/core.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/etag.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported/response_error.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/log/log.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/shared/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/log/log.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/errors.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/request.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64le.s
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmssflex.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_mock_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#2213 feat(helm): add extra args for controller
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
Labels: kind/feature, size/XS, cncf-cla: yes, ok-to-test

#2217 [release-1.30] feat(helm): add extra args for controller
  charts/latest/azuredisk-csi-driver-v1.30.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2223 fix: copy volume error in cross zone scenario
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azuredisk/fake_azuredisk.go
  test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#2230 Add group update policy for k8s.io dependencies
  .github/dependabot.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/test

#2233 fix: Workload identity is not working.
  pkg/azuredisk/azuredisk_test.go
  pkg/azureutils/azure_disk_utils.go
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes

#2239 fix: refine check disk lun collision logic
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/fake_azuredisk.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2241 [release-1.29] fix: enable check-disk-lun-collision during disk attach by default
  pkg/azurediskplugin/main.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2242 [release-1.29] fix: refine check disk lun collision logic
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/fake_azuredisk.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2246 fix: allow special char in tag value
  pkg/azuredisk/azure_managedDiskController.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: kind/bug, size/S, approved, cncf-cla: yes
