Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2024-11, with the labels that each got.

#2578 fix: vm-type is not overriding as expected
  pkg/azuredisk/azuredisk.go
Labels: kind/bug, size/XS, lgtm, cncf-cla: yes, ok-to-test

#2585 Revert "chore: upgrade to base image alpine 3.20.2"
  pkg/azurediskplugin/Dockerfile
Labels: size/XS, approved, cncf-cla: yes

#2594 test: fix trivy action
  .github/workflows/trivy.yaml
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#2593 [release-1.31] fix: CVE-2024-51744
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: kind/bug, size/M, approved, cncf-cla: yes

#2591 fix: CVE-2024-51744
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: kind/bug, size/M, approved, cncf-cla: yes

#2592 [release-1.30] fix: CVE-2024-51744
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: kind/bug, size/M, approved, cncf-cla: yes

#2590 chore: upgrade alpine base image to 3.18.9
  pkg/azurediskplugin/Dockerfile
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2579 feat: replace Get-Item powershell cmd with golang api on Windows HostProcess mode
  pkg/azuredisk/nodeserver_test.go
  pkg/os/volume/volume.go
Labels: kind/feature, size/S, lgtm, cncf-cla: yes, ok-to-test

#2602 test: disable offline expansion tests
  test/external-e2e/manifest/testdriver.yaml
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#2610 docs: Add missing disk encryption set read permission
  docs/driver-parameters.md
Labels: kind/documentation, size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#2611 chore: update max data disk num
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2616 fix: add serial format limit to fix OOM issue when formatting a few disks in parallel in csi-azuredisk-node
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_option.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azuredisk/fake_azuredisk_v2.go
  pkg/mounter/fake_safe_mounter.go
  pkg/mounter/safe_mounter_unix.go
  pkg/mounter/safe_mounter_unix_test.go
  pkg/mounter/safe_mounter_windows.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#2624 fix: tagValueDelimiter parameter mismatch
  pkg/azureconstants/azure_constants.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2628 [release-1.29] fix: tagValueDelimiter parameter mismatch
  pkg/azureconstants/azure_constants.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2630 cleanup: refine logging
  pkg/azuredisk/azure_controller_common.go
Labels: size/XS, approved, cncf-cla: yes, kind/cleanup

#2644 chore: set concurrent-format-timeout as 100s
  pkg/azuredisk/azuredisk_option.go
Labels: size/XS, approved, cncf-cla: yes, kind/cleanup

#2647 cleanup: remove unused livenessProbe in registrar
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: size/M, approved, cncf-cla: yes, kind/cleanup

#2648 [release-1.31] cleanup: remove unused livenessProbe in registrar
  charts/latest/azuredisk-csi-driver-1.31.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: size/M, approved, cncf-cla: yes, kind/cleanup

#2652 Chores:update deps in one pr.
  .github/dependabot.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/test

#2655 feat: pick region when zonal node pool is in different region
  pkg/azuredisk/controllerserver.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
Labels: kind/feature, size/M, approved, cncf-cla: yes

#2658 chore: update CSI spec to v1.10.0
  go.mod
  go.sum
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/identityserver_test.go
  pkg/azuredisk/nodeserver_test.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
  pkg/csi-common/utils_test.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi_grpc.pb.go
  vendor/modules.txt
Labels: kind/feature, approved, cncf-cla: yes, size/XXL

#2663 fix: avoid duplicate ssl mounts on Redhat in AzureStack environment
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#2667 [release-1.29] fix: avoid duplicate ssl mounts on Redhat in AzureStack environment
  charts/latest/azuredisk-csi-driver-v1.29.11.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2666 [release-1.30] fix: avoid duplicate ssl mounts on Redhat in AzureStack environment
  charts/latest/azuredisk-csi-driver-v1.30.6.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2668 fix: avoid duplicate ssl mounts on Redhat in AzureStack in chart config
  charts/v1.29.11/azuredisk-csi-driver-v1.29.11.tgz
  charts/v1.29.11/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.29.11/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.30.6/azuredisk-csi-driver-v1.30.6.tgz
  charts/v1.30.6/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.30.6/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.31.1/azuredisk-csi-driver-1.31.0.tgz
  charts/v1.31.1/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.31.1/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2665 [release-1.31] fix: avoid duplicate ssl mounts on Redhat in AzureStack environment
  charts/latest/azuredisk-csi-driver-1.31.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2673 chore: increase format timeout as 300s by default
  pkg/azuredisk/azuredisk_option.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2677 fix: increase snapshot container memory limit
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2678 [release-1.31] fix: increase snapshot container memory limit
  charts/README.md
  charts/latest/azuredisk-csi-driver-1.31.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2680 [release-1.30] fix: increase snapshot container memory limit
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.30.6.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2681 [release-1.29] fix: increase snapshot container memory limit
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.29.11.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2682 fix: update max data disk count table with v6 VM sku
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/feature, size/M, approved, cncf-cla: yes
