Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2024-01, with the labels that each got.

#2148 chore: adjust logging in node daemonset
  pkg/azuredisk/nodeserver.go
Labels: size/XS, approved, cncf-cla: yes, kind/cleanup

#2154 Refactor:bump cloudprovider and adopt new function changes
  go.mod
  go.sum
  pkg/azuredisk/azure_controller_common_test.go
  pkg/azuredisk/azure_managedDiskController_test.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/ginkgo_t_dsl.go
  vendor/github.com/onsi/ginkgo/v2/internal/output_interceptor_wasm.go
  vendor/github.com/onsi/ginkgo/v2/internal/progress_report_wasm.go
  vendor/github.com/onsi/ginkgo/v2/internal/suite.go
  vendor/github.com/onsi/ginkgo/v2/table_dsl.go
  vendor/github.com/onsi/ginkgo/v2/types/errors.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmssflex.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_fakes.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_utils.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmssflex.go
Labels: approved, lgtm, cncf-cla: yes, size/XXL, kind/cleanup

#2161 chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes

#2155 Refactor: migrate disk client to track2 sdk
  deploy/example/logs/0.2.0/csi-azuredisk-controller.log
  deploy/example/logs/0.3.0/csi-azuredisk-controller.log
  go.mod
  go.sum
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azure_controller_common_test.go
  pkg/azuredisk/azure_managedDiskController.go
  pkg/azuredisk/azure_managedDiskController_test.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/azuredisk_v1_test.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azuredisk/fake_azuredisk_v2.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_detach_tester.go
  test/utils/azure/azure_helpers.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/diskclient/custom.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/diskclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/diskclient/mock_diskclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/factory.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/factory_gen.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/mock_azclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/snapshotclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmssflex.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer_repo.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_mock_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_utils.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets.go
Labels: approved, lgtm, cncf-cla: yes, size/XXL, kind/cleanup

#2164 Refactor: migrate snapshot client to track2 sdk
  go.mod
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azureutils/azure_disk_utils_test.go
  pkg/azureutils/azure_snapshot_utils.go
  pkg/azureutils/azure_snapshot_utils_test.go
  pkg/tool/gen-disk-skus-map.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/snapshotclient/mock_snapshotclient/interface.go
Labels: size/XL, approved, lgtm, cncf-cla: yes, kind/cleanup

#2163 chore: adding ability to BYO storage classes for pod failover
  test/podFailover/workload/chart/templates/workload.yaml
Labels: kind/feature, size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#2167 cleanup: fix k8s.io/endpointslice dependency
  go.mod
  hack/verify-gomod.sh
  vendor/modules.txt
Labels: size/XS, approved, cncf-cla: yes, kind/cleanup
