Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2024-08, with the labels that each got.

#2446 feat: add grpcprom interceptor to export basic grpc metrics
  go.mod
  go.sum
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/LICENSE
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/client_metrics.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/client_options.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/constants.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/options.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/reporter.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/server_metrics.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/server_options.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/COPYRIGHT
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/LICENSE
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/callmeta.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/client.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/reporter.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/server.go
  vendor/github.com/stoewer/go-strcase/README.md
  vendor/github.com/stoewer/go-strcase/camel.go
  vendor/google.golang.org/grpc/reflection/README.md
  vendor/google.golang.org/grpc/reflection/adapt.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1/reflection.pb.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1/reflection_grpc.pb.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
  vendor/google.golang.org/grpc/reflection/internal/internal.go
  vendor/google.golang.org/grpc/reflection/serverreflection.go
  vendor/modules.txt
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/XXL, ok-to-test

#2450 fix: create snapshot failure in edge zone
  pkg/azuredisk/azure_managedDiskController.go
  pkg/azuredisk/controllerserver.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2453 [release-1.29] fix: create snapshot failure in edge zone
  pkg/azuredisk/controllerserver.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2457 chore: set HostProcess container deployment on Windows as default
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/install-driver.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2456 fix: only enable removeNotReadyTaint on driver node daemonset
  pkg/azuredisk/azuredisk.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2458 [release-1.30] chore: set HostProcess container deployment on Windows as default
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.30.3.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/install-driver.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2464 test: use workload identity for e2e test
  go.mod
  go.sum
  hack/verify-examples.sh
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_detach_tester.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_tag_tester.go
  test/e2e/testsuites/dynamically_provisioned_external_rg_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_volume_snapshot_cross_region_tester.go
  test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
  test/sanity/sanity_test.go
  test/utils/azure/azure_helpers.go
  test/utils/credentials/credentials.go
  test/utils/credentials/credentials_test.go
  test/utils/testutil/testutil.go
  vendor/github.com/pelletier/go-toml/.dockerignore
  vendor/github.com/pelletier/go-toml/.gitignore
  vendor/github.com/pelletier/go-toml/CONTRIBUTING.md
  vendor/github.com/pelletier/go-toml/Dockerfile
  vendor/github.com/pelletier/go-toml/LICENSE
  vendor/github.com/pelletier/go-toml/Makefile
  vendor/github.com/pelletier/go-toml/PULL_REQUEST_TEMPLATE.md
  vendor/github.com/pelletier/go-toml/README.md
  vendor/github.com/pelletier/go-toml/SECURITY.md
  vendor/github.com/pelletier/go-toml/azure-pipelines.yml
  vendor/github.com/pelletier/go-toml/benchmark.sh
  vendor/github.com/pelletier/go-toml/doc.go
  vendor/github.com/pelletier/go-toml/example-crlf.toml
  vendor/github.com/pelletier/go-toml/example.toml
  vendor/github.com/pelletier/go-toml/fuzz.go
  vendor/github.com/pelletier/go-toml/fuzz.sh
  vendor/github.com/pelletier/go-toml/keysparsing.go
  vendor/github.com/pelletier/go-toml/lexer.go
  vendor/github.com/pelletier/go-toml/localtime.go
  vendor/github.com/pelletier/go-toml/marshal.go
  vendor/github.com/pelletier/go-toml/marshal_OrderPreserve_test.toml
  vendor/github.com/pelletier/go-toml/marshal_test.toml
  vendor/github.com/pelletier/go-toml/parser.go
  vendor/github.com/pelletier/go-toml/position.go
  vendor/github.com/pelletier/go-toml/token.go
  vendor/github.com/pelletier/go-toml/toml.go
  vendor/github.com/pelletier/go-toml/tomlpub.go
  vendor/github.com/pelletier/go-toml/tomltree_create.go
  vendor/github.com/pelletier/go-toml/tomltree_write.go
  vendor/github.com/pelletier/go-toml/tomltree_writepub.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/XXL, ok-to-test

#2465 [release-1.30] test: use workload identity for e2e test
  go.mod
  go.sum
  hack/verify-examples.sh
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_detach_tester.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_tag_tester.go
  test/e2e/testsuites/dynamically_provisioned_external_rg_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_volume_snapshot_cross_region_tester.go
  test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
  test/sanity/sanity_test.go
  test/utils/azure/azure_helpers.go
  test/utils/credentials/credentials.go
  test/utils/credentials/credentials_test.go
  test/utils/testutil/testutil.go
  vendor/github.com/pelletier/go-toml/.dockerignore
  vendor/github.com/pelletier/go-toml/.gitignore
  vendor/github.com/pelletier/go-toml/CONTRIBUTING.md
  vendor/github.com/pelletier/go-toml/Dockerfile
  vendor/github.com/pelletier/go-toml/LICENSE
  vendor/github.com/pelletier/go-toml/Makefile
  vendor/github.com/pelletier/go-toml/PULL_REQUEST_TEMPLATE.md
  vendor/github.com/pelletier/go-toml/README.md
  vendor/github.com/pelletier/go-toml/SECURITY.md
  vendor/github.com/pelletier/go-toml/azure-pipelines.yml
  vendor/github.com/pelletier/go-toml/benchmark.sh
  vendor/github.com/pelletier/go-toml/doc.go
  vendor/github.com/pelletier/go-toml/example-crlf.toml
  vendor/github.com/pelletier/go-toml/example.toml
  vendor/github.com/pelletier/go-toml/fuzz.go
  vendor/github.com/pelletier/go-toml/fuzz.sh
  vendor/github.com/pelletier/go-toml/keysparsing.go
  vendor/github.com/pelletier/go-toml/lexer.go
  vendor/github.com/pelletier/go-toml/localtime.go
  vendor/github.com/pelletier/go-toml/marshal.go
  vendor/github.com/pelletier/go-toml/marshal_OrderPreserve_test.toml
  vendor/github.com/pelletier/go-toml/marshal_test.toml
  vendor/github.com/pelletier/go-toml/parser.go
  vendor/github.com/pelletier/go-toml/position.go
  vendor/github.com/pelletier/go-toml/token.go
  vendor/github.com/pelletier/go-toml/toml.go
  vendor/github.com/pelletier/go-toml/tomlpub.go
  vendor/github.com/pelletier/go-toml/tomltree_create.go
  vendor/github.com/pelletier/go-toml/tomltree_write.go
  vendor/github.com/pelletier/go-toml/tomltree_writepub.go
  vendor/modules.txt
Labels: kind/failing-test, approved, cncf-cla: yes, size/XXL

#2461 fix: checkDiskLun throttling issue
  pkg/azuredisk/azuredisk.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2472 fix: upgrade csi-provisioner to v5.0.2 to fix pv deletion stuck issue
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
Labels: kind/bug, size/M, approved, cncf-cla: yes

#2466 [release-1.28] test: use workload identity for e2e test
  go.mod
  go.sum
  hack/verify-examples.sh
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_detach_tester.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_tag_tester.go
  test/e2e/testsuites/dynamically_provisioned_external_rg_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_volume_snapshot_cross_region_tester.go
  test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
  test/integration/README.md
  test/integration/integration_test.go
  test/integration/run-test.sh
  test/integration/run-tests-all-clouds.sh
  test/sanity/sanity_test.go
  test/utils/azure/azure_helpers.go
  test/utils/credentials/credentials.go
  test/utils/credentials/credentials_test.go
  test/utils/testutil/testutil.go
  vendor/github.com/pelletier/go-toml/.dockerignore
  vendor/github.com/pelletier/go-toml/.gitignore
  vendor/github.com/pelletier/go-toml/CONTRIBUTING.md
  vendor/github.com/pelletier/go-toml/Dockerfile
  vendor/github.com/pelletier/go-toml/LICENSE
  vendor/github.com/pelletier/go-toml/Makefile
  vendor/github.com/pelletier/go-toml/PULL_REQUEST_TEMPLATE.md
  vendor/github.com/pelletier/go-toml/README.md
  vendor/github.com/pelletier/go-toml/SECURITY.md
  vendor/github.com/pelletier/go-toml/azure-pipelines.yml
  vendor/github.com/pelletier/go-toml/benchmark.sh
  vendor/github.com/pelletier/go-toml/doc.go
  vendor/github.com/pelletier/go-toml/example-crlf.toml
  vendor/github.com/pelletier/go-toml/example.toml
  vendor/github.com/pelletier/go-toml/fuzz.go
  vendor/github.com/pelletier/go-toml/fuzz.sh
  vendor/github.com/pelletier/go-toml/keysparsing.go
  vendor/github.com/pelletier/go-toml/lexer.go
  vendor/github.com/pelletier/go-toml/localtime.go
  vendor/github.com/pelletier/go-toml/marshal.go
  vendor/github.com/pelletier/go-toml/marshal_OrderPreserve_test.toml
  vendor/github.com/pelletier/go-toml/marshal_test.toml
  vendor/github.com/pelletier/go-toml/parser.go
  vendor/github.com/pelletier/go-toml/position.go
  vendor/github.com/pelletier/go-toml/token.go
  vendor/github.com/pelletier/go-toml/toml.go
  vendor/github.com/pelletier/go-toml/tomlpub.go
  vendor/github.com/pelletier/go-toml/tomltree_create.go
  vendor/github.com/pelletier/go-toml/tomltree_write.go
  vendor/github.com/pelletier/go-toml/tomltree_writepub.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/XXL

#2476 fix: upgrade csi-provisioner to v5.0.2 to fix pv deletion stuck issue on v1.30.3, v1.29.8 charts
  charts/v1.29.8/azuredisk-csi-driver-v1.29.8.tgz
  charts/v1.29.8/azuredisk-csi-driver/values.yaml
  charts/v1.30.3/azuredisk-csi-driver-v1.30.3.tgz
  charts/v1.30.3/azuredisk-csi-driver/values.yaml
  deploy/v1.29.8/csi-azuredisk-controller.yaml
  deploy/v1.30.3/csi-azuredisk-controller.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2475 [release-1.30] fix: upgrade csi-provisioner to v5.0.2 to fix pv deletion stuck issue
  charts/latest/azuredisk-csi-driver-v1.29.8.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes
