Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2024-07, with the labels that each got.

#2389 test: fix trivy action failure
  .github/workflows/trivy.yaml
Labels: size/XS, approved, cncf-cla: yes

#2383 feat: add ReservedDataDiskSlotNum to helm-chart
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
Labels: kind/feature, size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#2393 [release-1.29] feat: add ReservedDataDiskSlotNum to helm-chart
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.29.7.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2394 [release-1.30] feat: add ReservedDataDiskSlotNum to helm-chart
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.30.1.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2388 feat: add tagValueDelimiter parameter
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azureutils/azure_disk_utils.go
  pkg/util/util.go
  pkg/util/util_test.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_tag_tester.go
Labels: kind/feature, size/M, approved, cncf-cla: yes, ok-to-test

#2399 fix: reservedDataDiskSlotNum chart setting in v1.29.7
  charts/v1.29.7/azuredisk-csi-driver-v1.29.7.tgz
  charts/v1.29.7/azuredisk-csi-driver/values.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2404 fix: managed identity token refresh issue
  go.mod
  go.sum
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/README.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/TOKEN_CACHING.MD
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/TROUBLESHOOTING.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/azure_pipelines_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/errors.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/version.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/accounts_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/assets.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/autorest.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/blobcontainers_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/blobinventorypolicies_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/blobservices_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/ci.yml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/client_factory.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/deletedaccounts_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/encryptionscopes_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/fileservices_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/fileshares_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/localusers_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/managementpolicies_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/models.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/models_serde.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/networksecurityperimeterconfigurations_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/objectreplicationpolicies_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/operations_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/options.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/privateendpointconnections_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/privatelinkresources_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/queue_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/queueservices_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/responses.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/skus_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/table_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/tableservices_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/taskassignmentinstancesreport_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/taskassignments_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/taskassignmentsinstancesreport_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/time_rfc3339.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/usages_client.go
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/types/label_filter.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/k8s.io/utils/net/multi_listen.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/armauth/expire_early_wrapper.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/auth.go
Labels: kind/bug, approved, cncf-cla: yes, size/XXL

#2397 [release-1.29] feat: add tagValueDelimiter parameter
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azureutils/azure_disk_utils.go
  pkg/util/util.go
  pkg/util/util_test.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_tag_tester.go
Labels: kind/feature, size/M, approved, cncf-cla: yes, ok-to-test

#2406 test: upgrade csi-test to v5.2.0 for more test coverage
  test/sanity/run-tests-all-clouds.sh
Labels: size/XS, approved, cncf-cla: yes, kind/test

#2344 feat: Implement KEP3751 ("ControllerModifyVolume")
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  deploy/example/modifyvolume/README.md
  deploy/example/modifyvolume/storageclass-azuredisk-csi-premiumv2.yaml
  deploy/example/modifyvolume/volumeattributesclass.yaml
  deploy/rbac-csi-azuredisk-controller.yaml
  hack/verify-yamllint.sh
  pkg/azuredisk/azure_managedDiskController.go
  pkg/azuredisk/azure_managedDiskController_test.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azuredisk/fake_azuredisk_v2.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
  test/sanity/run-test.sh
Labels: kind/feature, size/XL, approved, cncf-cla: yes, ok-to-test

#2411 [release-1.30] feat: Implement KEP3751 ("ControllerModifyVolume")
  charts/latest/azuredisk-csi-driver-v1.30.2.tgz
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  deploy/example/modifyvolume/README.md
  deploy/example/modifyvolume/storageclass-azuredisk-csi-premiumv2.yaml
  deploy/example/modifyvolume/volumeattributesclass.yaml
  deploy/rbac-csi-azuredisk-controller.yaml
  hack/verify-yamllint.sh
  pkg/azuredisk/azure_managedDiskController.go
  pkg/azuredisk/azure_managedDiskController_test.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azuredisk/fake_azuredisk_v2.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
  test/sanity/run-test.sh
Labels: kind/feature, size/XL, approved, lgtm, cncf-cla: yes, ok-to-test

#2420 [release-1.28] fix: CVE-2024-5321
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  vendor/k8s.io/kubernetes/pkg/securitycontext/util.go
  vendor/k8s.io/kubernetes/test/e2e/storage/utils/create.go
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-attacher/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-health-monitor/external-health-monitor-controller/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-provisioner/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-resizer/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-snapshotter/csi-snapshotter/rbac-csi-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/README.md
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-driverinfo.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-testing.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-attacher.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-resizer.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/update-hostpath.sh
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/L

#2417 fix: CVE-2024-5321
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  vendor/k8s.io/kubernetes/pkg/securitycontext/util.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/defaultfs.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_unix.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_windows.go
  vendor/k8s.io/kubernetes/pkg/volume/plugins.go
  vendor/k8s.io/kubernetes/test/e2e/storage/utils/create.go
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-attacher/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-health-monitor/external-health-monitor-controller/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-provisioner/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-resizer/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-snapshotter/csi-snapshotter/rbac-csi-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/README.md
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-driverinfo.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-testing.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-attacher.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-resizer.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/update-hostpath.sh
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, size/XL, approved, cncf-cla: yes

#2418 [release-1.30] fix: CVE-2024-5321
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  vendor/k8s.io/kubernetes/pkg/securitycontext/util.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/defaultfs.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_unix.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_windows.go
  vendor/k8s.io/kubernetes/pkg/volume/plugins.go
  vendor/k8s.io/kubernetes/test/e2e/storage/utils/create.go
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-attacher/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-health-monitor/external-health-monitor-controller/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-provisioner/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-resizer/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-snapshotter/csi-snapshotter/rbac-csi-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/README.md
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-driverinfo.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-testing.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-attacher.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-resizer.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/update-hostpath.sh
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, size/XL, approved, cncf-cla: yes

#2424 [release-1.29] fix: increase azuredisk container memory limits as 600Mi
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.29.7.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2422 fix: increase azuredisk container memory limits as 600Mi
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2423 [release-1.30] fix: increase azuredisk container memory limits as 600Mi
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.30.2.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2425 [release-1.28] fix: increase azuredisk container memory limits as 600Mi
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.28.9.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2427 doc: update new chart versions
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.30.2/azuredisk-csi-driver-v1.30.2.tgz
  charts/v1.30.2/azuredisk-csi-driver/Chart.yaml
  charts/v1.30.2/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.30.2/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.30.2/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.30.2/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.30.2/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.30.2/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/v1.30.2/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.30.2/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.30.2/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.30.2/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.30.2/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.30.2/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.30.2/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.30.2/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.30.2/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.30.2/azuredisk-csi-driver/values.yaml
  deploy/v1.30.2/crd-csi-snapshot.yaml
  deploy/v1.30.2/csi-azuredisk-controller.yaml
  deploy/v1.30.2/csi-azuredisk-driver.yaml
  deploy/v1.30.2/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.30.2/csi-azuredisk-node-windows.yaml
  deploy/v1.30.2/csi-azuredisk-node.yaml
  deploy/v1.30.2/csi-snapshot-controller.yaml
  deploy/v1.30.2/rbac-csi-azuredisk-controller.yaml
  deploy/v1.30.2/rbac-csi-azuredisk-node.yaml
  deploy/v1.30.2/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.30.2.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#2428 test: change default windows tests to use ltsc2022 image
  deploy/example/windows/deployment.yaml
  deploy/example/windows/statefulset.yaml
  hack/verify-examples.sh
Labels: size/S, approved, cncf-cla: yes, kind/test

#2429 feat: support NVME disk
  pkg/azuredisk/azure_common_linux.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2439 fix: add pv patch permission with HonorPVReclaimPolicy enabled
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.29.7/azuredisk-csi-driver-v1.29.7.tgz
  charts/v1.29.7/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.30.1/azuredisk-csi-driver-v1.30.1.tgz
  charts/v1.30.1/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.30.2/azuredisk-csi-driver-v1.30.2.tgz
  charts/v1.30.2/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  deploy/rbac-csi-azuredisk-controller.yaml
  deploy/v1.29.7/rbac-csi-azuredisk-controller.yaml
  deploy/v1.30.1/rbac-csi-azuredisk-controller.yaml
  deploy/v1.30.2/rbac-csi-azuredisk-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2440 [release-1.30] fix: add pv patch permission with HonorPVReclaimPolicy enabled
  charts/latest/azuredisk-csi-driver-v1.30.2.tgz
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.30.1/azuredisk-csi-driver-v1.30.1.tgz
  charts/v1.30.1/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.30.2/azuredisk-csi-driver-v1.30.2.tgz
  charts/v1.30.2/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  deploy/rbac-csi-azuredisk-controller.yaml
  deploy/v1.30.2/rbac-csi-azuredisk-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2441 [release-1.29] fix: add pv patch permission with HonorPVReclaimPolicy enabled
  charts/latest/azuredisk-csi-driver-v1.29.7.tgz
  charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.29.7/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  deploy/rbac-csi-azuredisk-controller.yaml
  deploy/v1.29.7/rbac-csi-azuredisk-controller.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes
