Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2025-08, with the labels that each got.

#3252 chore: upgrade Azure cloud provider lib
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets_repo.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/config/azure_cache.go
Labels: size/S, approved, cncf-cla: yes, kind/cleanup

#3253 [release-1.33] chore: upgrade Azure cloud provider lib
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets_repo.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/config/azure_cache.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#3247 chore: add an option to configure instance-view param in VMSS VM list API
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_option.go
Labels: kind/feature, do-not-merge/hold, size/XS, approved, lgtm, cncf-cla: yes

#3268 perf: rely on readyToUse flag to monitor snapshot progress
  pkg/azuredisk/azuredisk_option.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azureutils/azure_snapshot_utils.go
  pkg/azureutils/azure_snapshot_utils_test.go
Labels: kind/bug, size/XL, approved, cncf-cla: yes

#3271 chore: upgrade CSI driver sidecar images
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/feature, size/S, approved, lgtm, cncf-cla: yes

#3272 [release-1.33] chore: upgrade CSI driver sidecar images
  charts/latest/azuredisk-csi-driver-1.33.4.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#3279 test: disable MaximumDataDisksExceeded flaky test case
  test/e2e/dynamic_provisioning_test.go
Labels: kind/flake, size/XS, approved, cncf-cla: yes

#3282 test: ignore latest tgz file in helm chart index verification
  hack/verify-helm-chart-index.sh
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#3288 fix: CVE-2025-5187
  go.mod
  go.sum
  vendor/k8s.io/component-helpers/resource/helpers.go
  vendor/k8s.io/kubelet/pkg/apis/stats/v1alpha1/types.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/L

#3290 [release-1.32] fix: CVE-2025-5187
  go.mod
  go.sum
  vendor/k8s.io/api/resource/v1alpha3/generated.proto
  vendor/k8s.io/api/resource/v1alpha3/types.go
  vendor/k8s.io/api/resource/v1alpha3/types_swagger_doc_generated.go
  vendor/k8s.io/api/resource/v1beta1/generated.proto
  vendor/k8s.io/api/resource/v1beta1/types.go
  vendor/k8s.io/api/resource/v1beta1/types_swagger_doc_generated.go
  vendor/k8s.io/apiserver/pkg/cel/library/cidr.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
  vendor/k8s.io/csi-translation-lib/plugins/portworx.go
  vendor/k8s.io/dynamic-resource-allocation/cel/cache.go
  vendor/k8s.io/dynamic-resource-allocation/cel/compile.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, size/XL, approved, cncf-cla: yes
