Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2025-03, with the labels that each got.

#2909 chore: upgrade Azure cloud provider lib
  go.mod
  go.sum
  vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/internal/oauth/ops/accesstokens/accesstokens.go
  vendor/golang.org/x/exp/slices/slices.go
  vendor/golang.org/x/exp/slices/sort.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
Labels: kind/feature, approved, cncf-cla: yes, size/L

#2911 fix: incorrect cloud provider setting in sovereign cloud
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_publicip_repo.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_routes.go
Labels: kind/bug, size/M, approved, lgtm, cncf-cla: yes

#2913 fix: merge mutable parameters for disk creation to support ModifyVolume changes
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#2908 doc: cut v1.32.0 release
  README.md
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-1.32.0.tgz
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/v1.32.0/azuredisk-csi-driver-1.32.0.tgz
  charts/v1.32.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.32.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.32.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.32.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.32.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.32.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.32.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/v1.32.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.32.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.32.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.32.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.32.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.32.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.32.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.32.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.32.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.32.0/azuredisk-csi-driver/values.yaml
  deploy/v1.32.0/crd-csi-snapshot.yaml
  deploy/v1.32.0/csi-azuredisk-controller.yaml
  deploy/v1.32.0/csi-azuredisk-driver.yaml
  deploy/v1.32.0/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.32.0/csi-azuredisk-node-windows.yaml
  deploy/v1.32.0/csi-azuredisk-node.yaml
  deploy/v1.32.0/csi-snapshot-controller.yaml
  deploy/v1.32.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.32.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.32.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.32.0.md
  pkg/optimization/azure_skus_map.go
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#2923 chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2922 fix: avoid duplicate ssl mounts on Fedora node in AzureStack environment
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-1.32.0.tgz
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.32.0/azuredisk-csi-driver-1.32.0.tgz
  charts/v1.32.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.32.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/L

#2925 [release-1.31] chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/azuredisk-csi-driver-1.31.5.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2926 [release-1.32] chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/azuredisk-csi-driver-1.32.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2929 [release-1.30] fix: avoid duplicate ssl mounts on Fedora node in AzureStack environment
  charts/latest/azuredisk-csi-driver-v1.30.9.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2928 [release-1.31] fix: avoid duplicate ssl mounts on Fedora node in AzureStack environment
  charts/latest/azuredisk-csi-driver-1.31.5.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2927 [release-1.32] fix: avoid duplicate ssl mounts on Fedora node in AzureStack environment
  charts/latest/azuredisk-csi-driver-1.32.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.32.0/azuredisk-csi-driver-1.32.0.tgz
  charts/v1.32.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.32.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
Labels: kind/bug, size/M, approved, cncf-cla: yes

#2931 chore: increase liveness-probe timeout
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.30.9/azuredisk-csi-driver-v1.30.9.tgz
  charts/v1.30.9/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.31.5/azuredisk-csi-driver-1.31.5.tgz
  charts/v1.31.5/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.32.0/azuredisk-csi-driver-1.32.0.tgz
  charts/v1.32.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  deploy/csi-azuredisk-node.yaml
  deploy/v1.30.9/csi-azuredisk-node.yaml
  deploy/v1.31.5/csi-azuredisk-node.yaml
  deploy/v1.32.0/csi-azuredisk-node.yaml
Labels: kind/bug, size/M, approved, cncf-cla: yes

#2932 [release-1.32] chore: increase liveness-probe timeout
  charts/latest/azuredisk-csi-driver-1.32.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.32.0/azuredisk-csi-driver-1.32.0.tgz
  charts/v1.32.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  deploy/csi-azuredisk-node.yaml
  deploy/v1.32.0/csi-azuredisk-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2934 fix: avoid get disk call in disk creation
  pkg/azuredisk/azure_managedDiskController.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#2936 chore: refine GetDisk operation
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azure_controller_common_test.go
  pkg/azuredisk/azure_managedDiskController.go
  pkg/azuredisk/azure_managedDiskController_test.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
Labels: approved, cncf-cla: yes, size/L, kind/cleanup

#2941 fix: reduce get disk calls in disk attach/detach on VMSS
  .github/workflows/static.yaml
  go.mod
  go.sum
  pkg/azuredisk/azure_common_windows.go
  pkg/azureutils/azure_disk_utils.go
  pkg/csi-common/utils.go
  vendor/github.com/Azure/msi-dataplane/pkg/dataplane/reloadCredentials.go
  vendor/github.com/prometheus/client_golang/prometheus/atomic_update.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_darwin.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_mem_cgo_darwin.c
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_mem_cgo_darwin.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_mem_nocgo_darwin.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_not_supported.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_procfsenabled.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/go.opentelemetry.io/otel/exporters/prometheus/exporter.go
  vendor/go.opentelemetry.io/otel/sdk/metric/internal/aggregate/exponential_histogram.go
  vendor/go.opentelemetry.io/otel/sdk/metric/version.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#2942 [release-1.32] fix: reduce get disk calls in disk attach/detach on VMSS
  .github/workflows/static.yaml
  go.mod
  go.sum
  pkg/azuredisk/azure_common_windows.go
  pkg/azureutils/azure_disk_utils.go
  pkg/csi-common/utils.go
  vendor/github.com/Azure/msi-dataplane/pkg/dataplane/reloadCredentials.go
  vendor/github.com/prometheus/client_golang/prometheus/atomic_update.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_darwin.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_mem_cgo_darwin.c
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_mem_cgo_darwin.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_mem_nocgo_darwin.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_not_supported.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_procfsenabled.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/go.opentelemetry.io/otel/exporters/prometheus/exporter.go
  vendor/go.opentelemetry.io/otel/sdk/metric/internal/aggregate/exponential_histogram.go
  vendor/go.opentelemetry.io/otel/sdk/metric/version.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#2945 chore: update max data disk count table
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2950 Update README.md
  deploy/example/sharedisk/README.md
Labels: size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#2949 fix: merge OTEL metrics with legacy registerer
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/trace/provider.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2952 feat: add metrics on node
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node.yaml
  pkg/azuredisk/nodeserver.go
  test/utils/azuredisk_log.sh
Labels: kind/feature, size/M, approved, cncf-cla: yes

#2954 [release-1.32] feat: add metrics on node
  charts/README.md
  charts/latest/azuredisk-csi-driver-1.32.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node.yaml
  pkg/azuredisk/nodeserver.go
  test/utils/azuredisk_log.sh
Labels: kind/feature, size/M, approved, cncf-cla: yes

#2955 chore: upgrade base image alpine to v1.18.12
  pkg/azurediskplugin/Dockerfile
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2963 fix: CVE-2025-30204
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v5/README.md
  vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
  vendor/github.com/golang-jwt/jwt/v5/parser.go
  vendor/github.com/golang-jwt/jwt/v5/token.go
  vendor/modules.txt
Labels: kind/bug, size/M, approved, cncf-cla: yes

#2962 [release-1.29] fix: CVE-2025-30204
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v5/README.md
  vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
  vendor/github.com/golang-jwt/jwt/v5/parser.go
  vendor/github.com/golang-jwt/jwt/v5/token.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/L

#2961 [release-1.30] fix: CVE-2025-30204
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v5/README.md
  vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
  vendor/github.com/golang-jwt/jwt/v5/parser.go
  vendor/github.com/golang-jwt/jwt/v5/token.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/L

#2960 [release-1.31] fix: CVE-2025-30204
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v5/README.md
  vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
  vendor/github.com/golang-jwt/jwt/v5/parser.go
  vendor/github.com/golang-jwt/jwt/v5/token.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/L

#2977 fix: increase TaintRemovalInitialDelay as 30s
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_option.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#2982 [release-1.32] chore: add node.removeNotReadyTaint parameter to helm chart
  charts/README.md
  charts/latest/azuredisk-csi-driver-1.32.1.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/latest/azuredisk-csi-driver/values.yaml
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#2981 [release-1.31] fix: increase TaintRemovalInitialDelay as 30s
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_option.go
Labels: kind/bug, size/M, approved, cncf-cla: yes
