Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2025-04, with the labels that each got.

#2986 chore: increase snapshot worker-threads from 10 to 100
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2987 [release-1.32] chore: increase snapshot worker-threads from 10 to 100
  charts/latest/azuredisk-csi-driver-1.32.1.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2988 [release-1.31] chore: increase snapshot worker-threads from 10 to 100
  charts/latest/azuredisk-csi-driver-1.31.6.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2989 chore: increase retry-interval-max in snapshot controller
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2992 fix: detach disk should have more priority than attach disk on the same node
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azure_controller_common_test.go
  pkg/azuredisk/azure_managedDiskController.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_option.go
  pkg/azuredisk/controllerserver.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#2995 [release-1.30] fix: detach disk should have more priority than attach disk on the same node
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azure_controller_common_test.go
  pkg/azuredisk/azure_managedDiskController.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_option.go
  pkg/azuredisk/controllerserver.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#2994 [release-1.31] fix: detach disk should have more priority than attach disk on the same node
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azure_controller_common_test.go
  pkg/azuredisk/azure_managedDiskController.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_option.go
  pkg/azuredisk/controllerserver.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#2536 feat: add VerticalPodAutoscaler to csi controller pod
  deploy/example/vpa/README.md
  deploy/example/vpa/install-components/admission-controller-deployment.yaml
  deploy/example/vpa/install-components/delete-webhook.sh
  deploy/example/vpa/install-components/gencerts.sh
  deploy/example/vpa/install-components/recommender-deployment.yaml
  deploy/example/vpa/install-components/rmcerts.sh
  deploy/example/vpa/install-components/updater-deployment.yaml
  deploy/example/vpa/install-components/vpa-rbac.yaml
  deploy/example/vpa/install-components/vpa-v1-crd-gen.yaml
  deploy/example/vpa/install-components/warn-obsolete-vpa-objects.sh
  deploy/example/vpa/install-vpa.sh
  deploy/example/vpa/uninstall-vpa.sh
  deploy/example/vpa/vertical-pod-autoscaler.yaml
  hack/verify-yamllint.sh
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/XXL, ok-to-test

#3005 test: fix CVE-2025-22871 in trivy action
  .github/workflows/trivy.yaml
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#3012 [release-1.32] chore: upgrade snapshot CRD to v8.2.0
  charts/latest/azuredisk-csi-driver-1.32.2.tgz
  charts/latest/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  deploy/crd-csi-snapshot.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/XXL

#3011 chore: increase snapshot worker-threads from 100 to 250
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#3014 cleanup: remove DisableUpdateCache flag
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_option.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/controllerserver.go
Labels: size/XS, approved, cncf-cla: yes, kind/cleanup

#3022 fix: remove unnecessary get vmss call during disk attach
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmssflex.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#3023 cleanup: add one log for dangling volume issue
  pkg/azuredisk/azure_controller_common.go
Labels: size/XS, approved, cncf-cla: yes, kind/cleanup

#3030 [release-1.31] fix: CVE-2025-22872
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_asm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_loong64.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_linux_noinit.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.s
  vendor/golang.org/x/sys/cpu/parse.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/registry/key.go
  vendor/golang.org/x/sys/windows/registry/value.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/XXL

#3031 [release-1.30] fix: CVE-2025-22872
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_asm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_loong64.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_linux_noinit.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.s
  vendor/golang.org/x/sys/cpu/parse.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/registry/key.go
  vendor/golang.org/x/sys/windows/registry/value.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/XXL

#3032 [release-1.29] fix: CVE-2025-22872
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_asm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_loong64.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_linux_noinit.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.s
  vendor/golang.org/x/sys/cpu/parse.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/registry/key.go
  vendor/golang.org/x/sys/windows/registry/value.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/XXL

#3033 [release-1.28] fix: CVE-2025-22872
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_asm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_loong64.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_linux_noinit.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.s
  vendor/golang.org/x/sys/cpu/parse.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/registry/key.go
  vendor/golang.org/x/sys/windows/registry/value.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/XXL

#3038 fix: incorrect disk num discovery on Windows 2019 node
  pkg/mounter/safe_mounter_host_process_windows.go
  pkg/os/disk/disk.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#3047 fix: disk detach failure on AzureStack Hub
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmssflex.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#3048 [release-1.32] fix: disk detach failure on AzureStack Hub
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmssflex.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#3053 [release-1.32] cleanup: revert to go1.23
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
Labels: size/M, approved, lgtm, cncf-cla: yes, kind/cleanup

#3054 cleanup: add toolchain in go.mod to unblock autobot upgrade
  go.mod
Labels: size/XS, approved, cncf-cla: yes, kind/cleanup

#3056 [release-1.32] chore: upgrade snapshot sidecar image to v8.2.1
  charts/README.md
  charts/latest/azuredisk-csi-driver-1.32.4.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#3058 fix: vpa install and uninstall script
  deploy/example/vpa/install-vpa.sh
  deploy/example/vpa/uninstall-vpa.sh
Labels: kind/bug, size/XS, needs-ok-to-test, approved, lgtm, cncf-cla: yes

#3059 chore: upgrade mount-utils
  go.mod
  go.sum
  vendor/k8s.io/mount-utils/doc.go
  vendor/k8s.io/mount-utils/mount_linux.go
  vendor/k8s.io/mount-utils/mount_windows.go
  vendor/modules.txt
Labels: kind/feature, size/M, approved, cncf-cla: yes

#3050 feat: Use WMI to implement Disk API to reduce PowerShell overhead#2
  pkg/mounter/safe_mounter_host_process_windows.go
  pkg/os/cim/disk.go
  pkg/os/disk/disk.go
  pkg/os/disk/disk_cim.go
  pkg/os/volume/volume_cim.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes

#3060 cleanup: refine resize volume error logging on Windows node using WMI API
  pkg/os/volume/volume_cim.go
Labels: size/XS, approved, cncf-cla: yes, kind/cleanup

#3061 doc: fix snapshot crd illegal characters
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#3062 chore: update max data disk count table
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: approved, cncf-cla: yes, size/XXL, kind/cleanup

#3066 [release-1.32] doc: fix snapshot crd illegal characters
  charts/latest/azuredisk-csi-driver-1.32.4.tgz
  charts/latest/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  deploy/crd-csi-snapshot.yaml
Labels: kind/documentation, size/XS, approved, cncf-cla: yes
