Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2025-06, with the labels that each got.

#3122 chore: update max data disk count table
  pkg/azuredisk/azure_dd_max_disk_count.go
  test/e2e/dynamic_provisioning_test.go
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#3123 chore: migrate csi driver sidecar images to dalec images
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: size/S, approved, cncf-cla: yes, kind/cleanup

#3130 [release-1.33] chore: migrate csi driver sidecar images to dalec images
  charts/latest/azuredisk-csi-driver-1.33.1.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: size/S, approved, cncf-cla: yes, kind/cleanup

#3145 [release-1.31] chore: upgrade alpine base image `release 1.31`
  pkg/azuredisk/azure_common_linux.go
  pkg/azurediskplugin/Dockerfile
Labels: size/XS, approved, lgtm, cncf-cla: yes, kind/cleanup, ok-to-test

#3149 fix: make disk and snapshot uri regex case insensitive everywhere
  pkg/azureconstants/azure_constants.go
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azure_controller_common_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#3155 chore: CVE-2025-4563 update k8s pkg
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
  vendor/k8s.io/kubernetes/pkg/kubelet/config/common.go
  vendor/k8s.io/kubernetes/pkg/util/kernel/constants.go
  vendor/k8s.io/kubernetes/pkg/volume/util/resize_util.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: size/M, approved, lgtm, cncf-cla: yes

#3150 Remove references to the V2 driver
  Makefile
  deploy/example/azdiskschedulerextender/nginx-pod-with-azschedulerextender.yaml
  deploy/example/failover/README.md
  deploy/install-driver.sh
  deploy/uninstall-driver.sh
  docs/csi-dev.md
  docs/design-v2.md
  pkg/azuredisk/azure_common_darwin.go
  pkg/azuredisk/azure_common_linux.go
  pkg/azuredisk/azure_common_windows.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/azuredisk_v1.go
  pkg/azuredisk/azuredisk_v1_test.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azuredisk/fake_azuredisk_v1.go
  pkg/azuredisk/fake_azuredisk_v2.go
  pkg/azuredisk/identityserver_v2.go
  pkg/azuredisk/nodeserver_v2.go
  test/e2e/README.md
  test/sanity/run-test.sh
  test/sanity/sanity_test.go
Labels: approved, lgtm, cncf-cla: yes, size/XXL, kind/cleanup

#3154 chore: add new owners to the owners list
  OWNERS
Labels: size/XS, approved, lgtm, cncf-cla: yes

#3158 [release-1.32] fix: CVE-2025-4563
  deploy/example/statefulset.yaml
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/features/versioned_kube_features.go
  vendor/k8s.io/kubernetes/pkg/kubelet/config/common.go
  vendor/k8s.io/kubernetes/pkg/util/kernel/constants.go
  vendor/k8s.io/kubernetes/pkg/volume/util/resize_util.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, size/M, approved, cncf-cla: yes

#3148 fix(doc): fixing typo in the doc
  docs/install-csi-driver-master.md
  docs/install-csi-driver-v1.13.0.md
  docs/install-csi-driver-v1.14.0.md
  docs/install-csi-driver-v1.15.0.md
  docs/install-csi-driver-v1.16.0.md
  docs/install-csi-driver-v1.17.0.md
  docs/install-csi-driver-v1.18.0.md
  docs/install-csi-driver-v1.19.0.md
  docs/install-csi-driver-v1.20.0.md
  docs/install-csi-driver-v1.21.0.md
  docs/install-csi-driver-v1.22.0.md
  docs/install-csi-driver-v1.23.0.md
  docs/install-csi-driver-v1.24.0.md
  docs/install-csi-driver-v1.25.0.md
  docs/install-csi-driver-v1.26.0.md
  docs/install-csi-driver-v1.26.6.md
  docs/install-csi-driver-v1.26.7.md
  docs/install-csi-driver-v1.26.8.md
  docs/install-csi-driver-v1.27.1.md
  docs/install-csi-driver-v1.28.10.md
  docs/install-csi-driver-v1.28.11.md
  docs/install-csi-driver-v1.28.2.md
  docs/install-csi-driver-v1.28.3.md
  docs/install-csi-driver-v1.28.4.md
  docs/install-csi-driver-v1.28.5.md
  docs/install-csi-driver-v1.28.7.md
  docs/install-csi-driver-v1.28.9.md
  docs/install-csi-driver-v1.29.0.md
  docs/install-csi-driver-v1.29.1.md
  docs/install-csi-driver-v1.29.10.md
  docs/install-csi-driver-v1.29.11.md
  docs/install-csi-driver-v1.29.12.md
  docs/install-csi-driver-v1.29.2.md
  docs/install-csi-driver-v1.29.5.md
  docs/install-csi-driver-v1.29.7.md
  docs/install-csi-driver-v1.29.8.md
  docs/install-csi-driver-v1.30.0.md
  docs/install-csi-driver-v1.30.1.md
  docs/install-csi-driver-v1.30.10.md
  docs/install-csi-driver-v1.30.2.md
  docs/install-csi-driver-v1.30.3.md
  docs/install-csi-driver-v1.30.5.md
  docs/install-csi-driver-v1.30.6.md
  docs/install-csi-driver-v1.30.7.md
  docs/install-csi-driver-v1.30.9.md
  docs/install-csi-driver-v1.31.0.md
  docs/install-csi-driver-v1.31.1.md
  docs/install-csi-driver-v1.31.10.md
  docs/install-csi-driver-v1.31.2.md
  docs/install-csi-driver-v1.31.5.md
  docs/install-csi-driver-v1.31.6.md
  docs/install-csi-driver-v1.32.0.md
  docs/install-csi-driver-v1.32.1.md
  docs/install-csi-driver-v1.32.7.md
  docs/install-csi-driver-v1.33.0.md
  docs/install-csi-driver-v1.33.1.md
Labels: kind/documentation, approved, lgtm, cncf-cla: yes, size/L, ok-to-test
