Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2025-05, with the labels that each got.

#3068 doc: fix snapshot crd illegal characters in deploy
  deploy/crd-csi-snapshot.yaml
Labels: kind/documentation, size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#3039 fix: adjust the batch size as per the number of disks allowed
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_option.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
  pkg/azuredisk/nodeserver_v2.go
Labels: size/M, approved, lgtm, cncf-cla: yes

#3071 fix: bump mount-utils to fix volume resizing failure when there are nfs unresponsive volumes
  go.mod
  go.sum
  vendor/k8s.io/mount-utils/mount.go
  vendor/k8s.io/mount-utils/mount_helper_unix.go
  vendor/k8s.io/mount-utils/resizefs_linux.go
  vendor/k8s.io/utils/clock/testing/fake_clock.go
  vendor/modules.txt
Labels: approved, lgtm, cncf-cla: yes, size/L

#3074 cleanup: only wait for disk detach when hit MaximumDataDisksExceeded error
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azure_controller_common_test.go
  pkg/azuredisk/azure_managedDiskController.go
  pkg/util/util.go
Labels: size/M, approved, cncf-cla: yes, kind/cleanup

#3075 [release-1.31] fix: adjust the batch size as per the number of disks allowed
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_option.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
  pkg/azuredisk/nodeserver_v2.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#3077 [release-1.30] fix: adjust the batch size as per the number of disks allowed
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_option.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/nodeserver.go
  pkg/azuredisk/nodeserver_test.go
  pkg/azuredisk/nodeserver_v2.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#3078 [release-1.31] cleanup: only wait for disk detach when hit MaximumDataDisksExceeded
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azure_controller_common_test.go
  pkg/azuredisk/azure_managedDiskController.go
  pkg/util/util.go
Labels: size/M, approved, cncf-cla: yes, kind/cleanup

#3080 test: improve TestGetMaxDataDiskCount unit test
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/nodeserver_test.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#3087 chore: update max data disk count table
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#3092 chore: upgrade Azure cloud provider lib
  go.mod
  go.sum
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/agentpools_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/assets.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/autorest.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/ci.yml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/machines_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/maintenanceconfigurations_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/managedclusters_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/models.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/models_serde.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/operations_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/privateendpointconnections_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/privatelinkresources_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/resolveprivatelinkserviceid_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/snapshots_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/trustedaccessrolebindings_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/trustedaccessroles_client.go
  vendor/golang.org/x/tools/go/ast/inspector/inspector.go
  vendor/golang.org/x/tools/go/ast/inspector/typeof.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/arm_conf.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/policy/retryaftermin/retryaftermin.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualnetworklinkclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualnetworklinkclient/mock_virtualnetworklinkclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualnetworklinkclient/zz_generated_client.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes

#3093 [release-1.32] chore: upgrade Azure cloud provider lib
  go.mod
  go.sum
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/agentpools_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/assets.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/autorest.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/ci.yml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/machines_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/maintenanceconfigurations_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/managedclusters_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/models.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/models_serde.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/operations_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/privateendpointconnections_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/privatelinkresources_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/resolveprivatelinkserviceid_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/snapshots_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/trustedaccessrolebindings_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/trustedaccessroles_client.go
  vendor/golang.org/x/crypto/ssh/mlkem.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_riscv64.go
  vendor/golang.org/x/sys/cpu/cpu_riscv64.go
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/golang.org/x/tools/go/ast/inspector/inspector.go
  vendor/golang.org/x/tools/go/ast/inspector/typeof.go
  vendor/k8s.io/utils/clock/testing/fake_clock.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/arm_conf.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/policy/retryaftermin/retryaftermin.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualnetworklinkclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualnetworklinkclient/mock_virtualnetworklinkclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualnetworklinkclient/zz_generated_client.go
Labels: kind/feature, approved, cncf-cla: yes, size/XXL

#3091 fix: vmss flex node naming parsing issue
  pkg/azuredisk/nodeserver.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#3097 [release-1.32] feat: add option to override ARM retry-after header
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_option.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/controllerserver.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#3098 [release-1.31] feat: add option to override ARM retry-after header
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_option.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/controllerserver.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#3081 feat: add option to override ARM retry-after header if the value is lower than the configured minimum
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_option.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/controllerserver.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
Labels: kind/feature, size/S, approved, lgtm, cncf-cla: yes

#3101 doc: cut v1.33.0 release
  README.md
  charts/index.yaml
  charts/latest/azuredisk-csi-driver-1.33.0.tgz
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/v1.33.0/azuredisk-csi-driver-1.33.0.tgz
  charts/v1.33.0/azuredisk-csi-driver/Chart.yaml
  charts/v1.33.0/azuredisk-csi-driver/templates/NOTES.txt
  charts/v1.33.0/azuredisk-csi-driver/templates/_helpers.tpl
  charts/v1.33.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.33.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/v1.33.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  charts/v1.33.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows-hostprocess.yaml
  charts/v1.33.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
  charts/v1.33.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  charts/v1.33.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.33.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  charts/v1.33.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
  charts/v1.33.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.33.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  charts/v1.33.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  charts/v1.33.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.33.0/azuredisk-csi-driver/values.yaml
  deploy/v1.33.0/crd-csi-snapshot.yaml
  deploy/v1.33.0/csi-azuredisk-controller.yaml
  deploy/v1.33.0/csi-azuredisk-driver.yaml
  deploy/v1.33.0/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/v1.33.0/csi-azuredisk-node-windows.yaml
  deploy/v1.33.0/csi-azuredisk-node.yaml
  deploy/v1.33.0/csi-snapshot-controller.yaml
  deploy/v1.33.0/rbac-csi-azuredisk-controller.yaml
  deploy/v1.33.0/rbac-csi-azuredisk-node.yaml
  deploy/v1.33.0/rbac-csi-snapshot-controller.yaml
  docs/install-azuredisk-csi-driver.md
  docs/install-csi-driver-v1.33.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#3112 doc: add linked permissions
  docs/driver-parameters.md
Labels: kind/documentation, size/S, approved, lgtm, cncf-cla: yes

#3106 chore: upgrade alpine base image
  pkg/azuredisk/azure_common_linux.go
  pkg/azurediskplugin/Dockerfile
Labels: kind/feature, size/XS, approved, cncf-cla: yes
