Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2025-02, with the labels that each got.

#2850 fix: remove duplicated imagePullSecrets deployment config #2835 #2819
  charts/latest-v2/azuredisk-csi-driver-v2.0.0-beta.11.tgz
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-controller-cleanup.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
Labels: kind/bug, size/S, cncf-cla: yes, ok-to-test

#2843 test: refine UT for CreateSnapshot
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/controllerserver_test.go
Labels: size/XL, approved, lgtm, cncf-cla: yes, ok-to-test

#2852 test: fix CVE-2025-22866 in trivy action
  .github/workflows/trivy.yaml
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#2857 fix: set get disk timeout as 15s and make it configurable
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_option.go
  test/e2e/suite_test.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2863 [release-1.30] fix: set get disk timeout as 15s and make it configurable
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_option.go
  test/e2e/suite_test.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2862 chore: use GetInfoFromURI func to make URI parsing logic clear
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azure_managedDiskController.go
  pkg/azuredisk/azure_managedDiskController_test.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_v2.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_test.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azuredisk/fake_azuredisk.go
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_test.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_detach_tester.go
  test/e2e/testsuites/dynamically_provisioned_azuredisk_tag_tester.go
  test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
  test/e2e/testsuites/testsuites.go
Labels: size/XL, approved, cncf-cla: yes, kind/cleanup

#2859 fix: issue #2858 incorrect controller.affinity property processing
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#2867 [release-1.30] fix: incorrect affinity chart config
  charts/latest/azuredisk-csi-driver-v1.30.7.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2866 [release-1.31] fix: incorrect affinity chart config
  charts/latest/azuredisk-csi-driver-1.31.3.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2865 fix: obsolete vmss cache issue after disk is resized successfully
  pkg/azuredisk/controllerserver.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2868 chore: Upgrade alpine base image to 3.18.11
  pkg/azurediskplugin/Dockerfile
Labels: kind/feature, size/XS, approved, lgtm, cncf-cla: yes, ok-to-test

#2875 [release-1.31] fix: CVE-2025-0426
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/recyclerclient/recycler_client.go
  vendor/k8s.io/kubernetes/pkg/volume/util/util.go
  vendor/k8s.io/kubernetes/test/e2e/framework/flake_reporting_util.go
  vendor/k8s.io/kubernetes/test/e2e/framework/framework.go
  vendor/k8s.io/kubernetes/test/e2e/framework/node/resource.go
  vendor/k8s.io/kubernetes/test/e2e/framework/skipper/skipper.go
  vendor/k8s.io/kubernetes/test/utils/density_utils.go
  vendor/k8s.io/kubernetes/test/utils/deployment.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/k8s.io/kubernetes/test/utils/runners.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/L

#2874 fix: CVE-2025-0426
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/features/versioned_kube_features.go
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/gce-pd/controller_ss.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-attacher.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-resizer.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, size/M, approved, cncf-cla: yes

#2876 [release-1.30] fix: CVE-2025-0426
  go.mod
  go.sum
  vendor/go.opentelemetry.io/otel/metric/noop/noop.go
  vendor/k8s.io/api/admissionregistration/v1alpha1/types.go
  vendor/k8s.io/api/admissionregistration/v1beta1/types.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go
  vendor/k8s.io/apiserver/pkg/server/options/etcd.go
  vendor/k8s.io/apiserver/pkg/server/options/tracing.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/client-go/tools/remotecommand/v4.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/volume/util/atomic_writer.go
  vendor/k8s.io/kubernetes/pkg/volume/util/atomic_writer_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/atomic_writer_unsupported.go
  vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/recyclerclient/recycler_client.go
  vendor/k8s.io/kubernetes/pkg/volume/util/util.go
  vendor/k8s.io/kubernetes/test/e2e/framework/flake_reporting_util.go
  vendor/k8s.io/kubernetes/test/e2e/framework/framework.go
  vendor/k8s.io/kubernetes/test/e2e/framework/node/resource.go
  vendor/k8s.io/kubernetes/test/e2e/framework/skipper/skipper.go
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/scheduling/nvidia-driver-installer.yaml
  vendor/k8s.io/kubernetes/test/utils/density_utils.go
  vendor/k8s.io/kubernetes/test/utils/deployment.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/k8s.io/kubernetes/test/utils/runners.go
  vendor/k8s.io/mount-utils/mount_helper_unix.go
  vendor/k8s.io/mount-utils/mount_linux.go
  vendor/modules.txt
Labels: kind/bug, size/XL, approved, cncf-cla: yes

#2878 cleanup: remove unused unlock variable
  pkg/azuredisk/azure_controller_common.go
Labels: size/XS, approved, cncf-cla: yes, kind/cleanup

#2882 cleanup: add context parameter in a few functions
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azure_controller_common_test.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azuredisk/fake_azuredisk.go
Labels: approved, cncf-cla: yes, size/L, kind/cleanup

#2885 [release-1.31] cleanup: add context parameter in a few functions
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azure_controller_common_test.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
  pkg/azuredisk/controllerserver.go
  pkg/azuredisk/controllerserver_v2.go
  pkg/azuredisk/fake_azuredisk.go
Labels: approved, cncf-cla: yes, size/L, kind/cleanup

#2883 fix: disable batch attach when hitting MaximumDataDisksExceeded error
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azure_controller_common_test.go
  pkg/azuredisk/azure_managedDiskController.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#2890 [release-1.30] fix: disable batch attach when hitting MaximumDataDisksExceeded error
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azure_controller_common_test.go
  pkg/azuredisk/azure_managedDiskController.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#2889 [release-1.31] fix: disable batch attach when hitting MaximumDataDisksExceeded error
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azure_controller_common_test.go
  pkg/azuredisk/azure_managedDiskController.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#2894 fix: ignore GetDisk timeout during disk attach
  pkg/azuredisk/controllerserver.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2900 chore: update max data disk count table for D family v6 series
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/feature, size/M, lgtm, cncf-cla: yes, ok-to-test

#2905 chore: update max data disk count table
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/feature, size/M, approved, cncf-cla: yes
