Repository kubernetes-sigs/azuredisk-csi-driver, pull requests merged in 2025-01, with the labels that each got.

#2781 test: add UT for gen-disk-skus-map_test
  pkg/tool/gen-disk-skus-map.go
  pkg/tool/gen-disk-skus-map_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#2783 fix: get disk stuck issue
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/controllerserver_test.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2786 [release-1.29] fix: get disk stuck issue
  pkg/azuredisk/azuredisk.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2791 test: exclude some go fake files in ut coverage
  .github/workflows/linux.yml
Labels: size/XS, approved, cncf-cla: yes, kind/test

#2789 chore: set GoMaxProcs as 2
  pkg/azuredisk/azuredisk_option.go
  pkg/azurediskplugin/main.go
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2793 test: disable two redundant e2e tests
  test/e2e/dynamic_provisioning_test.go
Labels: size/XS, approved, cncf-cla: yes, kind/test

#2796 test: fix pv deletion timeout
  test/e2e/testsuites/testsuites.go
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#2800 chore: update max data disk count table
  pkg/azuredisk/azure_dd_max_disk_count.go
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2787 test: refine UT for gen-disk-skus-map_test
  pkg/tool/gen-disk-skus-map.go
  pkg/tool/gen-disk-skus-map_test.go
  pkg/tool/skus-sample.json
Labels: approved, lgtm, cncf-cla: yes, size/L, ok-to-test

#2788 test: add UT for filewatcher
  pkg/filewatcher/filewatcher.go
  pkg/filewatcher/filewatcher_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#2810 test: add UT negative case for filewatcher
  pkg/filewatcher/filewatcher.go
  pkg/filewatcher/filewatcher_test.go
Labels: size/M, approved, lgtm, cncf-cla: yes, ok-to-test

#2812 fix: wrong node matching when detaching dangling disk
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
Labels: kind/bug, approved, cncf-cla: yes, size/L

#2815 Revert "fix: wrong node matching when detaching dangling disk"
  pkg/azuredisk/azure_controller_common.go
  pkg/azuredisk/azuredisk.go
  pkg/azuredisk/azuredisk_test.go
Labels: approved, cncf-cla: yes, size/L

#2819 fix: remove duplicated imagePullSecrets deployment config
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
Labels: kind/bug, size/XS, approved, lgtm, cncf-cla: yes

#2820 test: improve ut coverage
  .github/workflows/linux.yml
  pkg/azureutils/azure_disk_utils.go
  pkg/azureutils/azure_disk_utils_windows.go
Labels: size/M, approved, cncf-cla: yes, kind/test

#2823 [release-1.29] fix: remove duplicated imagePullSecrets deployment config
  charts/latest/azuredisk-csi-driver-v1.29.12.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2822 [release-1.30] fix: remove duplicated imagePullSecrets deployment config
  charts/latest/azuredisk-csi-driver-v1.30.7.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2821 [release-1.31] fix: remove duplicated imagePullSecrets deployment config
  charts/latest/azuredisk-csi-driver-1.31.2.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2829 doc: fix chart README doc
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#2833 test: fix trivy action failure due to CVE-2024-45336
  .github/workflows/trivy.yaml
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#2834 chore: upgrade CSI driver sidecar image versions
  charts/README.md
  charts/latest/azuredisk-csi-driver-v0.0.0.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes

#2837 [release-1.31] chore: upgrade CSI driver sidecar image versions
  charts/README.md
  charts/latest/azuredisk-csi-driver-1.31.2.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes

#2839 [release-1.29] chore: upgrade CSI driver sidecar image versions
  charts/latest/azuredisk-csi-driver-v1.29.12.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2838 [release-1.30] chore: upgrade CSI driver sidecar image versions
  charts/README.md
  charts/latest/azuredisk-csi-driver-v1.30.7.tgz
  charts/latest/azuredisk-csi-driver/values.yaml
  deploy/csi-azuredisk-controller.yaml
  deploy/csi-azuredisk-node-windows-hostprocess.yaml
  deploy/csi-azuredisk-node-windows.yaml
  deploy/csi-azuredisk-node.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes
